- doc/developer-guide.md
This patch updates the developer guide documentation to reference the stable/main branches rather than the main/develop branches, as we have now switched to using those.
> Update developer guide with correct branch names

- source/cl/include/cl/macros.h
This should help the compiler lay out the code more optimally.
> [CL] Mark OCL_CHECK branches as 'unlikely'

- modules/compiler/test/lit/passes/pipeline-components.ll
- modules/compiler/tools/muxc/muxc.cpp
- modules/compiler/tools/muxc/muxc.h
This commit refactors how muxc sets up its machinery. It now creates
everything required by the driver in one place: setupContext. This makes
it easier to track the context and see what's intitialized when.
It also now parses the input file before creating the pass machinery.
This more closely resembles the compiler flow, allowing us to bring the
two frameworks closer together.
This allows us to use three LLVM options checked by the BaseContext
constructor in a more intuitive way, i.e., without using
CA_LLVM_OPTIONS.
> [muxc] Refactor creation/setup methods

- scripts/testing/city_runner/cts.py
- scripts/testing/city_runner/test_info.py
Modify the City Runner test scripts for use with SYCL-CTS.
SYCL-CTS tests produce a different format of output, requiring different parsing to identify passing tests. Furthermore, test names can be more complex, including whitespace and punctuation characters, so the entries in the CSV test list file need to be parsed more carefully.
The City Runner will now accept as passing a test that outputs "All tests passed".
The City Runner will now accept quoted and escaped strings containing spaces as part of the test command line arguments column in the CSV file.
> Modify the Run Cities script to work with SYCL-CTS

- modules/compiler/builtins/abacus/README.md
Fix a link in the documentation
The link was broken.
I fixed the link.
* Run [clang-format-9](https://clang.llvm.org/docs/ClangFormat.html) on all modified code.
> Fix relative link to abacus.md

- source/cl/test/UnitCL/CMakeLists.txt
- source/cl/test/UnitCL/include/kts/sub_group_helpers.h
- source/cl/test/UnitCL/source/kts/sub_group_helpers.cpp
- source/cl/test/UnitCL/source/sub_groups.cpp
This is in the anticipation that the tests for the cl_intel_required_subgroup_size extension will want to use them.
> [UnitCL] Split out some sub-group helper methods

- modules/compiler/targets/host/source/HostPassMachinery.cpp
This doesn't appear to be necessary - none of the other targets require it.
> [host] Remove workaround for no-opt barrier pass

- modules/compiler/tools/muxc/muxc.cpp
These were caught by some nightly jobs compiling with GCC 7.5.0. It couldn't convert from std::unique_ptr<T> to
llvm::Expected<std::unique_ptr<T>>.
Using std::move appears to be what LLVM code does, so we can follow that idiom.
> [muxc] Fix for older GCC versions

- cmake/AddCA.cmake
My recent fix for older GCC versions broke newer ones. LLVM's own code disables this warning, so we should too.
> Fix the build for GCC 9+

- doc/getting-started.rst
- examples/technical_blogs/refsi_simple_blog1/Dockerfile
- modules/compiler/spirv-ll/test/CMakeLists.txt
- source/cl/test/UnitCL/kernels/CMakeLists.txt
This is only strictly required for testing, so we can relax its
requirement somewhat.
The old fatal error message was referring to UnitCL SPIR-V tests which
isn't true; the SPIR-V tests will indeed run successfully, as they've
been pre-compiled to .spv files. It's the offline tests that won't,
because we can't detect spirv-as at build time.
> Remove requirement on spirv-tools

- source/cl/source/extension/CMakeLists.txt
- source/cl/source/extension/include/extension/extension.h
- source/cl/source/extension/include/extension/intel_required_subgroup_size.h
- source/cl/source/extension/source/extension.cpp.in
- source/cl/source/extension/source/intel_required_subgroup_size.cpp
- source/cl/source/opencl-3.0.cpp
This requires a new extension entry-point for clGetKernelSubGroupInfo.
Disabled by default until the implementation is complete.
> [cl] Add stub files for the cl_intel_required_subgroup_size extension

- .github/workflows/create_llvm.yml
This adds a matrix of operating systems, llvm versions and build types to create multiple caches which can be used in other jobs at a later point.
Previously build llvm caches are required in order to run MRs as compiling llvm would take too long and specific cmake flags are used to build the right versions (including disabled zlib).
Added a workflow to iterate through operating systems, llvm versions and build types and create cached builds for each. Windows failed to build and this will be addressed in a later commit.
Note this must only be run on 'main' in order for MR testing to work on a pull request.
* Make sure the project builds successfully …
> Produce llvm cache build for use in MR and nightly testing

- modules/compiler/source/base/source/program_metadata.cpp
Support for Ubuntu18 is deprecated but we still have some old jobs that use it. Until we drop support properly, we can workaround a compile issue with an explicit std::move.
> [compiler] Fix build failure on older compilers

- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/intel_opt_none.spvasm
- modules/compiler/spirv-ll/tools/spirv-ll.cpp
- source/cl/source/binary/source/spirv.cpp
closes [DDK-245](https://jira.office.codeplay.com/browse/DDK-245)
To be able to run tests with yet to release oneAPI packages, support for OptNoneINTEL capability and SPV_INTEL_optnone extension is required.
To support OptNoneINTEL capbility, llvm attributes; `OptimizeNone` and `NoInline` are enabled if the respective function control bit is set.
A new .spvasm test is added to test the OptNoneINTEL capability. 
* Run [clang-format-9](https://clang.llvm.org/docs/ClangFormat.html) on all modified code.
> Adding OptNoneINTEL capability support

- modules/compiler/spirv-ll/include/spirv-ll/opcodes.h
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/context.cpp
- modules/compiler/spirv-ll/source/opcodes.cpp
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/op_execution_mode_subgroup_size.spvasm
- modules/compiler/spirv-ll/test/spvasm/op_execution_mode_subgroups_per_workgroup.spvasm
- modules/compiler/spirv-ll/test/spvasm/op_get_default_queue.spvasm
- modules/compiler/spirv-ll/test/spvasm/op_get_kernel_max_num_subgroups.spvasm
- modules/compiler/spirv-ll/test/spvasm/op_get_kernel_preferred_work_group_size_multiple.spvasm
- modules/compiler/spirv-ll/tools/spirv-ll.cpp
- source/cl/source/binary/source/spirv.cpp
- source/cl/source/extension/CMakeLists.txt
- source/cl/test/UnitCL/kernels/ext_reqd_subgroup.01_size8.spvasm32
- source/cl/test/UnitCL/kernels/ext_reqd_subgroup.01_size8.spvasm64
- source/cl/test/UnitCL/kernels/kernel_source_list.cmake
- source/cl/test/UnitCL/source/cl_intel_required_subgroup_size/cl_intel_required_subgroup_size.cpp
----
[spirv-ll] Support the 'SubgroupSize' ExecutionMode
This commit extends our SPIR-V consumer to understand the `SubgroupSize`
execution mode. It does so to accomodate both higher-level standards
like SYCL 2020 which have a `reqd_sub_group_size` attribute and OpenCL
which has `intel_reqd_sub_group_size` (via an extension). Although
there's no mandate that this execution mode should encode this data,
that's what tools like DPC++ do in practice and so we should handle
that.
This is awkward for us, as `SubgroupSize` comes as part of the
`SubgroupDispatch` capability, which in turn implicitly defines the
`DeviceEnqueue` capability. The OpenCL environment spec explicitly says
we are not required to support `DeviceEnqueue` as we don't support
device-side enqueue, but it also says that …
> Support SPIR-V 'SubgroupSize' and enable cl_intel_required_subgroup_size by default

- modules/compiler/multi_llvm/include/multi_llvm/opaque_pointers.h
- modules/compiler/multi_llvm/include/multi_llvm/optional_helper.h
- modules/compiler/source/base/source/base_module_pass_machinery.cpp
- modules/compiler/source/base/source/module.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/targets/host/source/HostPassMachinery.cpp
- modules/compiler/targets/host/source/kernel.cpp
- modules/compiler/targets/host/source/target.cpp
- modules/compiler/utils/include/compiler/utils/StructTypeRemapper.h
- modules/compiler/utils/source/align_module_structs_pass.cpp
- modules/compiler/utils/source/barrier_regions.cpp
- modules/compiler/utils/source/lld_linker.cpp
- modules/compiler/utils/source/mangling.cpp
- modules/compiler/utils/source/pass_machinery.cpp
- modules/compiler/utils/source/replace_c11_atomic_funcs_pass.cpp
- modules/compiler/utils/source/replace_mem_intrinsics_pass.cpp
- modules/compiler/vecz/source/transform/basic_mem2reg_pass.cpp
- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- modules/compiler/vecz/source/transform/scalarizer.cpp
- modules/compiler/vecz/source/vector_target_info_riscv.cpp
- modules/compiler/vecz/tools/source/veczc.cpp
This fixes all of the known *compile time* issues when building the construction kit with LLVM llvm/lllvm-project@89f4933. There are known issues when running, so it is not advised or advertised as working.
> Update construction kit to build with LLVM 17

- modules/compiler/test/lit/passes/barriers-controlled-mem-fence.ll
- modules/compiler/utils/include/compiler/utils/barrier_regions.h
- modules/compiler/utils/source/barrier_regions.cpp
- modules/compiler/utils/source/handle_barriers_pass.cpp
The Handle Barriers Pass creates new Mux Memory Barrier calls in between barrier regions. The arguments of this call come from the arguments of the barrier calls inside the original function. When these arguments are constant integers, all is good. However, when the arguments are expressions in the IR of the original function, the result is using values from the original Function inside the wrapper Function, which is not valid IR.
We should not be generating invalid IR from any of our passes.
When building the new Mux Memory Barrier, we now check for any non-constant arguments and pull them from the first instance of the barrier struct where necessary. The code used by the Barrier Regions to access data in the barrier struct has been made accessible through the public header …
> Retrieve values from barrier struct for use in new memory barriers

- .github/workflows/run_pr_tests.yml
If a PR only touched modules/, as #55 does, the PR actions weren't triggering due to this typo.
> [ci] Fix typo causing some PR workflows not to trigger

- examples/refsi/refsi_g1_wi/compiler/refsi_g1_wi/include/refsi_g1_wi/refsi_pass_machinery.h
- examples/refsi/refsi_g1_wi/compiler/refsi_g1_wi/source/module.cpp
- examples/refsi/refsi_g1_wi/compiler/refsi_g1_wi/source/refsi_pass_machinery.cpp
- examples/refsi/refsi_m1/compiler/refsi_m1/include/refsi_m1/module.h
- examples/refsi/refsi_m1/compiler/refsi_m1/include/refsi_m1/refsi_pass_machinery.h
- examples/refsi/refsi_m1/compiler/refsi_m1/source/module.cpp
- examples/refsi/refsi_m1/compiler/refsi_m1/source/refsi_pass_machinery.cpp
- modules/compiler/cookie/{{cookiecutter.target_name}}/include/{{cookiecutter.target_name}}/{{cookiecutter.target_name}}_pass_machinery.h
- modules/compiler/cookie/{{cookiecutter.target_name}}/source/module.cpp
- modules/compiler/cookie/{{cookiecutter.target_name}}/source/{{cookiecutter.target_name}}_pass_machinery.cpp
- modules/compiler/multi_llvm/include/multi_llvm/optional_helper.h
- modules/compiler/riscv/include/riscv/module.h
- modules/compiler/riscv/include/riscv/riscv_pass_machinery.h
- modules/compiler/riscv/source/module.cpp
- modules/compiler/riscv/source/riscv_pass_machinery.cpp
- modules/compiler/targets/riscv/test/lit/passes/late-passes-pipeline.ll
This mimics the host target and centralizes pass pipeline construction
while also giving users of muxc access to the same pipeline
functionality.
It also allows us to centralize the parsing of `CA_RISCV_VF`, which was
done in two different places whose logic had to match, otherwise bad
things would happen.
> [compiler] Move riscv/refsi/cookie pipeline handling into the PassMachineries

- examples/refsi/refsi_g1_wi/compiler/refsi_g1_wi/source/refsi_mux_builtin_info.cpp
- modules/compiler/multi_llvm/include/multi_llvm/multi_llvm.h
- modules/compiler/source/base/source/program_metadata.cpp
- modules/compiler/source/base/source/spir_fixup_pass.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/targets/host/source/HostMuxBuiltinInfo.cpp
- modules/compiler/test/CMakeLists.txt
- modules/compiler/test/mangling.cpp
- modules/compiler/utils/CMakeLists.txt
- modules/compiler/utils/include/compiler/utils/mangling.h
- modules/compiler/utils/include/compiler/utils/target_extension_types.h
- modules/compiler/utils/source/cl_builtin_info.cpp
- modules/compiler/utils/source/degenerate_sub_group_pass.cpp
- modules/compiler/utils/source/dma.cpp
- modules/compiler/utils/source/group_collective_helpers.cpp
- modules/compiler/utils/source/link_builtins_pass.cpp
- modules/compiler/utils/source/mangling.cpp
- modules/compiler/utils/source/optimal_builtin_replacement_pass.cpp
- modules/compiler/utils/source/replace_async_copies_pass.cpp
- modules/compiler/utils/source/scheduling.cpp
- modules/compiler/utils/source/target_extension_types.cpp
- modules/compiler/utils/source/unique_opaque_structs_pass.cpp
- modules/compiler/vecz/source/vectorization_context.cpp
This starts to teach the compiler about Target Extension Types[1], which we will start to expect and accommodate in LLVM 17.
The reason for this is that clang will now generate `spirv.Event`, `spirv.Sampler` and `spirv.Image` types for the corresponding OpenCL types. The plan is to make `spirv-ll` generate these types too, so that the IR is in a consistent format for each version. The decision about SPIR 1.2 is still undecided.
These types are beneficial for us because they are better defined than the previous solution of pointers to opaque structs with specific names - primarily because opaque pointers make it difficult or impossible to actually determine these types.
The target extension types, however, can not reach the backend unless that backend can actually work with them. Therefore …
> [compiler] Accommodate Target Extension Types in metadata & mangling

- modules/compiler/spirv-ll/source/builder_core.cpp
The SPIR-V builder (`spirv_ll::builder`) no longer propagates Alignment Decorators down Access Chains.
SYCL-CTS tests were failing on RiscV because of unaligned memory access errors.
Applying the same alignment to the result of a GEP as the alignment of the base pointer doesn't make any sense in general, since there is no reason that an individual element needs to have the same alignment, especially when it is access to a member of a struct. A struct is likely to be aligned according to its largest member, but may contain smaller members that are not so aligned.
When processing the SPIR-V IR opcodes `OpAccessChain`, `OpPtrAccessChain`, `OpInBoundsAccessChain` and `OpInBoundsPtrAccessChain`, any alignment decorators (`OpDecorate`) that were applied to the base pointer would also be applied …
> Don't propagate alignment decorations down access chains

- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/subgroup_broadcast.ll
Vecz now vectorizes a sub group broadcast of a uniform value by turning it into a NOP.
Sub group broadcasts of uniform values would crash the packetizer.
Vecz now vectorizes a sub group broadcast of a uniform value by turning it into a NOP. Broadcasts of uniform values across threads within a vectorization group are handled automatically by the packetizer and do not need to be explicitly turned into vector splats. If the incoming source value is uniform, the index operand becomes irrelevant.
A new LIT test has been created to prevent regression.
> Subgroup broadcast of uniform value becomes a NOP

- .github/workflows/run_pr_tests.yml
Add PR testing for clang-format
The current PR testing does not check new code obeys the clang-format restrictions
Added to the PR testing workflow a small clang-format-diff line to check for breakages.
* Run [clang-format-9](https://clang.llvm.org/docs/ClangFormat.html) on all modified code.
> Add PR testing for clang-format

- modules/compiler/source/base/source/image_argument_substitution_pass.cpp
- modules/compiler/test/CMakeLists.txt
- modules/compiler/test/utils.cpp
- modules/compiler/utils/include/compiler/utils/metadata.h
- modules/compiler/utils/include/compiler/utils/pass_functions.h
- modules/compiler/utils/source/align_module_structs_pass.cpp
- modules/compiler/utils/source/metadata.cpp
- modules/compiler/utils/source/pass_functions.cpp
This provides some groundwork for an upcoming change to the kernel ABI with regards to samplers. I've split this prep work away from that main change, in case we want to land it later, or revert it later on.
Each change is tested with UnitCompiler, so should be safe to land with a pass to make use of them.
> [compiler] Make some utilities more flexible

- modules/compiler/utils/source/pass_functions.cpp
We were taking a reference to a function's base name (or just plain name) and then change that name afterwards, leaving the StringRef in an invalid state.
> [compiler] Fix a use-after-free

- doc/modules/compiler/utils.rst
- modules/compiler/source/base/source/base_module_pass_machinery.cpp
- modules/compiler/source/base/source/base_pass_registry.def
- modules/compiler/test/lit/passes/replace-image-tys.ll
- modules/compiler/utils/CMakeLists.txt
- modules/compiler/utils/include/compiler/utils/builtin_info.h
- modules/compiler/utils/include/compiler/utils/replace_target_ext_tys_pass.h
- modules/compiler/utils/source/builtin_info.cpp
- modules/compiler/utils/source/mux_builtin_info.cpp
- modules/compiler/utils/source/replace_target_ext_tys_pass.cpp
The target extension types introduced in LLVM 17 pose a problem for us because no upstream backend supports the "spirv" types and will crash when lowering them. This means we must replace them across the module with "real" types.
This commit introduces a new pass and extension to the BuiltinInfo to provide the target with a way to customize how target extension types are removed from the module by replacing them with other types.
Events and samplers are replaced with `i32` types, and images are replaced with a pointer to `MuxImage` (which is just a mux-friendly rename of the undocumented `struct.Image` structure the ImageArgumentSubstitutionPass currently uses).
Note that functions are replaced in-place (i.e., without wrappers) as a wrapper would still keep the types lingering around in …
> [compiler] Add a pass to replace target extension types

- cmake/ImportLLVM.cmake
- modules/compiler/builtins/cmake/FindBuiltinsTools.cmake
Fix warning that max version is 16.0.4 for LLVM and version checking strings
We are promoting llvm version 16.0.6 as the one to use for LLVM 16. Also the builtins compiler version was including spacing causing errors.
Changed version in CMakeLists.txt. Also added quotes around llvm tool version error report checking to help assist debugging issues in this area and fixed the tool version checking to not include spaces.
> Fixed upper version of LLVM to be 16.0.6 and fixed version checking

- modules/compiler/test/lit/passes/replace-event-tys.ll
- modules/compiler/utils/source/replace_target_ext_tys_pass.cpp
This fixes an oversight in the pass that replaces target extension types, where previously it was skipping those types used in arrays or structs.
Out of these, only arrays of events (and structs containing those) seem possible in OpenCL C, but neither LLVM nor SPIR-V make no such restrictions on aggregate types, so supporting everything is more correct here.
> [compiler] Replace target extension types in aggregates

- modules/compiler/source/base/source/image_argument_substitution_pass.cpp
- modules/compiler/source/base/source/module.cpp
- modules/compiler/test/lit/passes/image-arg-subst-tgt-tys.ll
When running this pass we require that the target extension types have already been replaced with mux-compatible types: a pointer for images and i32 for samplers. This means we need to do subtly different things depending on the LLVM version.
This also schedules the target extension type replacement pass in the defualt compiler pipeline, meaning LLVM 17 is now more-or-less ready to go for OpenCL and SPIR-V inputs. SPIR 1.2 is known to be broken and will be removed shortly.
> [compiler] Update ImageArgumentSubstitutionPass for LLVM 17

- .github/workflows/run_pr_tests.yml
The diff was mistakenly reversed so we weren't actually checking the PR branch's commits: we were effectively checking 'main' for formatting errors.
> Fix clang-format CI job

- modules/compiler/targets/host/source/target.cpp
This code was just copied from the
OrcV2Examples/LLJITWithGDBRegistrationListener example. It provides a better debugging experience for jitted kernels, allowing the debugger to step into kernels, disassemble the kernel, etc.
It also removes the need for a workaround specific to 64-bit linux targets with LLVM 17, so the code is cleaner and more universal as a result.
> [host] Add better debugger integration with OrcJIT

- doc/developer-guide.md
- doc/overview/compiler/supported-llvm-versions.rst
Updated documentation to mention 16.0.6 LLVM versions and removed out of date references to ca-llvm
Documentation was out of date on versions used and made an out of date reference.
Updated reference of LLVM versions to use. Also deleted any references to ca-llvm.
> Updated documentation to mention 16.0.6 LLVM versions

- modules/compiler/builtins/include/builtins/builtins-3.0.h
- modules/compiler/builtins/include/builtins/clbuiltins-3.0.h
- modules/compiler/builtins/scripts/generate_header_30.sh
This fixes up a mistake where recent changes to the sub-group builtin
declarations and definitions were not auto-generated using the script
and were instead done manually.
There are a few bugs that are fixed by this:
* We were missing some declarations, and only providing definitions.
* Some declarations were marked `convergent` but the definitions
weren't. Now both are `convergent` as intended.
* We were providing 'mul' operations on the 'bool' type which isn't
strictly required by the extension we support.
Also allow any clang-format version when using this script. The reasoning
being that some systems may not explicitly version their
clang-format binaries. If this picks up the wrong version (i.e., not the
one specified in the root CMakeLists.txt), then it's still better than
not …
> [builtins] Auto-generate sub-group builtins

- cmake/AddCA.cmake
Always set `-Wno-maybe-uninitialized` for GCC above version 10.
Silence a wall of warnings which keep coming back every time a new GCC version is releases without this [bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96564) being fixed. This was supposed to be fixed in 11.4, then moved to 11.5, after which the ticekt has not been updated again. GCC 13 is now available.
Remove the upper bound on the version check to set the `-Wno-maybe-uninitialized` flag to disable warnings previously determined to be of dubious value.
> [cmake] Continue to disable -Wmaybe-uninitialized

- modules/compiler/test/group_ops.cpp
- modules/compiler/utils/include/compiler/utils/group_collective_helpers.h
- modules/compiler/utils/source/builtin_info.cpp
- modules/compiler/utils/source/cl_builtin_info.cpp
- modules/compiler/utils/source/degenerate_sub_group_pass.cpp
- modules/compiler/vecz/source/analysis/uniform_value_analysis.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
This PR just better integrates the new mux group builtins by:
* providing helper methods for common queries
* tidying up some code
* refactoring the degenerate sub-groups pass to use builtin IDs and not function name manipulation.
> [compiler] Further integrate mux group builtins

- examples/refsi/hal_refsi/external/refsidrv/source/refsidrv/refsi_device_g.cpp
- examples/refsi/hal_refsi/source/refsi_hal_g1.cpp
- examples/refsi/hal_refsi/source/refsi_hal_m1.cpp
The memory available for ELF files in RefSi has been increased to 128MB.
Some of the ELF files being created are greater than 1MB in SYCL CTS, but the refsi simulators were only setting aside less than 1MB. This caused tests to fail.
Changed defines to give a larger ELF File size in the RefSi drivers and HAL libraries
> Increase refsi elf size to cope with SYCL CTS large file creation

- modules/compiler/utils/source/builtin_info.cpp
- modules/compiler/utils/source/define_mux_dma_pass.cpp
This helps better solidify the API consistency between the identification and declaration/definition code of overloadable builtins.
Since the mux DMA read/write builtins now require the event type to declare themselves (as the event type is up to the target), we should be returning that event type when being identified. The goal is to allow a complete round-trip of identification, declaration, and definition.
> [compiler] Identify the event type for mux DMA builtins

- modules/compiler/test/lit/passes/barriers-dbg.ll
- modules/compiler/vecz/test/lit/llvm/undef_ub.ll
1. LLVM 17 re-introduced an unreachable where we haven't seen once since LLVM 13.
2. LLVM 17 changes how debug DW_OP_deref is handled when converting debug expressions. See https://reviews.llvm.org/D142160. This is apparently an improvement in debug info, but it's hard to tell. It's also unclear what we're meant to be doing with debug info in this pass as our support for debug info is generally lacking, so for now we'll just accept LLVM 17's output without questioning it too much.
> [compiler] Fix a couple of lit tests with LLVM 17

- modules/compiler/riscv/source/target.cpp
This feature is no longer 'experimental'
> [riscv] Update name of zvfh feature for LLVM 17

- modules/compiler/test/lit/passes/replace-target-tys-dbg.ll
- modules/compiler/utils/source/replace_target_ext_tys_pass.cpp
We were remapping functions and cloning their distinct debug info, but leaving it orphaned. LLVM has a flag for this - to update those pieces of metadata in place.
> [compiler] Fix bad debug into in ReplaceTargetExtTysPass

- modules/compiler/test/lit/passes/barriers-assume-like-intrinsics.ll
- modules/compiler/utils/source/barrier_regions.cpp
In the barriers pass, when a live var is an alloca instruction, we replace it and all of its uses directly with a GEP into the live variable struct.
This is unsafe to do in the presence of "assume-like" intrinsics, as the new memory region is not the same as the old one. Some interesting examples include `llvm.assume`, whose assumption may no longer hold, `llvm.lifetime.*` intrinsics, as the lifetime of the GEP is not equal to that of the alloca, and `llvm.invariant.*` intrinsics.
This doesn't seem to have shown up as a problem before LLVM 17, where a `llvm.lifetime.start` intrinsic using an alloca with the *base address* of the live variables struct. This lifetime intrinsic was being called after a store to *another* member of the live variables struct that we inserted during the pass. …
> [compiler] Remove assume-like intrinsics used by allocas

- examples/refsi/hal_refsi/external/refsidrv/source/refsidrv/kernel_dma.cpp
- examples/refsi/refsi_m1/compiler/refsi_m1/source/refsi_mux_builtin_info.cpp
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_1d.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_1d_tgt_tys.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_2d_tgt_tys.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_3d.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_3d_tgt_tys.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_wait_tgt_tys.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_1d_tgt_tys.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_2d.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_2d_tgt_tys.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_3d.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_3d_tgt_tys.ll
On LLVM 17, the `target("spirv.Event")` type has been replaced with i32s
by the `ReplaceTargetExtTysPass`, so the RefSi M1 DMA implementation
must account for that.
Luckily, this makes the code simpler to deal with, as we don't have to
fudge between pointers and integers.
This also extends the HAL to handle 32-bit truncating stores to the 64-bit DMA
registers, as it's difficult to get LLVM to stop optimizing codegen in that direction
when it can. This might not be the ideal solution but it should be technically sound.
> [refsi_m1] Update DMA implementation for LLVM 17

- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/intel_memory_access_aliasing.spvasm
- modules/compiler/spirv-ll/tools/spirv-ll.cpp
- source/cl/source/binary/source/spirv.cpp
To get sycl-nbody runwith oneapi-construction-kit and dpc++, `OpCapability MemoryAccessAliasingINTEL` support is needed.
While trying to run sycl-nbody with oneapi-cnstruction-kit, we get the error:
`error: OpCapability MemoryAccessAliasingINTEL (#5910) not supported by device`.
As for now just the basic pass through is added. A proper fix may be added later.
> Add basic pass through for OpCapability MemoryAccessAliasingINTEL 

- modules/compiler/builtins/abacus/generate/abacus_detail_integer/abacus_detail_integer.in
- modules/compiler/builtins/abacus/generate/abacus_integer/abs_and_abs_diff.in
- source/cl/test/UnitCL/kernels/kernel_source_list.cmake
- source/cl/test/UnitCL/kernels/regression.108_absdiff_int.cl
- source/cl/test/UnitCL/kernels/regression.108_absdiff_int.spvasm32
- source/cl/test/UnitCL/kernels/regression.108_absdiff_int.spvasm64
- source/cl/test/UnitCL/source/ktst_regression_05.cpp
Doing the subtraction in signed types would cause the compiler to assume no underflow, which is not a valid assumption. In C, the assumption that there's no underflow means clang adds `nsw` flags to the subtraction(s).
It appears that LLVM 17 was finally able to make use of these flags and optimize the IR such that our implementation was proven incorrect.
> [abacus] Fix abs_diff implementation

- modules/compiler/utils/include/compiler/utils/cl_builtin_info.h
- modules/compiler/utils/source/cl_builtin_info.cpp
- modules/compiler/vecz/test/lit/llvm/constant_address_with_uniform.ll
- modules/compiler/vecz/test/lit/llvm/diverging_loop.ll
- modules/compiler/vecz/test/lit/llvm/diverging_nested_loop.ll
- modules/compiler/vecz/test/lit/llvm/scalar_load_store_in_varying_branch.ll
- modules/compiler/vecz/test/lit/llvm/scalar_splat.ll
- modules/compiler/vecz/test/lit/llvm/scalar_splat_after_load_store_in_varying_branch.ll
- modules/compiler/vecz/test/lit/llvm/scalar_splat_after_varying_branch.ll
- modules/compiler/vecz/test/lit/llvm/scalar_splat_in_varying_branch.ll
- modules/compiler/vecz/test/lit/llvm/secretly_scalar_load_store.ll
- modules/compiler/vecz/test/lit/llvm/uniform_loop.ll
- modules/compiler/vecz/test/lit/llvm/uniform_loop_metadata.ll
- modules/compiler/vecz/test/lit/llvm/unmangled_builtin_call.ll
This PR removes unnecessary use of `multi_llvm` from `CLBuiltinInfo`, and also removes some queries on OpenCL builtins which are never reached, as those OpenCL builtins are now mapped to mux builtins early on.
The aim is just to clean up `CLBuiltinInfo` so it serves as a better reference for any other `BuiltinInfo` implementations.
> [compiler] Clean up CLBuiltinInfo

- .github/workflows/run_pr_tests.yml
Fix for workflows continuing to run after branch pushed to again
We were seeing multiple workflows running for the same PRs when the branch was pushed to again.
The fix is to add a concurrency/cancel-in-progress to the workflow.
> Fix for workflows continuing to run after branch pushed to again

- modules/compiler/test/lit/passes/subgroup-loop-unroll.ll
- modules/compiler/utils/source/handle_barriers_pass.cpp
The Handle Barriers Pass needs to account for the case that `compiler::utils::createLoop()` can do its own loop unrolling.
UnitCL tests were failing on Arm because of a vectorization factor that enabled the vector reduction loops to be unrolled, resulting in bad code.
The IR generation for reduction loops no longer assumes that `createLoop()` has to return an empty exit block. When it unrolls, it will populate the block with the actual iterations, and then return that. In this case, we don't need to create an LCSSA Phi node and can return the accumulator directly.
A lit test is also included.
> Account for loop unrolling in compiler::utils::createLoop()

- modules/compiler/test/group_ops.cpp
- modules/compiler/utils/include/compiler/utils/builtin_info.h
- modules/compiler/utils/source/builtin_info.cpp
This commit allows users to get the mux builtin ID corresponding to a `utils::GroupCollective`.
This could be useful to programmatically mutate a group collective, such as changing a sub-group operation to a work-group one, or changing an inclusive scan to an exclusive one.
In the absence of any concrete users, this enables round-trip testing of `ID -> GroupCollective -> ID` in `UnitCompiler`.
> [compiler] Provide a mapping from GroupCollective -> BuiltinID

- modules/compiler/vecz/source/vectorization_context.cpp
I'm not entirely sure what's going on here or why the compiler didn't warn about an unused variable, but this is obviously unnecessary.
> [vecz] Remove dead/discarded function demangle

- modules/compiler/vecz/source/include/vectorization_context.h
When using asserting value handles, if the vectorizer quits unexpectedly then the cache of vectorization units remains active. When the LLVMContext finally comes to clear its memory for functions, the value handles would assert that there are still uses of the functions we'd cached. Since this happens after the time our error handlers have been detatched we'd end up bringing down the OpenCL process, unhelpfully to users.
The intended use of the handle was to catch pointers to Functions being used as keys in the map, where if we deleted that Function LLVM may allocate a new one in its place, and we'd incorrectly end up using a cached vectorization unit for the new function.
Instead we can using a poisoning value handle, which poisons itself if the value is destroyed whilethe handle is …
> [vecz] Switch from AssertingVH to PoisoningVH

- modules/compiler/vecz/source/transform/inline_post_vectorization_pass.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/subgroup_builtins.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/subgroup_scans.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/compute_vector_length.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/subgroup_reductions.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/subgroup_reductions_spv_khr_uniform_group_instructions.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_broadcast.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_builtins.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_reductions.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_reductions_spv_khr_uniform_group_instructions.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_scans.ll
This PR finally pulls apart the conflation between sub-groups and vectorized group operations into two distinct concepts.
A sub-group operation (also called a mux sub-group) operates on a set of individual invocations of the kernel function. How this is done is ultimately up to the target (we don't have any examples in tree so this is largely academic at this point).
These operations can be vectorized, increasing the effective apparent sub-group size from the user's point of view (but crucially not from the target's). For example, two invocations of the kernel may be considered a mux sub-group. If the kernel is vectorized by 4, now each invocation does the work of 4 work-items and, as such, 8 work-items are being operated on by the mux sub-group. This is the actual sub-group size from the …
> [vecz] Vectorize sub-groups on top of mux sub-groups

- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/invalid_storage_class.spvasm
This is invalid SPIR-V (unfortunately generated by DPC++) but that doesn't mean we should segfault. Instead, report an error to the user.
> [spirv-ll] Fix segfault on invalid Function storage classes

- modules/compiler/source/base/CMakeLists.txt
- modules/compiler/tools/muxc/CMakeLists.txt
If we are building with a clang/LLVM built with
`LLVM_LINK_LLVM_DYLIB=ON`, then the static clang libraries we want to
link `compiler-base` against pull in the dynamic "LLVM" library. This
isn't the case for any of our locally built LLVMs, but is the case in
some distributed versions of clang/LLVM, e.g., Ubuntu's.
We are unable to safely link against LLVM's dynamic library for various
reasons ultimately stemming from LLVM's reliance on global state. As an
LLVM library ourselves, we may end up with some LLVM symbols in our
libCL library with others in libLLVM. In the more concrete case of
`llvm::Any` this leads to subtle breakages, as seen in issue #109.
I can't find a nice way around this other than by explicitly linking
against the full paths to the filenames of the static libraries.
Also …
> [compiler] Ensure we link against static LLVM libraries

- modules/compiler/targets/host/source/kernel.cpp
- modules/compiler/targets/host/source/target.cpp
In the case that no callback was provided, we weren't checking the `Error` objects before returning a generic error, which we must do or else LLVM will crash.
Since we can't do anything with the message, we just use `llvm::consumeError` which consumes it and marks it as checked without actually doing anything.
> [host] Ensure we always check llvm::Error objects

- modules/compiler/test/lit/passes/work-item-loops-broadcast-1.ll
- modules/compiler/test/lit/passes/work-item-loops-broadcast-2.ll
- modules/compiler/test/lit/passes/work-item-loops-broadcast-3.ll
- modules/compiler/utils/source/barrier_regions.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
The code was assuming the specific value being broadcast was always available in the barrier/live-variables struct.
This is not the case when the value is previously analyzed as 'trivial' and is removed for space-saving reasons.
Note that in this case it's incorrect to simply rematerialize the value as, if it's based on the local ID, the value being broadcast will differ for each work-item receiving the broadcast, whereas we need to retrieve a specific (uniform) value computed by the work-item doing the broadcasting.
Doing this 'properly' whilst maintaining the struct trimming optimization would require either some compiler analysis to only remove values which are not (transitively) used by work-group broadcasts, or it would require special rematerialization logic to handle these values …
> [compiler] Fix segfaults in work-group broadcasts

- modules/compiler/cookie/{{cookiecutter.target_name}}/source/{{cookiecutter.target_name}}_pass_machinery.cpp
- modules/compiler/riscv/source/riscv_pass_machinery.cpp
- modules/compiler/targets/host/source/HostPassMachinery.cpp
- modules/compiler/targets/riscv/test/lit/passes/verify-reqd-sg-size-2.ll
- modules/compiler/targets/riscv/test/lit/passes/verify-reqd-sg-size-3.ll
- modules/compiler/targets/riscv/test/lit/passes/verify-reqd-sg-size.ll
- modules/compiler/test/lit/passes/degenerate-sub-groups-cloning.ll
- modules/compiler/test/lit/passes/degenerate-sub-groups-cloning2.ll
- modules/compiler/test/lit/passes/degenerate-sub-groups-reqd-size.ll
- modules/compiler/utils/include/compiler/utils/attributes.h
- modules/compiler/utils/include/compiler/utils/vectorization_factor.h
- modules/compiler/utils/source/attributes.cpp
- modules/compiler/utils/source/degenerate_sub_group_pass.cpp
- modules/compiler/utils/source/verify_reqd_sub_group_size_pass.cpp
- modules/compiler/vecz/include/vecz/pass.h
- modules/compiler/vecz/source/pass.cpp
This updates users of the vectorizer to set the desired vectorization factor according to the kernel's required sub-group size, if present. It does so using a common method, to ensure consistent behaviour.This helper method assumes that the current underlying 'mux' sub-group size is 1, as we haven't got any in-tree targets that make use of anything larger than that.
All targets consider the required sub-group size less than they do `optnone` or `-cl-wfv=never` options. This can be revisited in the future if users desire different behaviour.
> [compiler] Vectorize to any required sub-group size

- modules/mux/targets/host/source/device.cpp
- modules/mux/targets/riscv/source/device_info.cpp
This updates the list of sub-group sizes reported by both the `host` and `riscv` targets to report `1` - the trivial sub-group size.
It appears though we have to report a non-empty list. Ignoring the issues that degenerate sub-groups provide with this system, we should always be able to create a sub-group size of 1, if we don't vectorize.
We won't actually always create kernels with this sub-group size: we'll create degenerate sub-groups and we'll also vectorize, so the user can't rely on this being the *only* sub-group size they'll see if they run a kernel; this requires further work, and ideally some SYCL specification clarifications.
> [mux] Advertise a sub-group size of 1

- scripts/testing/city_runner/cts.py
Updated city runner to catch "No tests ran".
The test runner we use for running test suites like SYCL CTS does some parsing on the result. We did not catch "No tests ran" to show that all tests were skipped.
Tweaked the regular expression matching in the cts profile of city runner to catch skipped case
> Extended the parsing on our test runner to catch "No tests ran"

- modules/compiler/source/base/source/base_module_pass_machinery.cpp
- modules/compiler/source/base/source/base_module_pass_registry.def
- modules/compiler/test/lit/passes/sub-group-analysis.ll
- modules/compiler/utils/CMakeLists.txt
- modules/compiler/utils/include/compiler/utils/sub_group_analysis.h
- modules/compiler/utils/source/degenerate_sub_group_pass.cpp
- modules/compiler/utils/source/sub_group_analysis.cpp
This pass analyses a module's use of mux sub-group builtins. It returns
a map with info about every function *definition*, whether or not that
function uses mux sub-group builtins, as well as the set of mux builtin
IDs it uses.
It is unable to glean anything about function declarations, therefore
in such a case, this analysis should not be relied on for 100%
correctness; however, this is not generally a use-case that the oneAPI
construction kit supports.
The degenerate sub-groups pass can use this analysis to reduce some of
its own computations.
In the future the vectorizer will use this to automatically vectorize
kernels using sub-groups to a device-specific sub-group size.
> [compiler] Add a sub-group analysis pass

- doc/modules/compiler/utils.rst
- doc/modules/vecz/vecz.md
- doc/overview/example-scenarios/mapping-algorithms-to-vector-hardware.rst
- examples/refsi/refsi_m1/compiler/refsi_m1/source/refsi_pass_machinery.cpp
- modules/compiler/cookie/{{cookiecutter.target_name}}/source/{{cookiecutter.target_name}}_pass_machinery.cpp
- modules/compiler/riscv/source/riscv_pass_machinery.cpp
- modules/compiler/targets/host/source/HostPassMachinery.cpp
- modules/compiler/targets/riscv/test/lit/passes/verify-reqd-sg-size-2.ll
- modules/compiler/test/lit/passes/barriers-v-vp.ll
- modules/compiler/test/lit/passes/work-item-loops-entry-points.ll
- modules/compiler/utils/source/work_item_loops_pass.cpp
- modules/compiler/vecz/source/pass.cpp
This fixes a long-standing hack in the vectorizer where it would strip
the vectorized kernels of their 'kernel' status.
This wasn't anything to do with vectorization but was a legacy behaviour
owing to the fact that the vectorizer used to replace the old functions.
The `WorkItemLoopsPass` would in turn wrap every kernel it came across,
and we didn't want it wrapping up the old 'scalar' kernel since we'd
never call it: this would negatively impact compile time for no reason.
However, with the revised sub-groups model and to handle the case where
the target is not using degenerate sub-groups, we *do* want to wrap up
the unvectorized scalar kernel as it is useful as a fallback in the same
way the degenerate sub-group kernel is.
To avoid compiling unnecessary kernel wrappers, the …
> [compiler] Preserve 'entry point' on vectorized kernels

- modules/compiler/test/lit/passes/sub-group-analysis.ll
- modules/compiler/utils/include/compiler/utils/sub_group_analysis.h
This clarifies and tests that the analysis does not consider the use of mux sub-group 'setter' builtins as uses of sub-groups. This was previously under-specified.
This behaviour is because the analysis is primarily to query the use of sub-groups that the user can observe. The effects of the 'setter' builtins are not apparent to the user other than through the 'getter' builtins. They are purely to provide the scaffolding and data for these getters.
> [compiler] Clarify semantics of SubgroupAnalysis pass

- doc/specifications/mux-compiler-spec.rst
- modules/compiler/source/base/source/pass_pipelines.cpp
- modules/compiler/test/lit/passes/degenerate-sub-groups-cloning2.ll
- modules/compiler/test/lit/passes/degenerate-sub-groups.ll
- modules/compiler/test/lit/passes/sub-group-analysis.ll
- modules/compiler/utils/CMakeLists.txt
- modules/compiler/utils/include/compiler/utils/attributes.h
- modules/compiler/utils/include/compiler/utils/sub_group_usage_pass.h
- modules/compiler/utils/source/attributes.cpp
- modules/compiler/utils/source/degenerate_sub_group_pass.cpp
- modules/compiler/utils/source/metadata_analysis.cpp
- modules/compiler/utils/source/sub_group_analysis.cpp
- modules/mux/source/hal/include/mux/hal/kernel.h
- modules/mux/targets/host/include/host/executable.h
- modules/utils/targets/host/include/host/utils/jit_kernel.h
This commit better conceptualizes that a function's use of degenerate sub-groups is different from using no sub-groups at all.
The `DegenerateSubGroupPass` would confuse the two, marking functions that it couldn't detect sub-group usage in as using degenerate sub-groups. As a knock-on effect, the `GenericMetadataAnalysis` would do this too and encode both concepts as '0'. This effectively led to the same situation where a kernel using degenerate sub-groups and one using no sub-groups were legal for any work-group size.
Aside from the confusion of two separate concepts, the problem comes when the degenerate sub-groups pass is not run by a target. In this situation, if that target runs the vectorizer, then a sub-group that doesn't use sub-groups is marked as having a sub-group size equal to …
> [compiler] Encode 'no' and 'degenerate' subgroups distinctly

- examples/refsi/refsi_m1/compiler/refsi_m1/source/refsi_pass_machinery.cpp
- modules/compiler/riscv/source/riscv_pass_machinery.cpp
- modules/compiler/utils/source/metadata_analysis.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
- modules/compiler/vecz/include/vecz/pass.h
- modules/compiler/vecz/source/pass.cpp
- modules/compiler/vecz/test/lit/llvm/device-sg-size-auto.ll
- modules/compiler/vecz/test/lit/llvm/reqd-sg-size-auto.ll
- modules/compiler/vecz/tools/source/veczc.cpp
- modules/mux/source/hal/include/mux/hal/kernel.h
- modules/mux/targets/host/include/host/executable.h
- modules/mux/targets/riscv/source/device_info.cpp
- modules/utils/targets/host/include/host/utils/jit_kernel.h
This PR updates the riscv/refsi targets to automatically vectorize kernels/functions containing explicit use of sub-groups to one of the device's advertised sub-group widths.
The rationale for this is as follows: The SYCL 2020 spec has `info::device::sub_group_sizes` which returns "**_the_**" list of sub-group sizes reported by the device. The CTS expects that if it runs a kernel which (for example) returns the kernel's sub-group size to the host, then that size is found in that same device list.
This rules out the use of degenerate sub-groups. We'd have to list all the sub-group (read: work-group) sizes from 1 to 1024, which is useless for users. All of those sub-group sizes could then, in turn, be _required_ by a user, and the compiler would effectively be unable to satisfy. A user …
> [riscv][vecz] Auto-vectorize sub-group kernels to a device-specific sub-group size

- modules/compiler/targets/host/source/HostPassMachinery.cpp
- modules/mux/targets/host/source/device.cpp
- modules/mux/targets/host/source/executable.cpp
This matches what we've recently done for riscv in 798118cf.
> [host] Vectorize sub-group functions to a device size

- modules/compiler/vecz/include/vecz/vecz_target_info.h
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/source/transform/passes.cpp
- modules/compiler/vecz/source/vector_target_info.cpp
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/broadcast_vector.ll
- modules/compiler/vecz/test/lit/llvm/VectorWidening/insertelement_runtime_index.ll
- modules/compiler/vecz/test/lit/llvm/VectorWidening/widen_abs.ll
- modules/compiler/vecz/test/lit/llvm/VectorWidening/widen_binops.ll
- modules/compiler/vecz/test/lit/llvm/VectorWidening/widen_copysign.ll
- modules/compiler/vecz/test/lit/llvm/VectorWidening/widen_fma.ll
- modules/compiler/vecz/test/lit/llvm/VectorWidening/widen_fmuladd.ll
- modules/compiler/vecz/test/lit/llvm/VectorWidening/widen_fmuladd_phi.ll
- modules/compiler/vecz/test/lit/llvm/simplify-masked-memops.ll
We were alternatively under- and over-setting the alignment on vectorized loads. Under-setting the alignment is still correct, if sub-optimal.
However, the `SimplifyMaskedMemOpsPass` was ignoring the alignment of the scalar masked mem load/store builtins when optimizing to regular LLVM load and store instructions. This would over-set the alignment, meaning the compiler could assume properties about the address which were not true.
This led to riscv reporting a misaligned store exception on some SYCL CTS tests.
> [vecz] Fix alignment of load operations

- scripts/testing/city_runner/profiles/sycl_cts.py
Fixed sycl_cts profile when no output
The sycl_cts profile was using stdout without importing it.
Added import for stdout
> Fix stdout usage in city runner python script

- modules/compiler/utils/source/pass_functions.cpp
Not doing so triggers an assertion in LLVM 17. Unhelpfully, it doesn't
present a verifier error until it reaches the actual machine function
emission stage, right at the end of the compilation process.
Logically I think this makes sense - the wrapper function should not
'retain' any nodes from the wrapped function's sub-program. Those are
retained by the wrapped function itself.
This doesn't seem necessary before LLVM 17 (in that there's no
assertion), and there's no clear API with which to do it, but for
consistency's sake we now do so too.
> [compiler] Clear retained nodes from artificial sub-programs

- modules/compiler/vecz/source/analysis/stride_analysis.cpp
- modules/compiler/vecz/source/include/analysis/stride_analysis.h
- modules/compiler/vecz/source/offset_info.cpp
- modules/compiler/vecz/source/pass.cpp
- modules/compiler/vecz/test/lit/llvm/invalid_cached_assumption_regression.ll
- modules/compiler/vecz/test/lit/llvm/invalid_cached_vu_regression.ll
The StrideAnalysisResult had its own local copy of an AssumptionCache.
These were still live at the time we deleted instructions at the end of packetization, and/or tore down the vectorization process upon packetization failure.
This meant that some llvm Values could have callback handles in two assumption caches, and when one was deleted the other would hold onto garbage memory.
The fix is to use the same assumption cache in StrideAnalysisResult as is obtained from the FunctionAnalysisManager.
An additional bug was that we were ostensibly invalidating all function analyses on deleted vectorized functions, but were accidentally inverting the set of preserved analyses such that all analyses were being *preserved*, rather than invalidated.
> [vecz] Fix invalid dangling AssumptionCaches

- README.md
A few of the links in the readme still reference `computeaorta` rather than `oneapi-construction-kit` when cross referencing sections in the developers guide.
Links currently broken.
Updated links to be correct.
Nope.
> Update README Links to developers guide.

- doc/overview/tutorials/creating-a-new-mux-target/adapting-target-pass-pipeline.rst
- doc/overview/tutorials/creating-new-hal/hal-operations-step-03-loading-programs.rst
- doc/overview/tutorials/creating-new-hal/initial-setup.rst
- doc/overview/tutorials/creating-new-hal/running-kernels/kernel-argument-packing.rst
- doc/overview/tutorials/creating-new-hal/running-kernels/simple-kernel-scheduling.rst
- hal/docs/hal.md
- source/cl/test/UnitCL/README.md
This PR fixes a number of small issues (typos, inconsistencies, etc.) that I found while going through the two tutorials (HAL and ComputeMux).
Improve doc quality and make it easier to follow.
Maybe the only noteworthy change is the fix to the pseudo code of the rewrite pass.  As I implemented a kernel interface adapter in C instead of using an LLVM pass, the wrong pseudo code tripped me up initially.  I then peeked at what the reference rewrite pass was doing and found the mismatch.
> Fix various small issues found in the tutorial docs

- README.md
Adding the documentation to  get the official Intel base toolkit to run and test with OCK.
Intel official base toolkit can be acquired from the Intel website, and can be used to build with OCK. The instructions are slightyly different from using the pre-release or nightly builds of Intel oneAPI, hence adding the documentation to download, install and test using the official toolkit.
> Add instructions to use OCK with official intel base toolkit

- modules/compiler/spirv-ll/source/builder_core.cpp
- source/cl/test/UnitCL/kernels/CMakeLists.txt
- source/cl/test/UnitCL/kernels/clSetProgramSpecializationConstant.fp16.spvasm32
- source/cl/test/UnitCL/kernels/clSetProgramSpecializationConstant.fp16.spvasm64
- source/cl/test/UnitCL/kernels/clSetProgramSpecializationConstant.fp64.fp16.spvasm32
- source/cl/test/UnitCL/kernels/clSetProgramSpecializationConstant.fp64.fp16.spvasm64
- source/cl/test/UnitCL/kernels/clSetProgramSpecializationConstant.fp64.spvasm32
- source/cl/test/UnitCL/kernels/clSetProgramSpecializationConstant.fp64.spvasm64
- source/cl/test/UnitCL/kernels/kernel_source_list.cmake
- source/cl/test/UnitCL/source/clSetProgramSpecializationConstant.cpp
Builder::create\<OpSpecConstant\> was implemented in a way that duplicated a lot of code, and did not handle sycl::half. This change simplifies things and ensures half is handled correctly.
This change re-does Builder::create\<OpSpecConstant\> to remove the duplicated logic for creating constants, and making it more general.
The code did not support half types, which would result in an llvm_unreachable being reached.
By writing Builder::create\<OpSpecConstant\> in a more general way, half types are implicitly handled without ever needing to specifically handle half types.
I modified the existing clSetProgramSpecializationConstant tests to cover testing of both double (already implemented but missing from the test) and half (not previously implemented).
The SYCL CTS also tests half …
> [spirv-ll] Re-do Builder::create<OpSpecConstant>.

- examples/technical_blogs/tartan_blog/build_and_run_networks.py
Adding a script to build portBLAS and SYCL-DNN, and download and build vgg16 and resnet50
The purpose of this script is to add testing of VGG16 and RESNET50 with oneAPI.
This script assumes that you have already cloned the portBLAS and SYCL-DNN repositories. Additionally, you should have cloned and built the oneAPI Construction Kit. Ensure that oneAPI itself has been built in advance as well. The build dirs and cloned repositories need to be set as environment variables; 
- portBLAS_source
- SYCL_DNN_source
- path_to_oneapi 
- OCK_libCL_path
- input_image  …
> Add a script to test vgg16 and resnet50 with oneapi-construction-kit, oneapi, portBLAS and SYCL-DNN

- source/cl/include/cl/device.h
- source/cl/source/command_queue.cpp
- source/cl/source/device.cpp
- source/cl/source/platform.cpp
Release any queues left when atexit is called.
This is due to an issue with dpc++ where it can leave temporary queues unreleased. This can then have the effect on the closing down of the device.
This is resolved by registering and deregistering the queues on creation and deletion and then releasing any queues which still have an external reference when `atexit` is called.
This should be reviewed when https://github.com/intel/llvm/issues/11156 is fixed.
> Release any queues left when atexit is called.

- examples/refsi/refsi_g1_wi/compiler/refsi_g1_wi/source/refsi_pass_machinery.cpp
- modules/compiler/source/base/include/base/pass_pipelines.h
- modules/compiler/source/base/source/base_module_pass_machinery.cpp
- modules/compiler/source/base/source/base_module_pass_registry.def
- modules/compiler/source/base/source/pass_pipelines.cpp
- modules/compiler/test/lit/passes/replace-wgc.ll
- modules/compiler/test/lit/passes/work-item-loops-scan-1.ll
- modules/compiler/test/lit/passes/work-item-loops-scan-2.ll
- modules/compiler/test/lit/passes/work-item-loops-scan-3.ll
- modules/compiler/utils/include/compiler/utils/replace_wgc_pass.h
- modules/compiler/utils/source/barrier_regions.cpp
- modules/compiler/utils/source/replace_wgc_pass.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/workgroup_scans.ll
This completes the set of work-group collective functions we can support
via the 'alternative' pathway through the vectorizer and the
work-item-loops pass. They join broadcasts and reductions, which were
added a while back.
The scans are implemented using a linear work-item loop, accumulating
with each iteration of the 'X' loop. The vectorizer vectorizes them like
the sub-group scans, so the accumulator used is just the
current/previous value of scan operation so far. The vectorized
work-group merges this with the partial scan over the vector group.
The 'scans-only' parameter to the replace-wgc pass has been removed. The
pass is either run or it isn't run, depending on what the target wants
to do to support the work-group collective operations. Only the RefSi G1
WIPT example uses the old …
> [compiler] Add work-group scan support in vecz/work-item-loops

- modules/compiler/source/base/CMakeLists.txt
- modules/compiler/source/base/include/base/check_for_unsupported_types_pass.h
- modules/compiler/source/base/source/base_module_pass_machinery.cpp
- modules/compiler/source/base/source/base_module_pass_registry.def
- modules/compiler/source/base/source/check_for_unsupported_types_pass.cpp
- modules/compiler/source/base/source/module.cpp
- modules/compiler/test/lit/passes/check-for-doubles-optnone.ll
- modules/compiler/test/lit/passes/check-for-halfs-optnone.ll
- modules/compiler/test/lit/passes/check-for-halfs.ll
When targeting a device that does not support half types, if we nonetheless received input that used half types, we would rely on LLVM's software implementation using library functions from libgcc/compiler-rt which we do not provide, and receive confusing linker errors as a result. For double types, we already flagged any use of such type as an error. This change extends that check to also flag half types, so that we issue an easier-to-understand error message.
When running the OpenCL CTS proposed change to test half support (https://github.com/KhronosGroup/OpenCL-CTS/pull/1681), we get confusing linker errors when running without half support, complaining about undefined references to __extendhfsf2 and __truncsfhf2.
This change extends the existing check for double support which flags …
> [compiler] Flag uses of half types.

- modules/CMakeLists.txt
Avoids fetching SPIRV Headers when building for Native CPU
The SPIRV Headers are already fetched by llvm-spirv when building DPC++, llvm-spirv puts them in a different folder and expects them there, the `Fetch` from OCK was overriding it, which lead `cannot file #include` errors when building llvm-spirv
Remove call to `FetchContent` for `Native CPU`
> [NATIVECPU] Avoid fetching SPIRV Headers when building for SYCL Native CPU

- modules/compiler/vecz/source/transform/builtin_inlining_pass.cpp
- modules/compiler/vecz/test/lit/llvm/builtin_inlining_memcpy.ll
The inlining for memcpy was incorrectly using the destination parameter's alignment rather than the source parameter, resulting in miscompiles.
As well as fixing this issue, a test has been added.
As well as being obviously wrong, this was causing a SYCL CTS test to segfault on the host device.
Fixed a value from using DestAlignment to SourceAlignment.
N/A
> [vecz] Use correct alignment for memcpy source

- CHANGELOG.md
- examples/refsi/refsi_g1_wi/compiler/refsi_g1_wi/source/refsi_wg_loop_pass.cpp
- modules/compiler/targets/host/source/AddEntryHook.cpp
- modules/compiler/utils/include/compiler/utils/pass_functions.h
- modules/compiler/utils/source/mux_builtin_info.cpp
- modules/compiler/utils/source/pass_functions.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
This deprioritises the IVs parameter of `createLoop`, in the case that users don't wish to set it and are happy with the default of 'none'.
It also allows us to more cohesively provide a second options field which allows users to set the IV names, rather than a) adding an additional parameter to `createLoop` or b) having related values split across `createLoop` and `CreateLoopOpts`.
Split off from #158
> [compiler] Move IVs into the CreateLoopOpts struct

- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- modules/compiler/vecz/test/lit/llvm/masked_group_collective.ll
These builtins function as barriers, so masking them produces undesirable results when laying out barrier regions. For this reason, we don't mask 'regular' barriers.
These builtins are, in any case, uniform/convergent, so either all work-items or no work-items should reach that point of execution.
Also ensure the SPIR-V reduction wrapper is marked as convergent, for completeness' sake.
> [vecz] Don't mask work-group collective operations

- modules/compiler/targets/host/source/kernel.cpp
- modules/compiler/targets/host/source/target.cpp
The use of `llvm::consumeError` is just to mark the error as 'handled' - it doesn't actually report the error in any way. If there's a callback we have reported *and* handled the error, so using `llvm::consumeError` is more correctly placed in an 'else' block.
This fixes potential move-after-move errors when a compilation error happens and the callback doesn't halt execution at that point.
> [host] Fix move-after-move errors

- CHANGELOG.md
- cmake/ImportLLVM.cmake
- doc/overview/tutorials/creating-a-new-mux-target/extending-it-further.rst
- modules/mux/test/muxCloneCommandBuffer.cpp
- modules/mux/test/muxUpdateDescriptors.cpp
- source/cl/test/UnitCL/source/clEnqueueNDRangeKernel.cpp
- source/cl/test/UnitCL/source/cl_codeplay_kernel_exec_info/usm.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer/clCommandCopyBufferKHR.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer/clCommandCopyBufferRectKHR.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer/clCommandCopyImageKHR.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer/clCommandFillBufferKHR.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer/clCommandFillImageKHR.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer/clCommandNDRangeKernelKHR.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer_mutable_dispatch/clEnqueueCommandBufferKHRMutability.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer_mutable_dispatch/clGetMutableCommandInfoKHR.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer_mutable_dispatch/clUpdateMutableCommandsKHR.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer_mutable_dispatch/usm_arg_update.cpp
This updates our CMake to only accept LLVM versions 16 and above. We no longer test or support LLVM 15 so leaving CMake support for it may be misleading. It turns out we didn't error on LLVM 14 either, so that was a past mistake.
I've also removed some code that was handling compilation under C++14 and below, which we haven't supported for a wee while. This was just found by grepping for "LLVM 15".
There's still code that ostensibly handles LLVM 15 (such as in `multi_llvm`) but we can remove that gradually over time - those changes may be more intrusive as `multi_llvm` objects may become redundant and need removing (see `multi_llvm::Optional`).
> Bump minimum LLVM version to 16

- cmake/ImportLLVM.cmake
This should reduce the noise required to support newly released LLVM versions, as we don't have to explicitly opt in to all minor and patch releases. This assumes that all newer minor/patch versions are strict improvements on previous versions.
The minimum version has been kept fully qualified as it is feasible that we may require a minor/patch versions as a minimum.
> Support all LLVM versions with same maximum major version

- modules/compiler/spirv-ll/source/opcodes.cpp
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/op_group_f_mul.spvasm
This fixes a crash exposed by hacking the SYCL-CTS somewhat.
Note that due to our coarse-grained tracking of `spirv-as` versions for test purposes, this test is pessimistically run on any v2024+ version (i.e., never...), when in fact we want the as-yet unreleased v2023.5. This will be fixed up in the near future as it's a pre-existing issue.
> [spirv-ll] Ensure that GroupUniformArithmeticKHR nodes have results

- modules/compiler/spirv-ll/test/CMakeLists.txt
- modules/compiler/spirv-ll/test/lit.cfg
- modules/compiler/spirv-ll/test/lit.site.cfg.in
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/intel_memory_access_aliasing.spvasm
- modules/compiler/spirv-ll/test/spvasm/intel_opt_none.spvasm
- modules/compiler/spirv-ll/test/spvasm/op_execution_mode_max_work_dim.spvasm
- modules/compiler/spirv-ll/test/spvasm/op_group_f_mul.spvasm
- modules/compiler/spirv-ll/test/spvasm/opencl_group_async_copy_2d2d.spvasm
- modules/compiler/spirv-ll/test/spvasm/opencl_group_async_copy_3d3d.spvasm
- modules/compiler/spirv-ll/test/spvasm/subgroup_shuffle_down_intel.spvasm
- modules/compiler/spirv-ll/test/spvasm/subgroup_shuffle_intel.spvasm
- modules/compiler/spirv-ll/test/spvasm/subgroup_shuffle_up_intel.spvasm
- modules/compiler/spirv-ll/test/spvasm/subgroup_shuffle_xor_intel.spvasm
This improves our previous tracking of `spirv-as` versions which was based soley on their release year, ignoring the point release. This coarse grained system meant that we had to conditionally enable spirv-ll tests on versions far newer than the oldest version which supports them, e.g., a feature introduce in `v2022.1` couldn't be tested until `v2022.0` was released.
It also now tracks `-dev` versions, which are packaged on some distributions as the 'official' `spirv-as` binary. We treat these as the previous point release, as in testing we have discovered that `v2022.1-dev` doesn't have some features present in `v2022.1`. Thus a `dev` version decrements the point release by 1, and if that would result in a negative version, we decrement the year instead, and set the point to 9. We …
> [spirv-ll] Improve spirv-as version tracking for test features

- modules/compiler/targets/host/include/host/target.h
This has no directly visible impact since we do not care what unique_identifier's initial value is, we just use it to generate unique names, but valgrind correctly picks up on the fact that we use it without initializing it.
This change provides an initial value to `unique_identifier`.
valgrind reports that we use `unique_identifier` uninitialized.
We use `unique_identifier` only in `HostKernel::lookupOrCreateOptimizedKernel` as follows:
```c++
if (snprintf(unique_name_data, unique_name_data_length,
"__mux_host_%" PRIu64, target.unique_identifier++) < 0) {
```
We do not care what exactly we get as the ID, we just need it to be something we have not seen before. Any initial value will do, so the uninitialized use is mostly harmless and this change should have no visible effect other than …
> [host] Initialize unique_identifier.

- modules/compiler/test/lit/passes/replace-local-module-scope-vars-alignment.ll
- modules/compiler/utils/source/replace_local_module_scope_variables_pass.cpp
This pass changes accesses to local memory (in the form of globals in address space 3) to offsets into a single struct passed into the function.
However, when calculating the layout of this struct, it incorrectly assumed that the size of a type was equal to its alignment (with some special handling for arrays). This patch changes it so that the datalayout is queried directly for the size of the type.
Was causing a SYCL-CTS test to segfault when running hierarchical code.
Fixed a bug in the struct layout calculation.
Nothing.
* Run …
> [passes] Handle alignments of structs correctly with local memory

- source/cl/test/UnitCL/source/C11Atomics.cpp
- source/cl/test/UnitCL/source/ktst_compiler_barrier.cpp
- source/cl/test/UnitCL/source/ktst_regression_01.cpp
- source/cl/test/UnitCL/source/ktst_regression_02.cpp
* C11Atomics.cpp: fix local buffers. We called AddLocalBuffer(kts::N) where kts::N is 256, where we need local_work_size * sizeof(T) which is 64 * 4, which is also 256. This works out but is fragile and breaks if we get larger T, and disregards kts::localN.
* ktst_compiler_barrier.cpp, ktst_regression_02.cpp: add explicit assertions so we fail hard rather than corrupting memory if we change kts::N or kts::localN.
* ktst_regression_01.cpp: change ASSERT_TRUE to ASSERT_EQ to get a better error message if the assertion fails.
Planned work regarding atomics resulted in test failures due to incorrect use of kts::N. This is split out into a separate MR for easier review.
This change only affects our own tests. Other people see no changes.
N/A …
> [test] Review use of kts::N and kts::localN.

- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/op_ptr_access_chain.spvasm
Fix for spir-v translation to IR for OpPtrAccessChain
In some cases the indexes field for OpPtrAccessChain can be empty. The translation code currently assumes this not to be the case and checks for element decorations, resulting in a segmentation fault during SYCL CTS testing.
This fixes the empty index case by not checking the decorations in this case. There are some issues with OpMemberDecorate, so testing of the path with additional arguments requiring decorations will not be tested here.
Also some previous clang-format issues have been resolved.
Additional lit tests have been added.
> Fix for spir-v translation to IR for OpPtrAccessChain

- source/cl/include/cl/device.h
- source/cl/source/command_queue.cpp
- source/cl/source/device.cpp
- source/cl/source/platform.cpp
This reverts commit 720cab78e991ffeb6e78944e9a86a84bac7e6c60 (Release any queues left when atexit is called).
This commit tried to work around a dpc++ issue where temporary queues were not deleted. However it was possible for queues to be released from global destructors which could cause a segfault.
Reverting the workaround. https://github.com/intel/llvm/issues/11156 is the original issue on dpc++.
> Revert "Release any queues left when atexit is called."

- modules/compiler/test/lit/passes/work-item-loop-array.ll
- modules/compiler/utils/include/compiler/utils/pass_functions.h
- modules/compiler/utils/source/pass_functions.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
Handle case where the kernel function is used by an LLVM ConstantArray.
An llvm_unreachable was being hit.
Handle similarly to `llvm::ConstantExpression`.
Added test `modules/compiler/test/lit/passes/work-item-loop-array.ll `
> Handle ConstantArray in WorkItemLoopPass

- examples/refsi/refsi_m1/compiler/refsi_m1/source/refsi_mux_builtin_info.cpp
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_1d_tgt_tys_32.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_1d_tgt_tys_64.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_2d_tgt_tys_32.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_2d_tgt_tys_64.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_3d_tgt_tys_32.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_read_3d_tgt_tys_64.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_wait_32.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_wait_64.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_wait_tgt_tys_32.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_wait_tgt_tys_64.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_1d_tgt_tys_32.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_1d_tgt_tys_64.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_2d_tgt_tys_32.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_2d_tgt_tys_64.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_3d_tgt_tys_32.ll
- examples/refsi/refsi_m1/compiler/refsi_m1/test/passes/refsi_define_mux_dma_pass_write_3d_tgt_tys_64.ll
- modules/compiler/source/base/source/image_argument_substitution_pass.cpp
- modules/compiler/test/lit/passes/image-arg-subst-64.ll
- modules/compiler/test/lit/passes/image-arg-subst-tgt-tys-64.ll
- modules/compiler/test/lit/passes/image-arg-subst-tgt-tys.ll
- modules/compiler/test/lit/passes/lower-async-copies-tgt-tys.ll
- modules/compiler/test/lit/passes/replace-event-tys-64.ll
- modules/compiler/test/lit/passes/replace-image-tys-64.ll
- modules/compiler/utils/include/compiler/utils/builtin_info.h
- modules/compiler/utils/source/builtin_info.cpp
- modules/compiler/utils/source/mux_builtin_info.cpp
- modules/compiler/utils/source/replace_target_ext_tys_pass.cpp
- modules/mux/targets/host/source/command_buffer.cpp
This fixes a bug in LLVM 17 where, on 64-bit targets, the `target` types used to represent samplers and events have an implicit size/alignment of 8 bytes (as their underlying "layout type" is `ptr`). This means that it is generally invalid to replace them with `i32`, as this may break existing alignment/size assumptions that the rest of the module has made on the access of the 'old' types.
Instead, we choose to replace `target` types with `size_t` (in practice `i32` or `i64` depending on the SPIR triple). This works more or less the same way on 32-bit targets.
On 64-bit targets, however, the runtime passes samplers to kernels as 8-byte values. These values follow the existing munging via pointers on LLVM 16, but are eventually zero-extended or truncated to `i32` when they interface with …
> [compiler] Represent samplers/events internally as size_t

- source/cl/test/UnitCL/include/kts/execution.h
- source/cl/test/UnitCL/source/C11Atomics.cpp
- source/cl/test/UnitCL/source/cl_khr_extended_async_copies/extended_async.cpp
- source/cl/test/UnitCL/source/kts/execution.cpp
- source/cl/test/UnitCL/source/ktst_barrier.cpp
- source/cl/test/UnitCL/source/ktst_dma.cpp
- source/cl/test/UnitCL/source/ktst_regression_03.cpp
- source/cl/test/UnitCL/source/ktst_regression_04.cpp
- source/cl/test/UnitCL/source/ktst_regression_05.cpp
- source/cl/test/UnitCL/source/ktst_spirv.cpp
- source/cl/test/UnitCL/source/ktst_vload_vstore.cpp
More reviews, rework AddLocalBuffer.
We have UnitCL tests where we under-allocate buffers and access local memory out of bounds.
AddLocalBuffer was error-prone as it was used in conjunction with AddInputBuffer and AddOutputBuffer, which take a number of elements, whereas AddLocalBuffer takes a number of bytes. This commit changes AddLocalBuffer so that it takes a number of elements, and either an element type as a template parameter, or an element size as a function parameter. Updating the tests to use this new API revealed a number of cases where we were still under-allocating buffers.
N/A …
> [test] More reviews, rework AddLocalBuffer.

- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/subgroup_shuffle_xor.ll
This extends fixed-width vectorization capabilities to `__mux_sub_group_shuffle_xor` builtins. This isn't something that is very efficiently vectorized, because of all of the runtime indexing, which no built-in LLVM instructions/intrinsics can really make use of.
It might be preferable for some targets to go through memory. We might want to make that a codegen option in a future update.
> [vecz] Packetize sub-group shuffle_xor builtins

- modules/mux/targets/host/source/command_buffer.cpp
A recent change makes samplers passed to kernels as size_t types. Unfortunately our pre-commit testing doesn't cover image support very well and it missed that I had forgotten to update the calculated the size of samplers for the purposes of allocating the packed argument struct.
> [host] Fix calculated size of sampler types

- scripts/testing/city_runner/test_info.py
In #190 I had intended to leave the blank line handling alone, but pushed a version that did change it.
We error out on blank lines when we shouldn't.
This restores the `if not line` check that we had before and I had wanted to keep intact.
> Restore handling of blank lines

- doc/overview/compiler/supported-llvm-versions.rst
I've removed the distinction between the two targets, as we nominally support both LLVM versions on each. A bug in either target in either version of LLVM is valid to report, and as such it is more useful for users to be aware of what we *claim* to support than what we actively test. The distinction was more valid in an earlier time when riscv had its own special patched version of LLVM.
Note that this has always been an overly simplified document; it's impossible to convey exactly *what* we test in which configurations on which targets and when, without just providing access to our internal testing infrastructure.
> [doc] Update list of tested/supported LLVM versions

- source/cl/include/cl/kernel.h
- source/cl/source/extension/source/intel_unified_shared_memory/intel_unified_shared_memory.cpp
- source/cl/source/extension/source/intel_unified_shared_memory/usm-exports.cpp
- source/cl/source/extension/source/khr_command_buffer.cpp
- source/cl/source/kernel.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_kernel.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer_mutable_dispatch/usm_arg_update.cpp
Remove much special casing for USM pointers
The SYCL CTS atomic pointer tests are currently failing, and pass with this change.
The SYCL CTS reveals that the logic we had in clSetKernelArgMemPointerINTEL to detect whether the pointer arguments we passed in were valid, while supported by the cl_intel_unified_shared_memory specification, was causing valid SYCL programs to be rejected, and the specification had an open question on whether this is actually desired. This commit implements a change to just accept arbitrary pointer values, which allows us to also remove a bunch of USM special casing. …
> [USM] Accept arbitrary pointers.

- scripts/testing/city_runner/test_info.py
Fix variable name.
One more error in #190 was the spelling of filter_tests as filtered_tests, which went unnoticed during testing as testing had been done without a filter file.
This change refers to the filter_tests variable using its correct name.
Tested by running the OpenCL CTS with both `-i source/cl/scripts/cts-3.0-online-ignore-linux-host.csv` and `-i source/cl/scripts/cts-3.0-online-ignore-linux-riscv.csv` and making sure that tests run.
* …
> Fix typo in test_info.py.

- modules/compiler/vecz/source/include/transform/packetization_helpers.h
- modules/compiler/vecz/source/transform/packetization_helpers.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/VectorPredication/boscc_reduction.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/packetize_mask_varying.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/subgroup_reductions.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/subgroup_reductions_spv_khr_uniform_group_instructions.ll
The initial vecz support for vector-predication was implemented around LLVM 12, before there were intrinsics available for reduction operations. This meant that we had to work around the lack intrinsics by using regular reduction intrinsics and 'sanitizing' the input by masking out the unwanted vector elements with the neutral value.
Vector-predicated reduction intrinsics have been around since LLVM 14 so it's high time we accommodate them natively. This should lead to better code generation when vector-predicating kernels.
> [vecz] Support vector-predicated reductions natively

- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/subgroup_builtins.ll
Forgetting to normalize the broadcast ID back into the 'mux' range would produce incorrect results on an implementation where the mux sub-groups were non-trivial, or where bounds were checked. This is, as such, not currently a visible problem in the default implementation of these builtins, but rather a theoretical one.
> [vecz] Fix vectorization of sub-group broadcasts

- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/subgroup_shuffle_down.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_shuffle_up.ll
This extends fixed-width vectorization capabilities to `__mux_sub_group_shuffle_up` and `__mux_sub_group_shuffle_down` builtins. Again, these aren't very efficiently vectorized as we have to perform the shuffle for each work-item in a pseudo-scalarized fashion.
> [vecz] Packetize sub-group shuffle_(up|down) builtins

- modules/compiler/source/base/source/printf_replacement_pass.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- source/cl/test/UnitCL/include/kts/printf.h
- source/cl/test/UnitCL/kernels/kernel_source_list.cmake
- source/cl/test/UnitCL/kernels/printf.23_string_dpcpp.spvasm32
- source/cl/test/UnitCL/kernels/printf.23_string_dpcpp.spvasm64
- source/cl/test/UnitCL/source/ktst_printf.cpp
Support SYCL printf.
The way DPC++ translates `printf` is invalid and results in assertion errors when we encounter it. We could diagnose that more clearly, but more useful is to be tolerant and translate it to valid LLVM IR.
DPC++ generates invalid SPIR-V for SYCL code containing calls to __builtin_printf. Be tolerant of this.
* Builder::create<OpFunction>: treat "printf" as a special exception and make it variadic.
* getPointerToStringAsString: recognize address space casts of strings.
Tested with a local workaround for the out-of-order command queues problem, with the following SYCL program compiled and linked with DPC++ commit 34a06351da0a7581dea472a199f9803be8433868:
```c++
#include <sycl/sycl.hpp>
int main() {
sycl::queue queue;
queue.submit([&](sycl::handler &cgh) { …
```
> Support SYCL printf.

- scripts/testing/city_runner/test_info.py
Fix one more error in test_info.py.
Currently, while the filter options to run_cities.py no longer cause an error, they do not have the desired effect, filters are ignored.
In #193 I made sure that we would not error out on trying to load filter lists, but did not check that the filter lists worked as intended, and they did not, because list1.append(list2) adds list2 as a single element to list1, whereas the intent was to add each element of list2 to list1, which is what list1.extend(list2) does.
* Make sure the …
> Fix one more error in test_info.py.

- modules/compiler/spirv-ll/include/spirv-ll/module.h
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/module.cpp
- modules/compiler/spirv-ll/test/spvasm/debug_info.spvasm
The old code wouldn't work correctly when an OpLine was specified multiple times with the same line/column, because we stored only one range for each 'unique' OpLine.
This commit updates the translator to store a list of ranges for each OpLine, meaning multiple distinct ranges can be attached to the same debug location.
> [spirv-ll] Allow DILocs to span multiple ranges

- source/cl/source/extension/include/extension/khr_command_buffer.h
- source/cl/source/extension/source/khr_command_buffer.cpp
Avoid memory leak in _cl_command_buffer_khr::updateCommandBuffer.
ASAN builds were showing a memory leak when running e.g. MutableDispatchUSMTest_InvalidArgValue_Test.
In _cl_command_buffer_khr::updateCommandBuffer we need to create a plain old data descriptor, which requires storing the data externally. We have no pre-existing memory which is guaranteed to persist for long enough that we can use it, but we can add a field to UpdateInfo to hold it.
This is an alternative to #199. This is a less invasive fix. If this is picked instead of #199, I will close that one. If #199 is picked, I will close this one.
* Make sure the project builds successfully …
> Avoid memory leak in _cl_command_buffer_khr::updateCommandBuffer (alternative)

- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
Certain tests live in sub-directories relative to the current binary dir. On certain build systems, these relative binary sub-directories may not have been created at the time `spirv-as` runs, which (may) then error. This fix adds an extra `COMMAND` to ensure the binary directories are always generated.
> [spirv-ll] Fix LIT test build with 'make' build system

- modules/compiler/cookie/{{cookiecutter.target_name}}/source/module.cpp
- modules/compiler/multi_llvm/include/multi_llvm/enums.h
- modules/compiler/multi_llvm/include/multi_llvm/loop_utils.h
- modules/compiler/riscv/source/module.cpp
- modules/compiler/source/base/source/module.cpp
- modules/compiler/source/base/source/pass_pipelines.cpp
- modules/compiler/targets/host/source/target.cpp
- modules/compiler/tools/muxc/muxc.cpp
- modules/compiler/vecz/source/transform/packetization_helpers.cpp
- modules/compiler/vecz/source/transform/pre_linearize_pass.cpp
This patch adds multi_llvm support for some changes that have been made in upstream LLVM's main branch. This will not allow the build to succeed at the moment, but it will skip some errors.
Specifically:
* `CodeGenFileType` and `CodeGenOptLevel` are now enum classes and require a struct to "fake" this in LLVM 17 and earlier.
* `createSimpleTargetReduction` no longer accepts the `TargetTransformInfo` parameter. A proxy function has been added which calls the appropriate version.
* Use `getVirtualFileRef` on the file manager. Seems to work in both LLVM 17 and tip.
Adds a bit of support for LLVM tip.
We'd like to test support for LLVM tip sooner rather than later.
This change doesn't allow LLVM tip to build, but it does fix some of the trivial errors encountered while building.
N/A
* Read …
> [LLVM] Multi_llvm support for current tip changes

- modules/compiler/spirv-ll/include/spirv-ll/module.h
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/builder_glsl.cpp
- modules/compiler/spirv-ll/source/builder_group_async_copies.cpp
- modules/compiler/spirv-ll/source/builder_opencl.cpp
- modules/compiler/spirv-ll/source/module.cpp
[spirv-ll] Rename 'get' method for clarify
There are many overloaded 'get' functions in spirv-ll, and it can be
confusing whether we're getting an Op from a spv::Id, an Op from a
llvm::Value, or an Op from a llvm::Type. This is especially because
there are many variables we call variants of "ty" or "type":
* `spv::Id structType`
* `OpType *sourceOpType`
* `llvm::Type *resultType`
Tracking the types of all these variables can be difficult when many
things are declared with `auto`. One way of combatting this is by better
naming the functions which declare these types.
Second commit:
[spirv-ll] Rename 'getType' method for clarity
This is to try to help prevent it getting confused with a method that
returns a SPIR-V `OpType` value.
> [spirv-ll] Rename a couple of getter methods for clarity

- modules/compiler/spirv-ll/test/glsl/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
The LIT test system always runs tests from their source paths, even if the binaries have been offline-assembled and copied into the binary directory.
This appears to be a legacy feature of the old testing system, where all LIT tests were run from the build directory. It's arguably beneficial for the old OCK/ComputeAorta binary releases, but we don't support those any more. None of the other LIT test systems copy source files into the binary directory at configure/build time (see the compiler-lit tests as an example).
This should shave off around 12M from the size of our builds.
> [spirv-ll] Don't copy test source files to the binary directory

- cmake/ResourceCompiler.cmake
Fix dependency on resources.
Currently, when using `target_resources`, if a resource changes and we rebuild, the new resource is built but not included.
It is not the final target that depends on the resources, it is the intermediate object file. The intermediate object file was not getting regenerated when the resources changed.
* Run [clang-format-16](https://clang.llvm.org/docs/ClangFormat.html) …
> Fix dependency on resources.

- modules/compiler/spirv-ll/include/spirv-ll/builder.h
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/context.cpp
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/debug_info_builtins.spvasm
- modules/compiler/spirv-ll/test/spvasm/debug_info_params.spvasm
This PR combines two commits fixing more crash issues in our translation of SPIR-V with debug info.
First commit:
[spirv-ll] Fix and refactor parameter-type debug info
We were passing `align` to the third parameter of
`DIBuilder.createBasicType`, but that parameter is actually the
`Encoding`. This meant that we were generating debug information for
types which were, e.g., `float` for all 4-byte types or `unsigned_char`
for all 8-byte types. The align is only relevant for pointer types.
We also take the opportunity to refactor this method, taking in a ID
rather than an LLVM Type. This gives us more control over the type. For
example, LLVM pointer types won't be able to get their pointee types as
they're now opaque. Using the SPIR-V type ID we can better trace the
types.
This fixes another …
> [spirv-ll] Fix a couple more crashes in debug info translation

- cmake/ResourceCompiler.cmake
Fix dependency on resources again.
In #210, I added `OBJECT_DEPENDS` for resources and removed `add_dependencies` as it should no longer be needed. Actually, we need both: the `OBJECT_DEPENDS` documentation says target-level dependencies need to be added as well.
File-level dependencies require target-level dependencies as well. The Ninja generator works fine without them, but the Makefile generator does not.
This partially reverts #210.
recent version …
> Fix dependency on resources again.

- modules/compiler/spirv-ll/include/spirv-ll/builder.h
- modules/compiler/spirv-ll/include/spirv-ll/module.h
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/builder_glsl.cpp
- modules/compiler/spirv-ll/source/builder_group_async_copies.cpp
- modules/compiler/spirv-ll/source/builder_opencl.cpp
- modules/compiler/spirv-ll/source/context.cpp
- modules/compiler/spirv-ll/source/module.cpp
- modules/compiler/spirv-ll/tools/spirv-ll.cpp
This commit changes most internal uses of cargo data types:
* `cargo::optional<spirv_ll::Error>` -> `llvm:Error`
* `cargo::optional<T>` -> `std::optional<T>`
* `cargo::expected<T, std::string>` -> `llvm::Expected<T>`
The rationale is that `spirv-ll` is inherently an LLVM-based tool - we don't build the tool at all in an LLVM-less build - and so making use of more "standard" types should be more intuitive - returning `llvm::Error::success()` instead of `cargo::nullopt`, for instance. We can also make use of LLVM's more extensive support for dedicated error handling, compared with our hand-rolled version.
I haven't changed the 'external' (or public) APIs just yet: those which the `compiler` module makes use of. That can come later, if we so wish.
> [spirv-ll] Replace most internal uses of cargo types

- modules/mux/targets/riscv/source/kernel.cpp
- modules/mux/test/muxQueryLocalSizeForSubGroupCount.cpp
- source/cl/scripts/cts-3.0-online-ignore-linux-riscv.csv
We hadn't fully fleshed out this query on riscv. We were returning 0,0,0 (an invalid work-group size) for anything other than 1 sub-group. This was being picked up as a failure by the OpenCL-CTS.
Instead, we must return a work-group size for which the work-group would execute the same number of sub-groups as we've been asked for. The returned work-group size is always 1D, hence we only care about the 'X' dimension.
We do this by taking the maximum sub-group size we've compiled, and returning the count multiplied by that size. This is because we know the kernel variant picking algorithm favours the kernel variant with the highest legal sub-group size. If the required work-group size is invalid we must also report 0,0,0.
This fixes a test failure in the OpenCL CTS.
> [mux][riscv] Fix getLocalSizeForSubGroupCount

- modules/compiler/spirv-ll/CMakeLists.txt
- modules/compiler/spirv-ll/include/spirv-ll/builder.h
- modules/compiler/spirv-ll/include/spirv-ll/builder_glsl.h
- modules/compiler/spirv-ll/include/spirv-ll/builder_group_async_copies.h
- modules/compiler/spirv-ll/include/spirv-ll/builder_opencl.h
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/builder_glsl.cpp
- modules/compiler/spirv-ll/source/builder_group_async_copies.cpp
- modules/compiler/spirv-ll/source/builder_opencl.cpp
This goes part way towards making the handling of SPIR-V extended instruction sets more flexible and less dependent on changing `spirv-ll` itself.
By adding an abstract interface through which the handlers are registered and are asked to handle a given `OpExtInst`, users of this library may in the future be able to register their own external handlers, if we so wish. This has been a long-standing wish for the project.
In the short-term, it helpers to separate out almost all of the handling of extended instruction sets into separate files. We were previously defining all the handlers in the common `builder.h` header file.
> [spirv-ll] Add an interface for OpExtInstImport handlers

- modules/compiler/spirv-ll/CMakeLists.txt
- modules/compiler/spirv-ll/include/spirv-ll/builder_debug_info.h
- modules/compiler/spirv-ll/include/spirv-ll/module.h
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/builder_debug_info.cpp
- modules/compiler/spirv-ll/source/context.cpp
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/opencl_debug_info_100.spvasm
- modules/compiler/spirv-ll/test/spvasm/opencl_debug_info_100_clean.spvasm
This adds a skeleton combined builder for these two sets. All of the instructions are ignored, meaning they are not translated to LLVM IR.
Since both instruction sets only produce non-semantic instructions, this is assumed to be safe enough for real-world usage, with a caveat noted in the code that it's probably possible to create a legal SPIR-V binary (from the verifier's point of view, at least) that reads the result of one of these opcodes from another instruction set, at which point we may internally error on not having produced an LLVM value for one a DebugInfo opcode IDs.
This risk is assumed to be minimal enough for real-world SPIR-V modules with debug info that nominally allowing the instruction set is more beneficial than not.
> [spirv-ll] Nominally support the DebugInfo/OpenCL.DebugInfo.100 sets

- source/cl/test/UnitCL/source/ktst_conversions.cpp
- source/cl/test/UnitCL/source/ktst_geometric.cpp
- source/cl/test/UnitCL/source/ktst_precision.cpp
- source/cl/test/UnitCL/source/ktst_vload_vstore.cpp
Re-enable a bunch of tests.
These tests are currently passing, so re-enable them so that at least we notice if they break again in the future.
No change other than re-enabling a bunch of tests.
> Re-enable a bunch of tests.

- modules/compiler/source/base/source/module.cpp
Commit d4a912153488 changed how the offsets into AST bitstream files are handled. This patch changes our loading of the builtinsPCH to include the new `InputFilesOffsetBase` field.
As this only affects LLVM tip/18, we also introduce a multi_llvm toggle.
This was causing LLVM tip to crash when reading the headers on tip.
Upstream LLVM added a new `InputFilesOffsetBase` field for the module file which should be included when offsetting into the module.
As this was crashing our CI systems, a completed build with a debug mode compiler should be sufficient to prove that it fixes things.
N/A
* …
> [compiler] Include file offset when loading builtins PCH

- source/cl/test/UnitCL/source/ktst_precision.cpp
Re-enable a bunch more tests.
These tests are currently passing as well, so re-enable them too.
This enables tests that were disabled for vector widths 2, 3, 4, but currently only fail for a vector width of 3, so re-enable the other ones.
> Re-enable a bunch more tests.

- modules/mux/targets/host/CMakeLists.txt
Downgrade half-precision being unsupported to a warning.
Although half-precision does not currently work on all targets, it almost works, and it works well enough that for debugging issues on the targets where we support it, it is actually convenient to be able to build it on targets where we do not.
Nothing changes for supported builds.
* Run …
> Downgrade half-precision being unsupported to a warning.

- modules/compiler/vecz/source/vecz_pass_builder.cpp
- modules/compiler/vecz/test/lit/llvm/RISCV/broadcast_vector.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/broadcast_vector.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/packetize_mask_varying.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/select_scalar_vector.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/shuffle.ll
- modules/compiler/vecz/test/lit/llvm/emit_memintrinsics.ll
- modules/compiler/vecz/test/lit/llvm/uniform_loop.ll
This change fixes a number of tests that were broken in LLVM tip:
* zext instructions now have an optional nneg flag which indicates whether they are not-negative. Tests have been updated to optionally read (and ignore) this flag. Since vecz doesn't actually set this flag (it's set by InstCombiner) I assume that it is being set correctly.
* LLVM added a new InferAlignmentPass which does alignment inference that was previously done by InstCombine. This is now included in the main vecz pipeline when using LLVM18.
* Due to the above changes in alignment handling, the emit_memintrinsics.ll test no longer checks alignment.
* uniform_loop.ll's checks were made more generic. Tip LLVM versions are able to pull `%load` out of the loop (which seems to be sound).
Should allow builds in a recent-ish …
> [vecz] Update tests for LLVM tip and fix alignment optimization

- modules/cargo/include/cargo/error.h
- modules/compiler/builtins/libimg/include/libimg/validate.h
- modules/compiler/builtins/source/bakery.cpp.in
- modules/compiler/builtins/source/printf.cpp
- modules/compiler/spirv-ll/include/spirv-ll/assert.h
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/vecz/tools/source/veczc.cpp
- modules/loader/source/relocations.cpp
- modules/tracer/source/tracer.cpp
- modules/utils/targets/host/source/relocations.cpp
- source/cl/include/cl/macros.h
- source/cl/test/UnitCL/include/ucl/assert.h
- source/cl/tools/clc/clc.cpp
- source/cl/tools/oclc/oclc.cpp
- source/cl/tools/oclc/oclc.h
The `cert-err33-c` check checks that function return values are checked. This is a useful warning, so we don't want to disable it outright, but it isn't useful in all situations. One primary one is where we're handling an error and we print a message, typically to `stderr` using `fprintf`. There's not much value in checking that `fprintf` succeeded, as we're about to propagate the error anyway.
In these situations, add a `(void)` cast to suppress the warning.
I've gone through all cases I consider "error handling" locally and came out with a clean build. This isn't to say that such cases don't exist (e.g., that I missed or are present in other build configurations) but this is about being good enough, to avoid false positive warnings/errors.
Also in this PR we convert a couple of …
> Suppress cert-err33-c in error handling code

- modules/compiler/builtins/CMakeLists.txt
- modules/compiler/builtins/abacus/source/CMakeLists.txt
Use depfiles for clang -cc1.
When we make changes to header files, we want to ensure their dependees get rebuilt automatically.
This change adds `-dependency-file`, `-MT`, and `-sys-header-deps` to `clang -cc1` invocations, and adds the `DEPFILE` option to use the written file. It also sets the CMake `CMP0116` policy to make the depfiles Ninja-compatible.
* Run …
> Use depfiles for clang -cc1.

- doc/Doxyfile.in
Fix Doxygen.
We did a search and replace in the documentation when we renamed the project, but this search and replace also included variables that came from outside the documentation that need to be kept at their old names.
Restore the CMake variable names that come from outside the documentation directory.
Tested by locally building the documentation.
> Fix Doxygen.

- modules/compiler/utils/source/align_module_structs_pass.cpp
https://github.com/llvm/llvm-project/pull/72867 renamed `recalculateIntrinsicID` to `updateAfterNameChange`, this PR accounts for this change in LLVM tip.
> Use version macro for update after name change

- modules/compiler/spirv-ll/include/spirv-ll/builder.h
- modules/compiler/spirv-ll/include/spirv-ll/module.h
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/module.cpp
- modules/compiler/spirv-ll/test/spvasm/debug_info.spvasm
This commit aims to simplify how we handle the management of different types of debug scope.
Debug info is now attached to instructions when we close a range. We no longer store all of the ranges and process them at the end of the module. This keeps debug information better contained within the builder, and means we have to track less volatile data. The code should be simpler as a result, and hopefully easier to maintain.
We also introduce a new concept to help manage debug info. In addition to the old 'line' range which is built in to SPIR-V, we introduce another: a 'lexical scope'. This will be used for the translation of the various DebugInfo extended instruction sets.
The lexical scopes and line ranges do interact, in the same way that the DebugInfo instruction sets interact with the …
> [spirv-ll] Refactor how debug ranges/scopes are handled

- examples/refsi/hal_refsi/external/refsidrv/source/refsidrv/refsi_device_g.cpp
- examples/refsi/hal_refsi/include/device/program.lds
- examples/refsi/hal_refsi/source/refsi_hal_g1.cpp
- examples/refsi/hal_refsi/source/refsi_hal_m1.cpp
In the refsi simulator, there are two memory regions:
* "Main" memory, starting at 0x10000
* "Local" memory, starting at 0x10000000
When emitting the sections, we move the output cursor to location 0x10000000 before writing the sections for local memory. This has the effect of, in some unknown circumstances, resulting in the generated ELF file including padding in the file itself for 255MiB. Besides wasting memory, this also made the refsi simulator unable to load the binaries due to its 128MiB limit.
This patch updates the linker script to be more explicit about the memory layout, which also has the added advantage of having the linker verify that the binary isn't too large.
It also reverts 73c6af20, which was a workaround for this issue.
This was causing a failure in our internal …
> [refsi] Update Refsi memory specifications

- modules/compiler/cookie/{{cookiecutter.target_name}}/source/module.cpp
- modules/compiler/cookie/{{cookiecutter.target_name}}/source/target.cpp
- modules/compiler/riscv/source/module.cpp
- modules/compiler/source/base/CMakeLists.txt
- modules/compiler/source/base/source/base_module_pass_machinery.cpp
- modules/compiler/source/base/source/module.cpp
- modules/compiler/targets/host/source/target.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/extract_element.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/insert_element.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_builtins.ll
More LLVM 18 fixups.
This fixes a few more build errors against LLVM 18.
* LLVM 18 moves clang::CodeGenOptions::VectorLibrary to llvm::driver::VectorLibrary. Use decltype to handle both.
* LLVM 18 drops CallingConv::WebKit_JS.
* LLVM 18 drops <llvm/Transforms/Vectorize.h> which we include needlessly.
* LLVM 18 requires us to link in libLLVMFrontendDriver, libclangAPINotes, libclangBasic.
* LLVM 18 moves <llvm/Support/Host.h> to <llvm/TargetParser/Host.h>.
* LLVM 18 is able to infer that we could potentially end up with a subvector size of zero, in which case we would end up with a division by zero. A subvector size of zero would be a bug elsewhere in OCK, so add an assert that it is not zero.
Tested against LLVM commit https://github.com/llvm/llvm-project/commit/1c55b227fe7d42b3ad18bf9e485 …
> More LLVM 18 fixups.

- doc/overview/tutorials/creating-a-new-mux-target/adapting-target-pass-pipeline.rst
- doc/overview/tutorials/creating-a-new-mux-target/running-new-target-script.rst
- doc/overview/tutorials/creating-new-hal/hal-operations-step-03-loading-programs.rst
- doc/overview/tutorials/creating-new-hal/patches/tutorial1_step1.patch
- doc/overview/tutorials/creating-new-hal/patches/tutorial1_step2.patch
- doc/overview/tutorials/creating-new-hal/patches/tutorial1_step3.patch
- doc/overview/tutorials/creating-new-hal/patches/tutorial1_step4.patch
- doc/overview/tutorials/creating-new-hal/patches/tutorial1_step5_sub1.patch
- doc/overview/tutorials/creating-new-hal/patches/tutorial1_step5_sub2.patch
- doc/overview/tutorials/creating-new-hal/patches/tutorial1_step5_sub3.patch
- doc/overview/tutorials/creating-new-hal/patches/tutorial1_step5_sub4.patch
- doc/overview/tutorials/creating-new-hal/running-kernels/executing-kernels-without-scheduling.rst
- doc/overview/tutorials/creating-new-hal/running-kernels/simple-kernel-scheduling.rst
- examples/refsi/hal_refsi/source/refsi_hal_m1.cpp
- scripts/create_target.py
- scripts/setup_new_target_tutorial.sh
This PR combines a bunch of fixes to the tutorial and new-target scripts. Each is split up into its own commit, but to summarize:
* An issue was fixed where the tutorial/example code was was internally inconsistent and had fallen behind current compiler code
* An issue was fixed that showed a kernel ABI mismatch in the HAL & new-target tutorials
* A memory leak in `program_find_kernel()` was fixed as per the reference HAL code
* The `alignBuffer` function behaves more intuitively when the buffer is already aligned
* The `create_target.py` script can take relative directories to `--external-dir`
* Patches were brought up to date and should no longer generate `.orig` files when applied
* A few spelling errors were fixed
This should fix all of the issues raised in #150 
It doesn't fix the …
> [tutorial] Fix various issues in the HAL tutorial and new-target scripts

- modules/compiler/spirv-ll/include/spirv-ll/builder.h
- modules/compiler/spirv-ll/include/spirv-ll/builder_debug_info.h
- modules/compiler/spirv-ll/include/spirv-ll/module.h
- modules/compiler/spirv-ll/include/spirv-ll/opcodes.h
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/builder_debug_info.cpp
- modules/compiler/spirv-ll/source/context.cpp
- modules/compiler/spirv-ll/source/module.cpp
- modules/compiler/spirv-ll/source/opcodes.cpp
- modules/compiler/spirv-ll/test/spvasm/CMakeLists.txt
- modules/compiler/spirv-ll/test/spvasm/invalid-spir-v/opencl_debug_info_100_type_member_non_constant.spvasm
- modules/compiler/spirv-ll/test/spvasm/invalid-spir-v/opencl_debug_info_100_type_template_parameter_non_constant.spvasm
- modules/compiler/spirv-ll/test/spvasm/invalid-spir-v/opencl_debug_info_100_type_templates.spvasm
- modules/compiler/spirv-ll/test/spvasm/opencl_debug_info_100.spvasm
- modules/compiler/spirv-ll/test/spvasm/opencl_debug_info_100_arrays.spvasm
- modules/compiler/spirv-ll/test/spvasm/opencl_debug_info_100_clean.spvasm
- modules/compiler/spirv-ll/test/spvasm/opencl_debug_info_100_debug_scopes.spvasm
- modules/compiler/spirv-ll/test/spvasm/opencl_debug_info_100_global_var.spvasm
- modules/compiler/spirv-ll/test/spvasm/opencl_debug_info_100_type_templates.spvasm
This commit extends spirv-ll to consume OpenCL.DebugInfo.100 instructions and translate them to meaningful LLVM debug info.
Although the legacy DebugInfo instruction set is similar, there are differences, and we aren't seeing real-world binaries with this extended instruction set and so lack tests to confidently enable it.
The translation process differs slightly from the translation of other extended instruction sets. There is a small core of 'root' instructions in the debug info hierarchy, and many more 'leaves' which don't meaningfully add debug information on their own. Thus the translator only processes the roots on demand as we visit them in program order. Those roots may then reference other instructions (roots or leaves) which we translate on the fly. We cache the translation of …
> [spirv-ll] Fully support OpenCL.DebugInfo.100 instructions

- CMakeLists.txt
- source/cl/include/cl/config.h.in
- source/cl/source/command_queue.cpp
- source/cl/test/UnitCL/CMakeLists.txt
- source/cl/test/UnitCL/include/Common.h.in
- source/cl/test/UnitCL/source/clCreateCommandQueueWithProperties.cpp
- source/cl/test/UnitCL/source/cl_khr_create_command_queue/clCreateCommandQueueWithPropertiesKHR.cpp
Minimal support for out-of-order queues
Out-of-order queues impose additional restrictions on user code and grant additional freedom to the implementation, including the freedom to continue to execute in order. Therefore, we can trivially support out-of-order queues by removing the code that is specifically there to reject them, and continuing to run them in order.
DPC++ aims to support OpenCL implementations that lack out of order execution support, but it does so by creating temporary queues that appear to not get released (intel/llvm#11156). By claiming out of order execution support, we avoid leaks, and the specification for CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE only permits out-of-order execution, it does not and in general cannot mandate it, so this should be a valid minimal …
> Minimal support for out-of-order queues

- source/cl/source/extension/include/extension/intel_unified_shared_memory.h
- source/cl/source/kernel.cpp
Fix threading issues where usm is used as well as kernel execution and memory free operations.
The velocity bench test svm was showing hangs and crashes when OCK was built in debug.
Usm adds some extra event handling so that any freeing of usm
memory is safe. There is some attempt already to make this thread
safe but this leaves windows where we have added events to the usm
allocations but we have not actually added the kernel execution to
the queue. This can mean the functions such as clMemBlockingFreeINTEL
can end up waiting on an event in a queue too early.
This resolves this by placing the context mutex across both the usm
event creation and the push to the queue, which means that the
usm deletion correctly waits.
> Fixed threading issues with usm and kernel execution

- modules/compiler/targets/riscv/test/lit/passes/verify-reqd-sg-size.ll
- modules/compiler/test/lit/passes/verify-reqd-sg-size-1.ll
- modules/compiler/utils/source/verify_reqd_sub_group_size_pass.cpp
Providing the name of the offending kernel is helpful when there is no diagnostic information to point to a specific line.
It doesn't guarantee that the function means anything to the application developer, as the failing function will (almost certainly) be mangled and may have been wrapped by some of our other compiler passes. Even then, this is still arguably useful information to present to people.
> [compiler] Improve diagnostics for failing sub-groups

- modules/compiler/vecz/source/debugging.cpp
- modules/compiler/vecz/source/include/debugging.h
- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- modules/compiler/vecz/test/lit/llvm/diverging_atomic.ll
This should help debugging (using `--pass-remarks-missed=vecz`) why control-flow conversion failed to apply masks to the CFG.  The previous diagnostics would only print the name of the function that couldn't be converted, but not any more specific information.
This commit adds an extra level of information via a 'note', which is optionally printed on the line after the main diagnostic.
This is not intended to be a full solution to better vecz diagnostics, but a good first step.
> [vecz] Provide more context when CFG conversion fails

- modules/cargo/include/cargo/small_vector.h
- modules/compiler/spirv-ll/source/context.cpp
- source/cl/source/buffer.cpp
- source/cl/source/command_queue.cpp
- source/cl/source/extension/source/intel_unified_shared_memory/intel_unified_shared_memory.cpp
- source/cl/source/extension/source/khr_command_buffer.cpp
- source/cl/source/program.cpp
- source/vk/source/pipeline_cache.cpp
Remove GCC 7 workaround.
This came up in another PR, where this workaround copied and pasted into new code was confusing and it was not clear why we needed it.
This workaround was needed for GCC 7, but we do not build with GCC 7 and in fact error when building with GCC 7 for other reasons anyway. GCC 8 does not need this workaround, tested with gcc-8 (Ubuntu 8.4.0-3ubuntu2) 8.4.0, so remove it.
* Make …
> Remove GCC 7 workaround.

- source/cl/source/extension/include/extension/intel_unified_shared_memory.h
- source/cl/source/extension/source/intel_unified_shared_memory/intel_unified_shared_memory.cpp
- source/cl/source/extension/source/intel_unified_shared_memory/usm-exports.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_allocate.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_mem_info.cpp
This implements shared allocations for USM using the same machinery as host allocations. A shared USM allocation can be associated with at most one device, and is accessable on host and that device.
This should be compliant with the extension spec, but does not yet support cross device access or migrating the allocation to the device. Both `CL_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE_INTEL` and `clEnqueueMigrateMemINTEL` have no effect.
Some tests and examples required shared USM support.
Hacked together shared USM support using host memory support. It's not efficient, but it should be compliant and not require any extra work by the backends.
I had to update a test which required cross-device support to consider shared USM supported, but I don't think that's required as per the spec.
Spec: …
> Basic shared USM support

- modules/mux/targets/host/source/device.cpp
- modules/mux/targets/riscv/source/device_info.cpp
Some SYCL benchmarks (seemingly ones ported to/from CUDA) require a sub-group size of 32.
There shouldn't be any harm in us advertising this, even if the vectorization width is larger than we typically consider:
* If it's required by a program and we don't support it, we'll fail to compile
* If we advertise it but fail to vectorize to that width, we'll fail to compile
* If we advertise it and successfully vectorize, then this is an improvement on what we had before
I've tried this with the `cudaSift` benchmark as part of Velocity Bench, as we do successfully vectorize to this amount. I've noticed some poor code-generation but we can work on improving that later.
> [host][riscv] Advertise/support a sub-group size of 32

- source/cl/source/extension/include/extension/intel_unified_shared_memory.h
- source/cl/source/kernel.cpp
This reverts commit 695309df35a12a6bf23160327b51182e04d040ac.
The fix for the usm threading issue introduces another threading issue, and so need reverting
Tsan build showed possible threading issues from putting a context mutex around a queue mutex as there are other cases where a context mutex is called under a queue mutex, in this case when we delete a program.
revert 695309df35a12a6bf23160327b51182e04d040ac
> Revert "Fixed threading issues with usm and kernel execution"

- source/cl/test/UnitCL/CMakeLists.txt
[NFC] Silence CMake.
When I renamed Common.h to Common.h.in, I left a reference to include/Common.h untouched which resulted in a CMake warning:
CMake Warning (dev) at cmake/AddCA.cmake:543 (add_executable):
Policy CMP0115 is not set: Source file extensions must be explicit.  Run
"cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
File:
oneapi-construction-kit/source/cl/test/UnitCL/include/Common.h.in
Call Stack (most recent call first):
source/cl/cmake/AddCACL.cmake:92 (add_ca_executable)
source/cl/test/UnitCL/CMakeLists.txt:59 (add_ca_cl_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.
Like Device.h, the reference should be explicitly to {CMAKE_CURRENT_BINARY_DIR}/include/Common.h. …
> [NFC] Silence CMake.

- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_allocate.cpp
Fix memory leaks in UnitCL shared alloc tests.
Some USM Shared alloc tests were added which showed up in asan that there were memory leaks from calls to clSharedMemAlloc.
This fixes the leaks by calling clMemBlockingFreeINTEL.
> Fix asan memory leaks

- modules/compiler/test/lit/passes/barriers-live-vars-literal-structs.ll
- modules/compiler/utils/include/compiler/utils/barrier_regions.h
- modules/compiler/utils/source/barrier_regions.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/cmpxchg.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/store_literal_struct.ll
- modules/compiler/vecz/test/lit/llvm/cmpxchg.ll
The work-item loops pass would crash when faced with a live variable whose type was a struct containing scalable vectors.
We aren't legally allowed to store a struct type containing a mixture of scalable and fixed types (`{ <vscale x 1 x i8>, i8 }`) so we decompose such types into their constituent elements and store each individually. Note that scalable elements are stored in the scalable part of the live variables struct, and fixed elements are stored in the fixed part; in that way they are treated as if they were never a struct to begin with.
Note that there may be a future optimization possible here where we store all-scalable structs "whole", but this isn't currently a priority.
Note that this problem doesn't currently surface in the default pipeline in the main branch, because we …
> [compiler] Handle scalable structs as barrier live variables

- source/cl/source/extension/source/intel_unified_shared_memory/usm-exports.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_free.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_mem_fill.cpp
Modifies behaviour of `clEnqueueMemFillINTEL`, `clMemFreeINTEL`, and `clMemBlockingFreeINTEL` so that the parameters can be arbitrary host data.
This mimics the behaviour we already allow for `clEnqueueMemCpyINTEL`.
This is required by some SYCL Velocity Bench benchmarks, such as `cudaSift`.
> [usm] Support filling and freeing arbitrary host pointers

- modules/compiler/source/base/source/check_for_ext_funcs_pass.cpp
- modules/compiler/source/base/source/printf_replacement_pass.cpp
- modules/compiler/source/base/source/program_metadata.cpp
- modules/compiler/tools/muxc/muxc.cpp
- modules/compiler/utils/source/mangling.cpp
- modules/compiler/utils/source/pass_functions.cpp
- modules/compiler/utils/source/rename_builtins_pass.cpp
- modules/compiler/vecz/source/vectorization_context.cpp
- modules/compiler/vecz/source/vectorizer.cpp
[NFC] Change startswith/endswith to starts_with/ends_with.
For consistency with C++20, LLVM renamed startswith to starts_with, and likewise for endswith. startswith and endswith are still available as wrappers that do nothing but call starts_with and ends_with, but as of LLVM 18 have been deprecated.
As the oldest LLVM we support (LLVM 16) already had starts_with and ends_with, we can just use that unconditionally, so this commit is nothing more than a global search and replace.
* Make sure the project builds …
> [NFC] Change startswith/endswith to starts_with/ends_with.

- modules/compiler/spirv-ll/include/spirv-ll/builder.h
- modules/compiler/utils/include/compiler/utils/pipeline_parse_helpers.h
[NFC] Change more startswith/endswith to starts_with/ends_with.
My previous PR to change startswith/endswith to starts_with/ends_with was intended to be limited to C++ sources, as we have a number of occurrences in Python files that should be left alone, but I did so by limiting to *.cpp files, when actually we have a few in *.h files that should be updated too.
points, etc.*
*If there's any …
> [NFC] Change more startswith/endswith to starts_with/ends_with.

- modules/compiler/vecz/source/vectorization_context.cpp
- modules/compiler/vecz/test/lit/llvm/OpaquePointers/control_flow_conversion_ptrs.ll
- modules/compiler/vecz/test/lit/llvm/OpaquePointers/masked_store.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_interleaved_store_as_masked.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/interleaved_load.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/define_interleaved_load_store.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/define_masked_load_store.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/scatter_gather.ll
- modules/compiler/vecz/test/lit/llvm/control_flow_conversion_ptrs.ll
- modules/compiler/vecz/test/lit/llvm/define_gather_load.ll
- modules/compiler/vecz/test/lit/llvm/define_gather_load_as_masked.ll
- modules/compiler/vecz/test/lit/llvm/define_scatter_store.ll
- modules/compiler/vecz/test/lit/llvm/define_scatter_store_as_masked.ll
- modules/compiler/vecz/test/lit/llvm/masked_atomics.ll
- modules/compiler/vecz/test/lit/llvm/masked_cmpxchg.ll
- modules/compiler/vecz/test/lit/llvm/masked_interleaved.ll
- modules/compiler/vecz/test/lit/llvm/masked_interleaved_as_scatter.ll
Though in practice we almost always have these attributes set on the functions that call these, this change should help codegen in the rare case that the builtins aren't inlined.
> [vecz] Add nounwind/norecurse attributes to internal vecz builtins

- modules/compiler/builtins/abacus/include/abacus/internal/log2_extended_precision.h
Fix boundary case in log2_extended_precision_half_safe.
log2_extended_precision_half_safe is a modified version of log2_extended_precision_half_unsafe that avoids denormal intermediate results via scaling. The unsafe version gives one input, 0x39f6, special treatment because the approximation is known to be incorrect, but the safe version did not translate this special treatment correctly: the special casing happens before downscaling, therefore the constant needs to be upscaled.
This fixes a pow test failure on FTZ targets.
One constant is changed. Tested by forcing this particular input to be used by modifying InputGenerator::half_edge_cases.
* …
> Fix boundary case in log2_extended_precision_half_safe.

- modules/compiler/utils/include/compiler/utils/pipeline_parse_helpers.h
> [compiler] Remove 'using namespace llvm' from header file

- .github/workflows/create_publish_artifacts.yml
Create a basic nightly OCK build and test vector-add using oneAPI. 
The ock build is archived if the test passes which can then be used
other builds.
As a further step I am also trying to create a pre-release of OCK [here](https://github.com/codeplaysoftware/oneapi-construction-kit/pull/270)
> Create a basic nightly OCK build and test vector-add using oneAPI. 

- source/cl/test/UnitCL/include/kts/execution.h
- source/cl/test/UnitCL/source/kts/fp16_execution.cpp
- source/cl/test/UnitCL/source/ktst_precision.cpp
Improve UnitCL pow testing.
We single out the value 0x39f6 in our implementation of log2_extended_precision, so in tests that use that function, we should ensure that that value is always tested.
This adds an overridable `GetEdgeCases()` function, defaulting to the `InputGenerator::half_edge_cases` we previously used, but overridden for `HalfMathBuiltinsPow` to additionally add `0x39f6` as an edge case.
Tested by locally reverting commit 90cf2faccb27adb19ce330bbe7c7ec62c53c7018 and verifying that UnitCL reliably picks up the error.
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/C …
> Improve UnitCL pow testing.

- modules/compiler/builtins/abacus/source/abacus_math/powr.cpp
- source/cl/test/UnitCL/source/ktst_precision.cpp
Fix powr and re-enable test.
We already treat 1 as a special case in pow(). If we treat it as a special case in powr() too, that looks to be sufficient to avoid errors caused by internal overflow.
points, etc.* …
> Fix powr and re-enable test.

- modules/compiler/builtins/abacus/source/abacus_math/fma.cpp
Avoid undefined behavior in FMA.
If the result is zero, the result is not denormal, so we do not need to follow the denormal special case logic. The check
rounding_mask & ansAsUint would always be zero, so it would never do anything, but the calculation of rounding_mask might have had undefined behavior due to an out-of-range exponent.
points, etc.*
*If there's any other relevant information …
> Avoid undefined behavior in FMA.

- modules/compiler/utils/source/replace_mux_math_decls_pass.cpp
- source/cl/CMakeLists.txt
- source/cl/cmake/Options.cmake
- source/cl/source/binary/include/cl/binary/binary.h
- source/cl/source/binary/source/binary.cpp
Remove CA_CL_FORCE_PROFILE_OPTION
This had been available as a backdoor for testing embedded but this is untested and not documented and embedded is much lower priority now. If needed we should make a target which is effectively embedded, which is a much better way of testing it.
Remove all references of CA_CL_FORCE_PROFILE_OPTION or CA_CL_FORCE_PROFILE_OPTION_STRING
> Remove CA_CL_FORCE_PROFILE

- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- modules/compiler/vecz/test/lit/llvm/Boscc/boscc_merge.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization13.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization5.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization6.ll
- modules/compiler/vecz/test/lit/llvm/divergent_loop_bug.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization13.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization5.ll
In divergent blocks, we must ensure that masked-out - or inactive -
work-items don't contribute a 'true' value towards the branch condition.
Masked-out values may be poison or undef, such as those coming from a
masked-load operation.
Note that this can happen even with ostensibly 'uniform' values, as our
uniform/divergent analysis isn't capable of discerning an
unconditionally uniform value from one that's uniform but produces
poison/garbage when masked out.
To work around this, we ensure that branch conditions in divergent
blocks are masked with the block's entry mask. This should ensure that
only lanes that are meant to be active at that point contribute their
values.
This is likely not a 100% complete fix, as we don't perform this on
uniform blocks or loops. There are tests with …
> [vecz] Ensure inactive lanes don't contribute to branch conditions

- source/cl/include/cl/command_queue.h
- source/cl/source/command_queue.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_free.cpp
*Provide a brief overview of what your changes do, summarizing their effects
and consequences.*
The UnitCL test USMBlockingFreeTest, MultipleQueueMultipleAlloc had previously been disabled due to sporadic fails. Tsan build showed that there was a dependency issue between the fill and copy commands.
This test did something like the following:
Q_A: Fill -> e[0]   BufA 4096
Q_B: Fill -> e[1]   BufB 4096
Q_C: e[0]->Memcpy   from BufA 2048
Q_C: e[1]->Memcpy   from BufB 2048
Much of the core dependencies for command buffers is done in _cl_command_queue::getCommandBufferPending(). In order to capture event dependencies, semaphores are waited on from pending or dispatched command buffers. The code would check events and then check to see if they were in pending command buffers and if so would add …
> Fix cross queue dependency when command buffer already dispatched.

- doc/modules/compiler/utils.rst
- modules/compiler/builtins/abacus/generate/abacus_config/abacus_config.in
- modules/compiler/builtins/abacus/source/abacus_math/CMakeLists.txt
- modules/compiler/builtins/abacus/source/abacus_math/fma.cpp
- modules/compiler/builtins/abacus/source/abacus_math/inplace_fma.cpp
- modules/compiler/builtins/abacus/source/abacus_math/inplace_fma.ll.in
- modules/compiler/builtins/include/builtins/clbuiltins.h
- modules/compiler/source/base/source/pass_pipelines.cpp
- modules/compiler/utils/include/compiler/utils/builtin_info.h
- modules/compiler/utils/source/replace_mux_math_decls_pass.cpp
Use llvm.fma in abacus_fma
Targets that have FMA instructions see a speedup when we use that instead of our custom `__abacus_fma` implementation. We know this helps ARM and RISC-V.
We add a new `__mux_hasnativefma()` builtin which, for now, only returns `true` on ARM and RISC-V (to be improved later). In `__abacus_fma`, if `__mux_hasnativefma()`, we use the `@llvm.fma` intrinsic, if not, we use our old implementation. This avoids problems on X86, where `@llvm.fma` needs libcalls which we do not expose.
* Make …
> Use llvm.fma in abacus_fma

- modules/compiler/builtins/abacus/include/abacus/internal/horner_polynomial.h
This is unnecessarily precise for float and double types, and causes a lot of code bloat in the builtins library, which slowed down benchmarks.
We hope to improve the handling and performance of `__abacus_fma` in the short term, so we might revisit this when we've done that.
> [compiler] Revert use of FMA in horner polynomial

- modules/compiler/builtins/abacus/include/abacus/internal/horner_polynomial.h
[NFC] Suppress clang-tidy warnings.
We use clang-tidy 9, which does not understand if constexpr. Until we can upgrade, just suppress the warnings it produces.
This commit merely adds two `// NOLINT` comments to instruct clang-tidy to ignore the code.
> [NFC] Suppress clang-tidy warnings.

- modules/compiler/test/lit/passes/subgroup-loop-unroll.ll
- modules/compiler/utils/include/compiler/utils/pass_functions.h
- modules/compiler/utils/source/pass_functions.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
- modules/compiler/vecz/test/lit/llvm/masked_atomics_scalar.ll
- modules/compiler/vecz/test/lit/llvm/masked_cmpxchg_scalar.ll
This simplifies the `createLoop` API so that users can rely on it having
generated a loop CFG structure. It correspondingly removes the
`allowUnroll` option.
Now, even when the loop bounds are constant and wouldn't generate a loop
(i.e., 0 or 1 iterations), `createLoop` will generate a loop. Users can
rely on standard LLVM passes to eliminate/simplify the loop.
> [compiler] Ensure createLoop always creates a loop

- .github/actions/do_build_ock/action.yml
- .github/actions/do_build_ock/do_build_m1/action.yml
- .github/workflows/create_publish_artifacts.yml
Overview
Create a pre-release version of OCK on github stable branch on every new push.
Description of change
Every time there's a new push to the stable branch, this workflow will be triggered and will create
a new OCK release on github. 
It uses GITHUB_TOKEN, which has been added to the repository secrets and also uploaded on 1password.
> Publish pre-release OCK

- modules/compiler/utils/include/compiler/utils/pass_functions.h
Remove unused cargo include from pass_functions.h
Unnecessary and unused dependence on a non-compiler module.
Removed unused header file.
> Remove unused cargo include from pass_functions.h

- doc/requirements.txt
Fix building documentation.
Sphinx 4.5.0 does not specify which versions of sphinxcontrib-* it needs and later versions have been released which no longer support Sphinx 4.
To unblock CI, as a first step, use specific older versions.
> Fix building documentation.

- .github/workflows/run_pr_tests.yml
- CMakeLists.txt
- README.md
- doc/getting-started.rst
- modules/cargo/include/cargo/detail/expected.h
- modules/cargo/include/cargo/detail/optional.h
- modules/compiler/builtins/abacus/source/abacus_integer/mad_sat.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- pull_request_template.md
- source/cl/test/UnitCL/source/Common.cpp
[NFC] Upgrade to clang-format-17.
We can see in the diff that clang-format-17 is better able to figure out when (A)*b and (A)&b are a cast and when they are a binary operator.
* CMakeLists.txt is updated to look for clang-format-17.
* Documentation is updated to refer to clang-format-17.
* CI is updated to install clang-format-17.
* Code is reformatted with clang-format-17.
* Run …
> [NFC] Upgrade to clang-format-17.

- modules/compiler/spirv-ll/source/builder_debug_info.cpp
- modules/compiler/utils/source/mux_builtin_info.cpp
- modules/compiler/vecz/source/analysis/instantiation_analysis.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/source/transform/pre_linearize_pass.cpp
- modules/compiler/vecz/source/transform/scalarizer.cpp
This cleans the project of the `bugprone-unchecked-optional-access` check which is present in newer versions of clang-tidy.
Some of these *are* checked as far as we're concerned, but clang-tidy can't know that that. Others are genuine oversights.
> [compiler] Fix unchecked std::optional accesses

- modules/compiler/source/base/source/image_argument_substitution_pass.cpp
- modules/compiler/source/base/source/module.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/utils/source/lld_linker.cpp
[NFC] Add more const.
This is a continuation of https://github.com/codeplaysoftware/oneapi-construction-kit/pull/304.
The main work on adding const was done on LLVM 18, but there are some variables that should be defined as const on LLVM 16 and LLVM 17 too.
> [NFC] Add more const.

- source/cl/test/UnitCL/include/kts/precision.h
- source/cl/test/UnitCL/source/kts/precision.cpp
- source/cl/test/UnitCL/source/ktst_geometric.cpp
[NFC] Remove unused denorm_support.
This was left over from a previous implementation, but is no longer used.
points, etc.*
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/CODE_OF_CO …
> [NFC] Remove unused denorm_support.

- modules/compiler/source/base/source/module.cpp
- modules/compiler/test/lit/frontend/convergent-attributes.cl
Clang emits these attributes by default when compiling C, C++, and OpenCL C. It does this through a default-on driver option which sets a default-off codegen option. Since we act as the driver, we weren't setting the codegen option on. This should enable more optimization opportunities.
> [compiler] Emit 'noundef' attributes when compiling OpenCL C

- source/cl/test/UnitCL/include/cl_intel_unified_shared_memory.h
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_enqueue.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_event_info.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_free.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_hints.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_kernel.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_kernel_exec_info.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_mem_fill.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_mem_info.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_mem_set.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer_mutable_dispatch/usm_arg_update.cpp
This is a small rework of the USM testing framework to make it easier to add new USM memory types in the future, and also adds shared USM support to many tests.
USM shared memory testing was lacking, this improves it by adding USM testing to most tests that currently do both device and host tests. It also removes duplication in the test suite itself.
This change brings a lot of duplicated code into
`cl_intel_unified_shared_memory_Test` (the base class of many tests). Specifically, it provides properties to check host and shared memory USM support, and helper functions to generate USM pointers.
One of the design changes was adding a way to iterate through all available USM pointer types without having to copy-paste code. This is used to add shared allocations to many places alongside …
> USM testing rework for better USM support

- modules/compiler/vecz/source/analysis/uniform_value_analysis.cpp
- modules/compiler/vecz/source/include/analysis/uniform_value_analysis.h
- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- modules/compiler/vecz/test/lit/llvm/Boscc/boscc_merge3.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization12.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization17.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization18.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization19.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization5.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization6.ll
- modules/compiler/vecz/test/lit/llvm/Boscc/partial_linearization7.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization12.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization17.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization18.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization19.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization5.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization7.ll
This commit extends the Uniform Value Analysis with a fourth kind of uniformity: "true" uniformity. This represents a value that is uniform on both active and inactive lanes. The old class of "uniform" has been renamed to "active" uniformity to clarify this.
The analysis pass has been extended with a method to query whether a value is truly uniform. It processes this recursively on demand and caches the result. This is because the initial analysis run works from varying "roots" and marks all dependent values as varying - uniform values aren't handled at all. Rather than negatively affecting the performance of all Uniform Value Analysis runs, this on-demand method keeps costs the same except for users that need to query uniformity.
The query is still conservative, but less so. This can be …
> [compiler] Improve analysis of 'true uniform' values

- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_kernel.cpp
Remove some debugging code that snuck in.
This causes a segfault when building when USM is disabled (and probably elsewhere).
Removed bad line.
> Remove debug code that snuck in

- CHANGELOG.md
- examples/refsi/refsi_g1_wi/compiler/refsi_g1_wi/CMakeLists.txt
- examples/refsi/refsi_m1/compiler/refsi_m1/CMakeLists.txt
- modules/compiler/cookie/{{cookiecutter.target_name}}/CMakeLists.txt
- modules/compiler/source/base/CMakeLists.txt
- modules/compiler/spirv-ll/CMakeLists.txt
- modules/compiler/test/CMakeLists.txt
- modules/compiler/utils/CMakeLists.txt
- modules/compiler/vecz/CMakeLists.txt
- modules/compiler/vecz/tools/CMakeLists.txt
- modules/mux/cookie/{{cookiecutter.target_name}}/CMakeLists.txt
`compiler-utils` library has been split into `compiler-pipeline` and `compiler-binary-metadata` .
The split allows allow use of compiler pipeline utilities without the binary metadata requirements. Both will be needed for `mux` targets.
> Split compiler-utils into compiler-pipeline and compiler-binary-metadata

- modules/compiler/test/lit/passes/add-kernel-wrapper-dbg.ll
- modules/compiler/test/lit/passes/add-kernel-wrapper-noinline.ll
- modules/compiler/test/lit/passes/add-kernel-wrapper-preserve.ll
- modules/compiler/test/lit/passes/add-kernel-wrapper-sched-args.ll
- modules/compiler/test/lit/passes/add-kernel-wrapper.ll
- modules/compiler/test/lit/passes/add-sched-params-add-kernel-wrapper.ll
- modules/compiler/utils/source/add_kernel_wrapper_pass.cpp
This commit lets LLVM know that the pointer to the packed argument structure may not be null, must not be undef/poison, and is dereferenceable.
It also transfers `noundef` and `nonnull` attributes from the old parameters to the new loads from the argument struct. Those loads can take `!noundef` and `!nonnull` metadata.
This should improve performance in certain cases, as this pass typically runs before the final O3 optimization pipeline and any extra information we can give LLVM should help.
> [compiler] Set attributes on packed args and on loads from them

- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_free.cpp
Free some pointers which were incorrectly not freed.
This was failing a sanitizer due to memory leaks.
Free'd memory at the end of a test case.
> Fix missing "frees" on USM pointers

- modules/compiler/utils/source/barrier_regions.cpp
- modules/compiler/vecz/source/transform/basic_mem2reg_pass.cpp
Updates uses of `findDbgDeclares` to account for upstream LLVM changes (https://github.com/llvm/llvm-project/commit/304119860ac0ded0a126ab1c8cc30367e29ebd01)
> Update findDbgDeclares for LLVM 18

- cmake/AddCA.cmake
- source/cl/cmake/AddCACL.cmake
Disable check targets when CA_ENABLE_TEST=false
Remove target name conflict when used with SYCL Native CPU, also seems more correct
This extends the cmake flag to include check targets.
> Extend CA_ENABLE_TESTS to include check targets

- source/ur/source/context.cpp
We now enable pedantic errors but our testing for pull requests does not cover unified runtime. This fixes a ';' after function body.
Overnight testing showed failure to build when unified runtime was enabled.
> Fix pendantic error unified runtime support

- source/cl/test/UnitCL/include/cl_intel_unified_shared_memory.h
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_enqueue.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_event_info.cpp
- source/cl/test/UnitCL/source/cl_intel_unified_shared_memory/usm_kernel.cpp
Add a new pointer to the available pointers (used by allPointers()) for a "deviceless" shared USM pointer. This is a shared USM pointer without an associated device.
Improves USM testing
Added a new pointer type to the pointers list.
The tests should all still pass.
> Add "deviceless" shared USM pointer

- modules/compiler/vecz/test/lit/llvm/constant_address.ll
- modules/compiler/vecz/test/lit/llvm/constant_address_with_uniform.ll
- modules/compiler/vecz/test/lit/llvm/gep_duplication.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization22-llvm18.ll
- modules/compiler/vecz/test/lit/llvm/scalarize_mixed_gep.ll
Update tests for LLVM 19.
This adjusts some tests based on failures seen when testing with LLVM 19.
* LLVM 19 canonicalizes getelementptr instructions, so tests are updated to allow either old or new output.
* LLVM 19 renames a pass, which cannot be handled in a single test. The test is split in two, one for LLVM 16, 17, 18 which uses the old name, one for LLVM 19 which uses the new name.
* Run …
> Update tests for LLVM 19.

- source/ur/source/kernel.cpp
- source/ur/test/source/urKernelRetain.cpp
urKernelRetain: fix incorrect error result.
urKernelRetain is supposed to return UR_RESULT_ERROR_INVALID_NULL_HANDLE if a null kernel is passed in, but instead it previously returned UR_RESULT_ERROR_INVALID_NULL_POINTER. We had a test for this already, but it never ran so we never noticed.
points, etc.* …
> urKernelRetain: fix incorrect error result.

- modules/compiler/utils/source/manual_type_legalization_pass.cpp
Include FMA in manual type legalization.
It too is promoted incorrectly by current LLVM versions.
Current LLVM promotes half-precision FMA to single-precision, which is not sufficient to get a correct result. Promote it to double-precision instead.
> Include FMA in manual type legalization.

- .github/workflows/run_ock_demo.yml
Replace OCK Daily with OCK Demo Package for the ock-demo release
> Fix the OCK demo package release name on github

- modules/compiler/targets/host/include/host/target.h
- modules/compiler/targets/host/source/kernel.cpp
- modules/compiler/targets/host/source/target.cpp
- modules/compiler/utils/CMakeLists.txt
- modules/compiler/utils/include/compiler/utils/gdb_registration_listener.h
- modules/compiler/utils/source/gdb_registration_listener.cpp
This commit adds a version of LLVM's GDBRegistrationListener that is safe to use in our libraries.
This and the original listener is responsible for registering and deregistering dynamically compiled kernels with GDB's JIT compilation interface. It does this through access to global symbols understood by GDB. This requires that it must be made correctly thread-safe.
LLVM ensures this by having only one static singleton version of its GDB listener, which locks itself when notified of a new object, or notified or a freed one. This does not work for our use-case, as the static singleton may be destroyed before the OpenCL library is destroyed. Thus our modules and kernels may inadvertently use an already freed object.
To solve this, our version of this listener is no longer a singleton, and …
> [compiler] Provide a safe GDB JIT registration listener

- source/cl/test/UnitCL/CMakeLists.txt
These fp16 tests are important enough that we should be running them in more configurations more often - with vectorization, with different compilation flags, etc. Relegating them to only the `check-UnitCL-half` target means we miss out on this coverage.
These will all be skipped if half/fp16 isn't enabled so shouldn't negatively impact testing time in the majority of configs.
> [UnitCL] Test *Half* tests under the 'COMPILER' filter

- modules/compiler/builtins/abacus/source/abacus_math/ldexp.cpp
- source/cl/test/UnitCL/source/ktst_precision.cpp
Fix bug in new ldexp implementation.
* The calculation of n_1_min was not quite right. This seems to have not caused any issues, but there is no reason not to get it right.
* The calculation of n_1 rounded to zero, which causes issues. For a scale of -41, we would split it into factors with scales of -13, -13, -15 which breaks because the last would be subnormal. We should instead split it into factors with scales of -14, -14, -13.
points, etc.*
*If you have added new testing, provide details on what …
> Fix bug in new ldexp implementation.

- modules/compiler/targets/host/CMakeLists.txt
- modules/utils/targets/host/CMakeLists.txt
Using `CMAKE_SOURCE_DIR` doesn't work correctly when OCK is built as a sub-project.
There are some further uses of `CMAKE_SOURCE_DIR` where we *check* whether it equals some other directory, and I've left those for now. This commit deals with uses of `CMAKE_SOURCE_DIR` to find include specific OCK directories.
> [cmake] Switch uses of CMAKE_SOURCE_DIR to PROJECT_SOURCE_DIR

- modules/compiler/builtins/abacus/source/abacus_math/CMakeLists.txt
[NFC] Move .cl sources to abacus_math_sources_device.
We were relying on these being implicitly excluded for host, but this is fragile, and breaks if we are included from within LLVM which tries to set up support for compilation of .cl sources in its libclc.
points, etc.*
understanding and verifying your patch, …
> [NFC] Move .cl sources to abacus_math_sources_device.

- modules/compiler/tools/muxc/CMakeLists.txt
This tool includes code from 'base' and clang headers and so should link against the compiler-base library.
This will transitively add the appropriate clang headers to the include path. In a pre-installed/external LLVM build they'll be included anyway because they live at the same location as the LLVM headers. However, in a (eventually correct) in-tree LLVM build, the clang headers will be in a different location and will only be included by the compiler-base library, and not the compiler-static library.
> [muxc] Link against compiler-base

- modules/compiler/CMakeLists.txt
- modules/compiler/multi_llvm/CMakeLists.txt
- modules/compiler/spirv-ll/CMakeLists.txt
- modules/compiler/tools/muxc/CMakeLists.txt
- modules/compiler/vecz/CMakeLists.txt
- source/vk/CMakeLists.txt
Use include_directories for llvm includes under compiler
llvm suggests using include_directories for llvm projects and it is currently does not feel very clean.
At the moment we effectively add target include directories by having dependencies on multi_llvm which in itself adds the target include directories.
llvm suggests using include_directories for llvm projects and adding it at the compiler level feels a cleaner solution.
> Use include_directories for llvm includes under compiler

- modules/compiler/source/base/CMakeLists.txt
1. When building against an in-tree LLVM, the clang headers are not in the same place as the LLVM headers, as in a pre-installed build.
2. When building against an in-tree LLVM, we don't have to provide the full paths to the (static) clang libraries we link against, because the libnames should already be library targets, which will be correctly resolved to the correct built in-tree libraries.
> [compiler] Fix in-tree detection of clang includes/libs

- CMakeLists.txt
- cmake/AddCA.cmake
- doc/developer-guide.md
- doc/source/cl/test/unitcl.rst
- source/cl/cmake/AddCACL.cmake
- source/cl/test/UnitCL/CMakeLists.txt
- source/vk/test/CMakeLists.txt
This commit changes how we name check targets when OCK is built inside an LLVM tree. LLVM includes external projects before unconditionally trying to create a `check` target. If OCK has already created such a target, CMake errors out.
Thus we name the `check` target to `check-ock` and for consistency name all check sub-targets to `check-ock-*`.
This fixes a configure-time error building OCK inside an LLVM tree with tests enabled, and should better "namespace" OCK's own testing compared with the parent project.
> Conditionally rename check targets in an LLVM tree

- .github/actions/build_vgg_resnet_action/action.yml
- .github/workflows/build_pr_cache.yml
- .github/workflows/create_llvm.yml
- .github/workflows/create_publish_artifacts.yml
- .github/workflows/docs.yml
- .github/workflows/run_ock_demo.yml
- .github/workflows/run_pr_tests.yml
- examples/technical_blogs/ock_demo_blog/envvars
- examples/technical_blogs/ock_demo_blog/getting_started.md
Update the getting started guide for ock_demo package. 
Some minor changes were made in the last  commits, so updating the getting_started_guide.md accordingly.
> Update the getting started guide for ock_demo package

- CMakeLists.txt
A recent refactor accidentally made the global `check` target depend on `check-cross-ComputeAorta` which, because `check-ComputeAorta` depends on `check`, running `check-ComputeAorta` would run `check-cross-ComputeAorta`.
This in theory shouldn't be a problem but the `check-cross-ComputeAorta` target looks to make incorrect assumptions about which test/check targets are available, and unconditionally depends on them even when they may not exist.
This is problematic and so we should look at fixing the 'cross' target, but in the meantime we need to reinstate the correct intended dependency chain on the two check targets.
> Fix check-ComputeAorta depending on check-cross-ComputeAorta

- source/cl/test/UnitCL/source/ktst_precision.cpp
This has been showing several precision failures on RISC-V during MR testing. Until the problem has been resolved, disable the test.
The issue is tracked internally.
> [UnitCL] Temporarily disable the Half_Ldexp test

- .github/workflows/run_pr_tests.yml
- CMakeLists.txt
- cmake/AddCA.cmake
- doc/cmake/AddCA.rst
- doc/developer-guide.md
- doc/modules/mux/targets/host/lit.md
- doc/source/cl/extension.rst
- doc/source/cl/test/unitcl.rst
- doc/tutorials/adding-a-custom-builtins-extension.rst
- modules/compiler/spirv-ll/test/README.md
- source/cl/cmake/Options.cmake
This commit attempts to streamline and make consistent our check target names, so that they are unconditionally named `check-ock-*` in all build configurations.
The generic `check` target still exists, but now it is an alias of the new global `check-ock` target, which depends on all the internal check targets such as `check-ock-UnitCL` etc.
This makes it easier to splice out the `check` target, and have everything remain internally consistent. It also means users and developers can consistently run `check-ock-*` targets without worrying about which build configuration they are in.
Notable exceptions are the now legacy `check-ComputeAorta`-style targets, which now alias (possibly new) `check-ock` versions:
* `check-ComputeAorta` aliases `check-ock`
* `check-tidy-ComputeAorta` aliases …
> Unify check target names

- modules/mux/targets/host/extension/example/CMakeLists.txt
- source/cl/examples/CMakeLists.txt
A previous change made the mistake of thinking that the examples weren't built at all when `CA_ENABLE_TESTS` was off, when in fact the examples are unconditionally built, but when `CA_ENABLE_TESTS` is off, the check targets are not built.
The trick is that `add_ca_cl_check` does nothing when `CA_ENABLE_TESTS` is off, so the targets that the group names depend on are not present.
> Fix building of CL examples when CA_ENABLE_TESTS=OFF

- modules/compiler/vecz/source/include/offset_info.h
- modules/compiler/vecz/source/offset_info.cpp
- modules/compiler/vecz/test/lit/llvm/stride_analysis.ll
There were several cases in the OffsetInfo analysis where the OffsetInfo
was told to copy the stride information from another value (typically
one of the instruction's source operands) but the bitmask was not
updated. This meant that the value analysis - which works backwards from
the leaf instruction - would "stop" at that point, and become incorrect
as it would not take into account the range of values that the source
may have.
This was problematic because the analysis would come to the conclusion
that a value has a safe range of values and a valid stride, when in fact
it was truncated from a larger value before being zero-extended, and
thus divergent.
This was found through a segfault/invalid access in one of ArrayFire's
CannyEdgeDetector kernels.
Oftentimes we want to copy the bitmask …
> [vecz] Fix dropped value analysis in OffsetInfo

- modules/compiler/builtins/abacus/source/abacus_math/ldexp.cpp
- source/cl/test/UnitCL/source/ktst_precision.cpp
Fix another bug in ldexp's earlier bugfix.
While 7a083327 noted that we should split -41 as -14, -14, -13, rather than -13, -13, -15, the way this was implemented was not quite right. It resulted in 2 being split into 2, 2, -2. The sign change here can lead to overflow in an intermediate result. Do this better and re-enable the disabled test.
points, etc.*
*If there's any other relevant …
> Fix another bug in ldexp's earlier bugfix.

- modules/compiler/builtins/abacus/generate/abacus_detail_integer/abacus_detail_integer.in
Fix signed integer overflow in add_sat.
This fixes an error seen in UBSAN builds. If x < (T)0, then min - x cannot overflow, but if x >= (T)0, it can. We were relying on the result of that overflow being ignored by masking it out, but it is undefined behavior to even perform the operation, so we need to avoid that.
Unsigned subtraction is well-defined for any values; we can use that instead.
* Run …
> Fix signed integer overflow in add_sat.

- modules/mux/targets/host/test/lit/OCLC/half.cl
- source/cl/tools/oclc/oclc.cpp
Internally we were storing half data as cl_half, which is correct, but this is not an actual floating-point data type. Therefore when we converted those values to/from floating-point types, things would go wrong (e.g., we'd static cast 2.0 to the integer 2 instead of 0x4000).
The OpenCL headers provide some methods for correct translation between float and half, so we can use those instead.
> [oclc] Fix input and output of 'half' values

- modules/compiler/vecz/source/include/transform/packetization_helpers.h
- modules/compiler/vecz/source/transform/packetization_helpers.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
[NFC] buildAfter: return IRBuilder<>.
In LLVM 19, we will no longer be able to use instruction pointers to keep track of insertion points. This change prepares for that by making a helper function that is only ever used to construct an IRBuilder<> return an IRBuilder<> directly.
points, etc.*
understanding and …
> [NFC] buildAfter: return IRBuilder<>.

- modules/compiler/test/utils.cpp
- modules/compiler/utils/source/metadata.cpp
Adds support for handling the `reqd_work_group_size` metadata node with less than three operands.
This is needed for the SYCL Native CPU integration in DPC++. DPC++ may generate metadata nodes with less than 3 operands.
Defaults to 1 for the unspecified dimensions, similarly to what the `LLVM-SPIRV Translator` [does](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/747ef0f0ec03a25b5fb4edf5f5bf43e794503806/lib/SPIRV/PreprocessMetadata.cpp#L131).
Added a lit test for the `reqd_work_group_size` metadata with one and two operands.
> Support reqd_work_group_size with less than 3 operands

- modules/compiler/vecz/source/ir_cleanup.cpp
- modules/compiler/vecz/test/lit/llvm/packetization_debug_info.ll
- modules/compiler/vecz/test/lit/llvm/undef_debug_info.ll
Keep debug information.
DeleteDebugInfoInstructions has a comment explaining that it intends to remove invalid debug info instructions, but the ones that it is removing seem perfectly valid. Given that Fraser recently removed other generation of invalid debug info instructions, hopefully this means we no longer have invalid debug info that we need to clean up. …
> Keep debug information.

- .github/actions/build_portBLAS_action/action.yml
- .github/actions/build_portDNN_action/action.yml
- .github/actions/build_vgg_resnet_action/action.yml
- .github/workflows/run_ock_demo.yml
Replacing the workflow of creating oneapi demo to use multiple jobs for its components instead of using the same workflow.
> Replacing the ock-demo workflow to use multiple jobs for its components instead of using the same workflow.

- modules/compiler/multi_llvm/include/multi_llvm/basicblock_helper.h
- modules/compiler/source/base/source/target.cpp
- modules/compiler/targets/host/source/target.cpp
- modules/compiler/targets/riscv/test/lit/CLC/add.cl
- modules/compiler/targets/riscv/test/lit/passes/link-builtins.ll
- modules/compiler/utils/include/compiler/utils/barrier_regions.h
- modules/compiler/utils/source/barrier_regions.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
- modules/compiler/vecz/source/control_flow_boscc.cpp
- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- modules/compiler/vecz/source/transform/packetization_helpers.cpp
- modules/compiler/vecz/source/transform/scalarizer.cpp
Update for LLVM 19.
* When using the new debug info format, make sure to actually use the new debug info format by converting the builtins module after loading.
* When checking debug info, make sure to check both the old and the new debug info formats.
* When inserting debug info, make sure to insert in the appropriate format.
* When inserting PHIs, ensure they are inserted before any debug info. We are also inconsistent in whether trying to insert PHIs before or after existing PHIs; this commit tries to preserve the existing insertion points as much as possible.
* In add.cl, do not check that no vsetvli is generated. Even if we do not generate it, LLVM 19 …
> Update for LLVM 19.

- modules/compiler/targets/host/source/target.cpp
Fix aarch64 failure due to flags for non-jit path by making the creation of TargetMachine closer to the JIT path.
The cross aarch64 "host" target was crashing when running the offline test
Execution/Execution.Barrier_02_Barrier_No_Duplicates/OfflineOpenCLC.
This was found to be due to the flags passed to the creation of the TargetMachine being different to what is passed from the JITTargetMachineBuilder. The main ones that seemed to matter was the CodeModel and the `JIT` parameter.
This change uses the defaults for the CodeModel and RelocationModel and also sets the JIT parameter. The need for the JIT parameter should be investigated to understand why the failure happens.
> Fix aarch64 failure due to flags for non-jit path

- scripts/jenkins/cts_summary/opencl_conformance_tests_wimpy_very_quick.csv
Changed to call explicit_2sv as the parameter of test_basic,
We have a csv file used for testing MRs where we run OpenCL-CTS test. Since updating OpenCL-CTS some tests have changed.
> Fix quick cts testing for latest OpenCL-CTS

- .github/workflows/run_ock_demo.yml
One of the previous commits seem to have remove it so readding getting_started_guide and envvars to the ock_demo.tar
> Readding getting_started_guide and envvars to the ock_demo.tar

- modules/mux/targets/host/source/device.cpp
Round up memory_size.
We calculate memory_size as os_memory_bounded_size() / 4, but on 32-bit platforms with more than 4GiB of memory, os_memory_bounded_size() is 0xffffffff, so we end up calculating memory_size as 0x3fffffff. Given that we are calculating memory_size this way specifically for OpenCL CTS which assumes that it sees a multiple of various pattern sizes it uses, make it more suitable for OpenCL CTS by rounding up.
points, etc.*
*If you have added new testing, provide details on what …
> Round up memory_size.

- modules/mux/cookie/hooks/post_gen_project.py
- modules/mux/cookie/{{cookiecutter.target_name}}/CMakeLists.txt
- scripts/create_target.py
- scripts/default_target_cookie.json
Cookie changes required to build offline including atomic64, and library dependencies
An offline target could not build offline for two reasons:
* atomic64 was enabled at the cpp level but not the cmake level and was not configurable either way
* The mux dependencies include compilers and did not include md_api.
Added a extra field for the cookie to allow the capability to atomic64
to be acted on and updated the post_gen_project.py to act on this to
update the .cpp file after copying.
CMake adjusted to act on the atomic64 change and correct the library
dependencies.
> Cookie changes required to build offline including atomic64

- .github/workflows/run_ock_demo.yml
As the spacing and syntax is not checked if the workflow is not run in the PR, this went in without raising any errors.
> Fix syntax in ock_demo workflow

- modules/CMakeLists.txt
When building in DPC++'s tree, `FetchContent` for the `SPIRV-Headers` conflicted with the one in `llvm-spirv`, so we skip it when `llvm-spirv` is between the projects enabled through `LLVM_ENABLE_PROJECTS`.
> Skip FetchContent for SPIRV-Headers if building llvm-spirv

- modules/compiler/targets/host/source/target.cpp
- modules/loader/include/loader/elf.h
- modules/loader/include/loader/relocation_types.h
- modules/loader/include/loader/relocations.h
- modules/loader/source/relocations.cpp
This adds support for RISC-V relocations - enough to permit the running
of UnitCL (in the default configuration). There are obviously many other
relocations for RISC-V but without test coverage those have been left
for future work.
Note that relocation support is still incomplete. There is no support
yet for the PLT or GOT sections, so if the executable is loaded too far
away from external symbols, the relocation process will fail at program
load time, complaining of an unreachable symbol. This situation is
entirely down to the in-process memory of the OpenCL location and the
machine it's running on, so cannot be easily pre-determined.
Locally, at least, all (offline) UnitCL tests pass in isolation but fail
when run together, because the binary is loaded too far away from some
symbols …
> [host] Add initial support for RISC-V relocations

- modules/loader/include/loader/elf.h
The "sh_flags" field is meant to be Elf64_Xword, i.e., 64 bits in size.
Also sprinkle in a few static assertions to ensure the data structures
are the correct size.
> [loader] Fix ELF64_shdr field size

- source/cl/scripts/cts-3.0-online-ignore-linux-arm.csv
- source/cl/scripts/cts-3.0-online-ignore-linux-host.csv
- source/cl/scripts/cts-3.0-online-ignore-linux-riscv.csv
Ignore test_gl test.
This test covers the cl_khr_gl_sharing extension, but is not skipped on implementations that do not support this extension.
At the moment we comment out this test in our internal OpenCL CTS testing, rather than using the ignore file for it, but this causes problems when we move to using OpenCL CTS's own CSV files.
points, etc.*
*If there's any other relevant information …
> Ignore test_gl test.

- modules/compiler/spirv-ll/source/builder_debug_info.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
Fix build with LLVM 19 again.
LLVM 19 makes more debug info changes that we need to account for.
points, etc.*
* …
> Fix build with LLVM 19 again.

- scripts/testing/city_runner/cts.py
city_runner: Do not exit early.
When running a full test executable, it will print results for each individual subtest. We want to get all the results.
points, etc.* …
> city_runner: Do not exit early.

- modules/compiler/utils/source/cl_builtin_info.cpp
- modules/compiler/utils/source/link_builtins_pass.cpp
Another fix for LLVM 19.
When we load modules, we convert them to the new debug info format as needed. However, this does not convert not-yet-materialized functions. Previously, this would work out but as LLVM reduces implicit conversions between old and new debug info format, we now need to convert explicitly.
points, etc.*
*If there's any other relevant information we should know that may …
> Another fix for LLVM 19.

- modules/compiler/spirv-ll/test/spvasm/op_group_f_mul.spvasm
Fix op_group_f_mul invalid test.
Newer spirv-tools point out that the GroupUniformArithmeticKHR capability requires the SPV_KHR_uniform_group_instructions extension, and the OpName is in the wrong place.
points, etc.*
* Read and follow the project …
> Fix op_group_f_mul invalid test.

- clik/test/profile.py
- modules/compiler/builtins/scripts/ll_stripper.py
- scripts/coverage/modules/gcovr.py
- scripts/linux_perf_support/perf_jit/disassembly.py
- scripts/testing/city_runner/cts.py
- scripts/testing/city_runner/profiles/gtest.py
Fix Python 3.12 SyntaxWarning
Python has emitted a DeprecationWarning for unescaped backslashes in non-raw string literals for a while, but only when DeprecationWarnings are requested (when -Wd is used). Python 3.12 promotes this to a SyntaxWarning and emits them by default.
When we want a literal \ in a string, escape it as \\.
Code in eternal/ is intentionally left unmodified.
> Fix Python 3.12 SyntaxWarning

- source/vk/source/instance.cpp
- source/vk/test/UnitVK/source/CreateInstance.cpp
Fix vkEnumerateInstanceExtensionProperties.
GCC 13 rightly complains about an out of bounds pointer: when *pPropertyCount > vk::instance_extensions.size(), merely computing vk::instance_extensions.begin() + *pPropertyCount has undefined behavior and trying to cover that up via std::min afterwards is too late and not guaranteed to do what is intended.
Check correctly.
While looking into this I also found that we did not match the spec in that we did not return VK_INCOMPLETE when the passed in size was too small, and did not set *pPropertyCount when the passed in size was too large. …
> Fix vkEnumerateInstanceExtensionProperties.

- source/cl/test/MultiDevice/source/main.cpp
- source/vk/test/UnitVK/include/UnitVK.h
Add missing includes.
We use std::find without including <algorithm>. This previously worked as libstdc++ implicitly includes this header through other headers, but GCC 14 does this less and flags errors.
points, etc.*
* Read and follow the project …
> Add missing includes.

- modules/compiler/targets/host/source/AddFloatingPointControl.cpp
Fix LLVM assertion about wrong debug info
When an inlineable call is emitted in a function that has debug info, that call must itself have debug info. In AddFloatingPointControl, in configX86FP, we made sure to call a utility function that sets up the debug info, but in configAarch64FP and configArmFP we did not do the same, resulting in errors.
points, etc.*
*If there's any other relevant …
> Fix LLVM assertion about wrong debug info

- modules/compiler/test/lit/passes/work-item-loop-no-successor.ll
- modules/compiler/utils/source/work_item_loops_pass.cpp
Currently code similar to 
```
define internal spir_kernel void @__vecz_v8__ZTSZZN8orderingclEvENKUlRN4sycl3_V17handlerEE_clES3_EUlT_E_(ptr addrspace(3) noundef align 1 %_arg_arr_acc, ptr addrspace(3) noundef align 4 %_arg_local_acc,
ptr addrspace(1) noundef align 1 %_arg_res_acc, ptr noundef align 8 %_arg_res_acc9) local_unnamed_addr #7 !srcloc !10 !kernel_arg_buffer_location !11 !kernel_arg_runtime_aligned !12 !kernel_arg_exclusive
_ptr !12 !sycl_fixed_targets !13 !sycl_kernel_omit_args !14 !codeplay_ca_vecz.derived !21 {
entry:
%mux_call7 = call i64 @__mux_get_num_groups(i32 0) #12
%mux_call9 = call i64 @__mux_get_local_size(i32 0) #12
%mux_call11 = call i64 @__mux_get_local_size(i32 0) #12
%mux_call8 = call i64 @__mux_get_num_groups(i32 0) #12
%mux_call13 = call i64 …
```
> Handle barriers with no successor

- modules/compiler/source/base/CMakeLists.txt
Add missing dependency.
When targets depend on abacus_generate, their corresponding tidy targets need to also depend on abacus_generate.
points, etc.*
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-constructi …
> Add missing dependency.

- cmake/AddCA.cmake
- modules/compiler/builtins/abacus/source/CMakeLists.txt
- modules/compiler/builtins/libimg/CMakeLists.txt
- modules/compiler/source/base/CMakeLists.txt
- source/cl/CMakeLists.txt
Specify dependency on Abacus headers.
The previous fix was insufficient to avoid clang-tidy running before Abacus headers were generated.
This commit adds a DEPENDS keyword to add_ca_tidy, add_ca_library, and add_ca_executable. If specified, the dependencies are added to the main target, the tidy target, and the tidy target's symbolic files. Existing dependencies on abacus_generate are updated to use DEPENDS so that the clang-tidy commands will pick this up. …
> Specify dependency on Abacus headers.

- modules/compiler/test/lit/passes/manual_type_legalization-aarch64.ll
- modules/compiler/utils/source/manual_type_legalization_pass.cpp
[AArch64] Scalarize vector int-to-fp conversions.
LLVM compiles AArch64 vector int-to-fp conversions by first converting the int to a fp type of the same width, and then to the desired fp type. This double rounding can introduce errors.
Scalar conversions do not have this problem. Scalarize the vector operation to work around the problem.
* Run …
> [AArch64] Scalarize vector int-to-fp conversions.

- source/cl/CMakeLists.txt
Install ignore list in cts_summary.
We have our OpenCL CTS runner CSV files spread out over two directories and only install them from one of them.
In order to use cts-3.0-online-ignore-linux-*.csv in CI reliably as well, install these too.
> Install ignore list in cts_summary.

- modules/compiler/vecz/test/lit/llvm/VectorPredication/subgroup_reductions_spv_khr_uniform_group_instructions.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_reductions_spv_khr_uniform_group_instructions.ll
Update for LLVM 19.
LLVM 19 uses trunc x to i1 as the canonical representation, rather than LLVM 18's icmp ne (and x, 1), 0, for truncations to i1.
As the purpose of these tests is not how that truncation is performed, allow anything.
> LLVM 19 update: trunc to i1.

- examples/refsi/hal_refsi/external/refsidrv/external/CMakeLists.txt
[RefSi] Restore CMAKE_C(XX)_EXTENSIONS.
We cannot expect external projects to account for our changes from CMake defaults.
Fixes:
/builds/ComputeAorta/ci-github/oneapi-construction-kit/build/_deps/riscv-isa-sim-src/fdt/fdt_ro.c: In function ‘fdt_stringlist_count’: /builds/ComputeAorta/ci-github/oneapi-construction-kit/build/_deps/riscv-isa-sim-src/fdt/fdt_ro.c:711:12: warning: implicit declaration of function ‘strnlen’; did you mean ‘strlen’? [-Wimplicit-function-declaration]
711 |   length = strnlen(list, end - list) + 1;
|            ^~~~~~~
|            strlen …
> [RefSi] Restore CMAKE_C(XX)_EXTENSIONS.

- source/cl/source/device.cpp
- source/cl/test/UnitCL/source/clCreateUserEvent.cpp
- source/cl/test/UnitCL/source/clGetDeviceInfo.cpp
Report availability of out of order exec mode.
If CA_ENABLE_OUT_OF_ORDER_EXEC_MODE is enabled (as it is by default), we accept CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE in queue properties, but do not report it as a property we support for queues.
This commit rectifies that.
This is not currently tested by OpenCL CTS, but will soon be.
> Report availability of out of order exec mode.

- cmake/ImportLLVM.cmake
Set LLVM_DIR.
When we import LLVM, we do so by including LLVMConfig directly, which works fine. However, we do the same for LLD, we include LLDConfig, but LLDConfig needs LLVM and does find_package(LLVM 19.0.0 [...]). Although it sets a hint path here that would pick up the previously included LLVM, the hint path is ignored in cross builds with CMAKE_FIND_ROOT_PATH_MODE_PACKAGE set to ONLY, which it normally should be set to because host packages cannot be used for the target.
By setting LLVM_DIR, we allow the cross LLVM to be found in the expected location, outside of CMAKE_FIND_ROOT_PATH. …
> Set LLVM_DIR.

- source/cl/source/command_queue.cpp
Do not mark events as running.
We were previously marking events as running before they were running. If we have commands A, B, with implicit dependencies, we would mark both of A, B as running once they were submitted. As OpenCL CTS test_events reveals, this is incorrect, because it allows an application to retrieve the execution status of B, determine that it is running, and then retrieve the execution status of A, and determine that it is running as well, when it is only possible for B to start running once A is completed.
Never marking commands as running is the minimal change to be a poor-quality conforming implementation (commands are never guaranteed to take long enough for the "running" state to be observed).
This is intended to be improved in a future commit so that we do mark …
> Do not mark events as running.

- .github/workflows/run_pr_tests.yml
- clik/external/hal_cpu/include/cpu_hal.h
- clik/external/hal_cpu/include/device/program.lds
- clik/external/hal_cpu/source/CMakeLists.txt
- clik/external/hal_cpu/source/cpu_hal.cpp
- clik/external/hal_cpu/source/hal_main.cpp
Minor changes to cpu hal to enable wrapping for remote hal access
Wrapping of the cpu hal with a server and remote access from a client requires some changes to make it work. 
The creation of the device info being a function that can be called externally through a static function. This allows us to use clc without having to use the client/server relation to get the device info.
Making the linker script (which is empty) defined within the static function rather than baking it. Technically we could bake it but we wanted to simplify the server and build the cpu hal files directly rather than having to build it as a shared library and complicate the dependencies.
> Minor changes to cpu hal to enable wrapping for remote hal access

- modules/compiler/builtins/cmake/FindBuiltinsTools.cmake
[CMake] Do not try to read missing files.
In #430, my changes to improve the processing of LLVMConfig.cmake missed out a continue() that resulted in errors when LLVMConfig.cmake could not be found.
This commit adds the missing line.
> [CMake] Do not try to read missing files.

- scripts/testing/city_runner/cts.py
- scripts/testing/city_runner/profile.py
- scripts/testing/city_runner/profiles/basic.py
- scripts/testing/city_runner/profiles/gtest.py
- scripts/testing/city_runner/profiles/tensorflow.py
- scripts/testing/city_runner/test_info.py
city_runner improvements
These are two city_runner changes for the benefit of OpenCL CTS.
- Allow specifying multiple CSV files. When multiple CSV files are specified, their contents will be merged.
- Fix failure calculation. We were miscounting the number of total tests when we encountered a failure.
> city_runner improvements

- modules/compiler/builtins/CMakeLists.txt
- modules/compiler/builtins/cmake/FindBuiltinsTools.cmake
CMake changes that allow cross compiling OCK when building with LLVM in-tree.
If `CMAKE_CROSSCOMPILING` is set and we are in-tree, it means that OCK is being cross compiled as part of LLVM, and so we can use `LLVM_NATIVE_TOOL_DIR` to find the tools required to compile the builtins. Moreover, since when building in tree we don't use `ImpotLLVM`, the `LLVM_PACKAGE_VERSION` variable was not defined, which lead to a configure error when checking the version string for the builtin tools.
Uses `LLVM_NATIVE_TOOL_DIR` to find builtin tools, sets `LLVM_PACKAGE_VERSION` when cross compiling in-tree.
> Enable cross compilation when building OCK in-tree.

- source/cl/source/extension/source/khr_command_buffer.cpp
- source/cl/test/UnitCL/source/cl_khr_command_buffer/clEnqueueCommandBufferKHR.cpp
We aren't returning the correct errors as specified by `clEnqueueCommandBufferKHR`.
Issues we're found based on testing of CTS PR https://github.com/KhronosGroup/OpenCL-CTS/pull/1931 that verifies these errors
Non-conformant implementation of  `clEnqueueCommandBufferKHR`
1. Update some existing `clEnqueueCommandBufferKHR` return codes to the correct value.
2. Use helper function in `clEnqueueCommandBufferKHR` to verify event wait-list.
3. Add check for `CL_INVALID_COMMAND_QUEUE` to `clEnqueueCommandBufferKHR`.
- Updated UnitCL tests to check against the specification defined value.
- Modified these checks to use gtest `EXPECT` rather than `ASSERT` because if the `ASSERT` fails and returns immediately then we won't release the command-queue created by the test, resulting in a leak.
- Still …
> Return correct clEnqueueCommandBufferKHR errors

- modules/mux/targets/host/CMakeLists.txt
- modules/utils/targets/host/source/relocations.cpp
[X86] Expose __truncdfhf2.
LLVM uses __truncdfhf2 for conversion from fp64 to fp16, because under the code generation options we use, there is no native instruction to perform this conversion directly, and emulating it by converting from fp64 to fp32 and then from fp32 to fp16 introduces rounding errors. We did not make this function available, resulting in errors when enabling both FP64 and FP16 on x86.
This change makes it available.
Although this change makes us pass tests on x86 with FP16 enabled, this change does not yet change its status to supported. In order to support it, we would need a bit more investigation to make sure that __truncdfhf2 is available on all X86 targets we aim to support, or introduce an alternative implementation if not. …
> [X86] Expose __truncdfhf2.

- modules/compiler/vecz/test/lit/llvm/ScalableVectors/intrinsics.ll
- modules/compiler/vecz/test/lit/llvm/intrinsics-scalarize.ll
- modules/compiler/vecz/test/lit/llvm/intrinsics.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_reductions_spv_khr_uniform_group_instructions.ll
[LLVM 19] Adjust tests for llvm.ct* intrinsics.
LLVM 19 adds the range attribute to the return type of llvm.ct* intrinsics. No code changes are needed to deal with this, but it appears in a few tests that did not allow attributes.
This commit updates the tests to allow {{.*}} for attributes of affected functions.
* Run [clang-format-17](https://clang.llvm.org/docs/ClangFormat.html) on all modified …
> [LLVM 19] Adjust tests for llvm.ct* intrinsics.

- scripts/testing/city_runner/test_info.py
[city_runner] Ignore whitespace.
OpenCL CTS opencl_conformance_tests_full.csv contains lines where individual fields start with a space, rather than the whole line, as in:
Vectors, vectors/test_vectors
We want to run "vectors/test_vectors", not " vectors/test_vectors".
Call .strip() once more.
> [city_runner] Ignore whitespace.

- CMakeLists.txt
- modules/compiler/targets/host/CMakeLists.txt
- modules/compiler/targets/host/source/target.cpp
- modules/mux/targets/host/CMakeLists.txt
- modules/utils/targets/host/CMakeLists.txt
[RISC-V] Link FP64 and FP16 options to d and Zfh.
Previously, our list of enabled extensions was hardcoded and when a user would set CA_HOST_ENABLE_FP16 on RISC-V, it would fail because it would use softfloat and attempt to use compiler-rt/libgcc functions that we do not provide. But presumably, when CA_HOST_ENABLE_FP16 is enabled, the user wants to use Zfh half-precision hardware instructions.
Enable the extension instead.
Do the same for FP64, where the extension was previously always enabled, but now gets linked to CA_HOST_ENABLE_FP64. …
> [RISC-V] Link FP64 and FP16 options to d and Zfh.

- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_subgroup_scans.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_subgroup_scans_vp.ll
`llvm.vector.splice` is no longer experimental in LLVM 19, we need to update our lit tests.
Lit tests that check for `llvm.experimental.vector.splice` are failing.
Update lit tests to optionally match `.experimental`.
> Update check for llvm.vector.splice

- compiler_passes/CMakeLists.txt
- compiler_passes/README.md
Add a top level directory which can be used to just build compiler passes (currently pipeline related)>
Adding a top level directory which includes just what is necessary allows
us to create a more compiler pass oriented cmake entry point, which can
be included directly from other repos like sycl native cpu.
>  Add top level directory which can be used to just build compiler passes

- modules/compiler/targets/host/source/module.cpp
[host] Remove invalid caching of object code.
As seen in clBuildProgramTwiceTest.RedefineMacro, we may reuse a HostModule to create a binary from a different LLVM module, or with different LLVM build options. We do not have sufficient information to determine whether we can re-use a prior result, and can reasonably assume that if createBinary is called a second time, it will be called a second time specifically because the caller does not want the prior result.
Remove the loading of the prior value of `object_code`.
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/CODE_OF_CONDUCT.m …
> [host] Remove invalid caching of object code.

- .github/workflows/create_llvm.yml
As a first step towards the switch to 17/18 LLVM versions, the builds we do of llvm will switch to 17/18. This does not affect any running CI which only runs on 17.
Only supporting two version is our policy. It is time to start the switch to 17/18
Change to build 17/18. Additionally changed running of the workflow to an overnight, rather than every merge.
> Switch llvm builds in CI to 17/18

- .github/workflows/build_pr_cache.yml
- .github/workflows/run_pr_tests.yml
- CHANGELOG.md
- cmake/ImportLLVM.cmake
- doc/overview/compiler/supported-llvm-versions.rst
Switch min/max versions for OCK to be 17/18
Require to support only two LLVM versions, and 18 is stable
Updated cmake checks and documentation
updated ci usage.
> Switch to llvm versions 17/18 as supported versions

- modules/compiler/spirv-ll/source/module.cpp
- modules/compiler/tools/muxc/muxc.cpp
- modules/compiler/vecz/tools/source/veczc.cpp
Both `muxc` and `veczc` were not using the LLVM passes to out assembly/bitcode, this PR addressed that. 
This PR also makes sure that a module is created with the old debug info format in `spirv-ll`.
Not using the upstream passes means that we were missing out on any kind of logic that is added upstream when outputting IR, e.g. LLVM 19 is changing the debug info format, and `PrintModulePass` handles printing IR in a way that doesn't break `CHECK` directives for debug intrinsics.
Uses `PrintModulePass` and `BitcodeWriterPass` in `muxc` and `veczc`, sets old type of debug info format in `spirv-ll`. …
> LLVM 19 fixes

- CHANGELOG.md
- modules/compiler/compiler_pipeline/include/compiler/utils/pass_functions.h
- modules/compiler/compiler_pipeline/source/pass_functions.cpp
- modules/compiler/compiler_pipeline/source/replace_local_module_scope_variables_pass.cpp
- modules/compiler/test/lit/passes/replace-local-module-scope-mem_builtins.ll
Rewrite replace_local_module_scope_variables to only add parameters where needed.
replace_local_module_scope_variables was incorrectly trying to clone and delete the original of memcpy which was referenced in a llvm.compiler.used line to ensure it continued to exist.
This fixes this by looking at any globals and working back through the user chain until we find an Instruction and only cloning functions that actually require it, as well as all kernels. It also moves and modifies the `addParamToAllFunctions` to the ReplaceLocalModuleScopeVariablesPass as it is only used in there and we can make more appropriate changes.
This change puts it more in line with other similar add parameter pass_functions such as the scheduling parameters and is more efficient.
> Fix replace_local_module_scope_variables mempcy bug

- modules/compiler/targets/host/CMakeLists.txt
- modules/mux/targets/host/CMakeLists.txt
[host] Specify dependency on Mux/Abacus headers
These headers are used directly by host, so should be referenced so that we do not implicitly rely on some dependency having caused them to be generated.
points, etc.*
* Read and follow the project [Code …
> [host] Specify dependency on Mux/Abacus headers

- modules/compiler/targets/host/CMakeLists.txt
- modules/compiler/targets/host/source/kernel.cpp
- modules/mux/targets/host/CMakeLists.txt
- modules/mux/targets/host/source/command_buffer.cpp
Reduce memory consumption.
On 32-bit platforms, OpenCL CTS's `test_conversions` test would fail after running out of memory.
* When destroying a HostKernel, clean up the string pool. The string pool contains the names of every symbol used by the kernel now freed. We do not want these to persist if there is nothing else still using them.
* When resetting a command buffer, do not just clear the commands, shrink the commands too. Otherwise, if enough commands were present that dynamic allocations were needed, this memory would not be freed until the command buffer got destroyed. But because we re-use command buffers, this would keep the allocations until long after we no longer need them.
* When resetting a command buffer, do not just clear and shrink the commands, also clear and shrink the …
> Reduce memory consumption.

- modules/mux/targets/host/include/host/command_buffer.h
- modules/mux/targets/host/source/command_buffer.cpp
- modules/mux/targets/host/source/queue.cpp
Fix memory leak.
In bf1b1eab5b, I cleared host->ndranges, but the result of that the loop in hostDestroyCommandBuffer to free the arguments no longer does anything useful: there is no longer any reference to the arguments.
Change packed_args to a mux::dynamic_array so that this is automatically taken care of for us.
* Run [clang-format-17](https://clang.llvm.org/docs/ClangFormat.html) on all …
> Fix memory leak.

- examples/hal_cpu_remote_server/CMakeLists.txt
- examples/hal_cpu_remote_server/README.md
- examples/hal_cpu_remote_server/hal_cpu_executable.cpp
- examples/hals/hal_cpu_client/CMakeLists.txt
- examples/hals/hal_cpu_client/source/CMakeLists.txt
- examples/hals/hal_cpu_client/source/hal_main.cpp
- hal/CMakeLists.txt
- hal/hal_remote/CMakeLists.txt
- hal/hal_remote/include/hal_remote/hal_binary_decoder.h
- hal/hal_remote/include/hal_remote/hal_binary_encoder.h
- hal/hal_remote/include/hal_remote/hal_client.h
- hal/hal_remote/include/hal_remote/hal_device_client.h
- hal/hal_remote/include/hal_remote/hal_server.h
- hal/hal_remote/include/hal_remote/hal_socket_client.h
- hal/hal_remote/include/hal_remote/hal_socket_transmitter.h
- hal/hal_remote/include/hal_remote/hal_transmitter.h
- hal/hal_remote/source/hal_device_client.cpp
- hal/hal_remote/source/hal_server.cpp
- hal/hal_remote/source/hal_socket_transmitter.cpp
- hal/source/hal_library.cpp
- scripts/new_target_templates/cpu_client_riscv.json
This adds support for generic client and server hal support to allow
sending commands as binary requests over a `hal_transmitter`.
Required to support customer needs of talking to a remote cpu.
Added encoders and decoders for converting hal commands to binary format
Add hal_server base class which uses the encoders and decoders and a
hal_transmitter to receive hal commands remotely and act on the given
hal device.
Add a hal_client and hal_device_client base class which can be used with
a transmitter to send to a remote server binary commands.
Added a hal socket cpu client.
Added hal cpu socket based server program.
This currently only supports single device hals
> add support for a hal remote library

- hal/CMakeLists.txt
- hal/hal_remote/CMakeLists.txt
- hal/hal_remote/include/hal_remote/hal_socket_transmitter.h
- hal/hal_remote/include/hal_remote/hal_transmitter.h
- hal/hal_remote/source/hal_socket_transmitter.cpp
Add hal transmitter and socket support for remote hal
part of the support needed for communications for remote hal support
Add base class hal_transmitter which can be used for simple send/ receive operations of data. This can be used by client and servers for different models of communication.
Also added a socket version which will be the default use case.
> Add hal transmitter and socket support for remote hal

- modules/compiler/vecz/CMakeLists.txt
Explictly link `vecz` to the `AggressiveInstCombine` LLVM component.
`vecz` was not explicitly linked to the LLVM component, which may cause errors if the dependency is not satisfied.
> Link vecz to aggressiveinstcombine

- hal/CMakeLists.txt
Disable remote HAL on non-Linux.
Remote HAL does not build with MSVC and is not expected to work on Windows in general. This may be revisited in the future, but for now, that is how it is.
For now, just disable the build except on Linux.
> Disable remote HAL on non-Linux.

- examples/hal_cpu_remote_server/README.md
- examples/hal_cpu_remote_server/hal_cpu_executable.cpp
- hal/CMakeLists.txt
- hal/hal_remote/CMakeLists.txt
- hal/hal_remote/include/hal_remote/hal_binary_decoder.h
- hal/hal_remote/source/hal_device_client.cpp
- hal/hal_remote/source/hal_server.cpp
- hal/hal_remote/source/hal_socket_transmitter.cpp
This fixes the build for windows so that it does not discard building hal_remote library.
There is also an update for the README to resolve the incorrect description on the ssh forwarding.
Run through showed some minor issues, we also want to have windows capable of building most of the code.
> Fix hal_remote to build for windows, fix other minor issues

- modules/compiler/targets/host/source/info.cpp
[host] Allow setting supports_deferred_compilation
It helps in debugging to be able to override supports_deferred_compilation.
points, etc.*
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blo …
> [host] Allow setting supports_deferred_compilation

- examples/hal_cpu_remote_server/CMakeLists.txt
- examples/hal_cpu_remote_server/README.md
- hal/hal_remote/source/hal_socket_transmitter.cpp
- scripts/create_target.py
Minor fixes required when testing remote HAL in CI
CI showed up some more minor issues
* Fixed hal cpu server README CMAKE_CROSS_COMPILING
* Fixed CMAKE_CXX_STANDARD to 17 for hal cpu server build
* Fixed some brackets in the debug output for socket transmitter 
* Flushed print for no cookiecutter installed on create_target.py so error shows up in CI
> Fix remaining issues shown up in CI for remote hal

- modules/compiler/riscv/source/riscv_pass_machinery.cpp
- modules/compiler/source/base/source/module.cpp
- modules/compiler/targets/host/source/HostPassMachinery.cpp
- modules/compiler/targets/riscv/test/lit/passes/late-passes-pipeline.ll
Run AlignModuleStructsPass earlier.
The AlignModuleStructsPass patches up structs according to OpenCL alignment requirements so that they behave the same way on all implementations. We were already calling this, but we were calling it after running a number of upstream LLVM passes, so we were feeding them incorrect input and hoping we could correct that afterwards. A change has gone in on LLVM 19 that performs a valid optimization that we cannot correct afterwards.
Make sure we run AlignModuleStructsPass as soon as we know what target we are compiling for. …
> Run AlignModuleStructsPass earlier.

- README.md
- examples/applications/simple-vector-add.cpp
- examples/applications/vector_addition-load-store.cpp
- examples/applications/vector_addition-masked-store.cpp
- examples/applications/vector_addition-predicated.cpp
- examples/applications/vector_addition-tiled-load-store.cpp
- examples/hal_cpu_remote_server/README.md
Added some SYCL testing to the README for the remote server. The SYCL tests inside OCK were also out of date and have been updated to work with the latest SYCL.
We wanted an example of running SYCL tests with remote HAL. The tests as is are out of date.
Fixed tests to use latest SYCL. Added SYCL instructions to hal server  README.
> Added some SYCL testing to the Remote HAL README, fixed tests

- modules/compiler/compiler_pipeline/source/cl_builtin_info.cpp
- modules/compiler/compiler_pipeline/source/link_builtins_pass.cpp
- modules/compiler/source/base/source/check_for_ext_funcs_pass.cpp
- modules/compiler/spirv-ll/source/builder.cpp
Avoid StringRef.equals()
LLVM 19 has deprecated StringRef::equals in favor of plain ==.
This has been supported by all versions of LLVM ever since StringRef was first added, so we can just change them as suggested.
> Avoid StringRef.equals()

- CMakeLists.txt
Pass --no-show-signature.
git log may either show GPG signatures or not, depending on user settings, when neither --show-signature nor --no-show-signature is passed.
We are relying on not getting GPG signatures here, so explicitly pass --no-show-signature.
> Pass --no-show-signature.

- clik/external/hal_cpu/include/cpu_hal.h
- clik/external/hal_cpu/source/cpu_hal.cpp
- clik/external/hal_cpu/source/hal_main.cpp
- examples/hal_cpu_remote_server/README.md
- examples/hals/hal_cpu_client/source/hal_main.cpp
- hal/hal_remote/include/hal_remote/hal_client.h
- hal/include/hal_types.h
- modules/compiler/riscv/source/module.cpp
- modules/mux/targets/riscv/external/CMakeLists.txt
- modules/mux/targets/riscv/source/kernel.cpp
Return a hal_device_info_riscv_t from cpu hal/remote hal
Allow in-tree risc-v to support cpu hal/remote HAL
Change cpu hal to return a reference to the device info.
Fix assert when vlen = 0 in mux kernels.
Add link_shared to hal arguments.
Add the examples/hals directory to the list searched
> Return a hal_device_info_riscv_t from cpu hal/remote hal

- modules/compiler/builtins/source/printf.cpp
- source/cl/test/UnitCL/kernels/printf.10_print_nan.cl
- source/cl/test/UnitCL/kernels/printf.10_print_nan.spvasm32
- source/cl/test/UnitCL/kernels/printf.10_print_nan.spvasm64
- source/cl/test/UnitCL/source/ktst_printf.cpp
Fix printf of nan.
std::string::replace takes pos and count parameters, not start and end. This was not previously covered by testing because either the format specifier appeared at the start (meaning count and end are the same), or the format specifier appeared at the end (meaning there are no characters after the format specifier to cut off).
Add a test that puts the format specifier in the middle. …
> Fix printf of nan.

- modules/compiler/builtins/source/printf.cpp
Fix printf of %%.
We were printing any non-argument-consuming parts of printf format strings literally, but that is not right: printf("%%") is supposed to print "%", not "%%".
We have already checked the format string, we already know that the format string consumes no arguments, so just pass it to printf to handle any embedded %%.
* Run [clang-format-17](https://clang.llvm.org/docs/ClangFormat.html …
> Fix printf of %%.

- modules/compiler/compiler_pipeline/source/cl_builtin_info.cpp
- modules/compiler/compiler_pipeline/source/link_builtins_pass.cpp
- modules/compiler/source/base/source/target.cpp
- modules/compiler/targets/host/source/target.cpp
[LLVM 19] Drop debug info format conversions
We were converting between LLVM's old and new debug info format to work around the incomplete new debug info format implementation in LLVM 19. Now that it is (mostly) done, we no longer need that.
points, etc.*
understanding and verifying your patch, please include it …
> [LLVM 19] Drop debug info format conversions

- modules/compiler/builtins/CMakeLists.txt
- modules/compiler/targets/riscv/test/lit/passes/link-builtins-memcpy.ll
- modules/compiler/targets/riscv/test/lit/passes/link-builtins-memmove.ll
- modules/compiler/targets/riscv/test/lit/passes/link-builtins-memset.ll
Fix risc-v memmove creating memcpy instrinsic
SYCL CTS test vector_load_store with host risc-v showed that memmove intrinsics could result in a linked builtin which then included memcpy instrinsics which could result in a linker error.
This resolves this by passing -fno-builtin in the build for the builtins. This only removes the additional llvm.memcpy and all other instrinsics remain.
> Fix risc-v memmove creating memcpy instrinsic

- modules/compiler/builtins/include/builtins/builtins-3.0.h
- modules/compiler/builtins/scripts/generate_header_30.sh
- modules/compiler/compiler_pipeline/source/replace_c11_atomic_funcs_pass.cpp
- source/cl/test/UnitCL/kernels/c11atomics.09_store_local_int.cl
- source/cl/test/UnitCL/kernels/c11atomics.09_store_local_long.cl
- source/cl/test/UnitCL/kernels/c11atomics.09_store_local_uint.cl
- source/cl/test/UnitCL/kernels/c11atomics.09_store_local_ulong.cl
- source/cl/test/UnitCL/kernels/c11atomics.10_store_global_int.cl
- source/cl/test/UnitCL/kernels/c11atomics.10_store_global_long.cl
- source/cl/test/UnitCL/kernels/c11atomics.10_store_global_uint.cl
- source/cl/test/UnitCL/kernels/c11atomics.10_store_global_ulong.cl
Add missing atomic functions.
We only implemented the *_explicit versions, and only the versions that take both memory_order and memory_scope parameters. The OpenCL specification tells us we also need overloads that only take memory_order, and non-explicit versions that do not take either.
points, etc.*
Tested by running OpenCL CTS's updated `test_generic_address_space` test, which …
> Add missing atomic functions.

- modules/compiler/source/base/source/module.cpp
- source/cl/test/UnitCL/source/clBuildProgram.cpp
Add parsing for -cl-uniform-work-group-size and -cl-no-subgroup-ifp
These flags were not recognised so if set in the build program we would get an error. See 
https://github.com/codeplaysoftware/oneapi-construction-kit/issues/476
This adds support for parsing them, but does nothing with the result as they are optimizations only.
> Add parsing of -cl-uniform-work-group-size and -cl-no-subgroup-ifp

- source/cl/test/UnitCL/source/cl_khr_command_buffer/clEnqueueCommandBufferKHR.cpp
Replaced the global value increment with an atomic_inc in UnitCL test IncrementKernelTwiceDifferentQueues
This test started two queues at the same time and updated the same value. This could on occasion cause a race condition, exhibited on risc-v host.
> Fix test IncrementKernelTwiceDifferentQueues

- modules/compiler/targets/host/source/module.cpp
[host] Add debug option to dump assembly.
With CA_HOST_DUMP_ASM=1, when a kernel binary is created, also dump it in text form to stderr for easier debugging.
> [host] Add debug option to dump assembly.

- modules/compiler/targets/host/source/target.cpp
Update for LLVM 19.
LLVM 19 changes llvm::sys::getHostCPUFeatures() to return by value.
points, etc.*
* Make …
> Update for LLVM 19: account for getHostCPUFeatures API change.

- modules/compiler/builtins/abacus/source/CMakeLists.txt
[MSVC] Fix debug builds.
We build Abacus in debug builds with /RTCc to flag out of range conversions, but this is a leftover from when Abacus was its own project. In oneAPI Construction Kit, it does not make sense and does not work, as the infrastructure to report such conversions is not available. It was also completely untested as it was only enabled in Debug builds, which we never ran.
Remove /RTCc. …
> [MSVC] Fix debug builds.

- source/cl/CMakeLists.txt
- source/cl/include/cl/config.h.in
- source/cl/source/platform.cpp
- source/cl/test/UnitCL/CMakeLists.txt
Improve for Visual Studio builds.
* In the reported platform version, include build configuration only if available at CMake time. When building using a multi-config generator, it will not yet be known and the build type will be left out.
* In the reported platform version, always include Git commit if available, even for release builds. Non-Git builds will still be able to build as well: no Git commit will be included in that case.
* Explicitly pass kernel and include directory to UnitCL. We were relying on the UnitCL default of ../share which does not work in multi-config builds, as binaries are not one but two levels down. The UnitCL default, which is …
> Improve for Visual Studio builds.

- cmake/AddCA.cmake
- hal/source/hal_library.cpp
- modules/cargo/source/thread.cpp
- modules/compiler/loader/source/loader.cpp
Fix <windows.h> header name.
The header name is <windows.h>. In a few places, we referred to it as <Windows.h> which breaks on case sensitive file systems. This is not common on Windows, but important for cross compilation.
points, etc.*
* Read and …
> Fix <windows.h> header name.

- doc/developer-guide.md
- modules/compiler/cookie/{{cookiecutter.target_name}}/source/{{cookiecutter.target_name}}_pass_machinery.cpp
- modules/compiler/riscv/source/module.cpp
- modules/compiler/riscv/source/riscv_pass_machinery.cpp
- modules/compiler/source/base/source/module.cpp
- modules/compiler/targets/host/source/info.cpp
- modules/compiler/targets/host/source/module.cpp
- modules/compiler/utils/source/lld_linker.cpp
Unify uses of environment variables under NDEBUG or CA_ENABLE_DEBUG_SUPPORT
There is some inconsistency in where environement variables are enabled either bug using !defined(NDEBUG) or defined(CA_ENABLE_DEBUG_SUPPORT). This change means that either will affect these environment variables.
Support both  !defined(NDEBUG) or defined(CA_ENABLE_DEBUG_SUPPORT) in use cases
This also moves CA_HOST_DEFERRED_COMPILATION under similar controls.
> Unify uses of debug environment variables

- doc/developer-guide.md
- modules/compiler/targets/host/CMakeLists.txt
- modules/compiler/targets/host/source/target.cpp
Allow features to be added using env variable or cmake using standard  mechanism of "+v,+zfence" etc
Allow risc-v host to support "+v" etc more easily.
Added cmake (CA_HOST_TARGET_${HOST_ARCH_UPPER}_FEATURES) and env variable (CA_HOST_TARGET_FEATURES) support  to host target.
> Add support for host target setting of support of features

- modules/compiler/targets/host/source/target.cpp
Adding some extra curly brackets due to clang-tidy
Fix clang-tidy fail
> Fix curly brackets clang-tidy error

- modules/loader/include/loader/relocation_types.h
- modules/loader/source/relocations.cpp
Added RISCV_BRANCH and RISCV_RVC_JUMP relocations. 
This is useful for debugging where we assemble the output assembly for testing purposes, but could in theory happen regardless.
Added RISCV_BRANCH and RISCV_RVC_JUMP relocations, as well as skipping RISCV_ALIGN relocations.
> Added some relative relocations for RISC-V

- doc/developer-guide.md
Added some docs for CA_HOST_DUMP_ASM and CA_HOST_DEFERRED_COMPILATION
We've improved how these variables are enabled, so adding to documentation.
> Added some docs for CA_HOST_DUMP_ASM and CA_HOST_DEFERRED_COMPILATION

- modules/cargo/CMakeLists.txt
- modules/compiler/targets/host/source/target.cpp
[cargo, host] Handle macOS.
* pthread_setname_np only takes a single argument and can only set the thread name of the current thread. Where cargo optionally uses pthread_setname_np, it needs the two-argument version, so change the CMake check to reject the macOS version.
* For macOS/arm64, we need the same workaround as for macOS/x86, we need to generate ELF since Mach-O has restrictions on names that means our IR cannot be compiled for it. This makes things easier for us anyway as we already have an ELF loader.
* Read …
> [cargo, host] Handle macOS.

- modules/loader/source/relocations.cpp
[host][AArch64] Fix R_AARCH64_ADR_PREL_PG_HI21 handling.
R_AARCH64_ADR_PREL_PG_HI21 writes the page difference to the immediate operand of an ADRP instruction. We were this in bits 29-30 (low) and 3-21 (high), but the immediate operand is supposed to be encoded in bits 29-30 (low) and 5-23 (high).
Write to bits 5-23 instead.
* Run [clang-format-17](https://clang.llvm.org/docs/ClangFormat.html) on …
> [host][AArch64] Fix R_AARCH64_ADR_PREL_PG_HI21 handling.

- modules/kts/source/stdout_capture.cpp
Fix UnitCL file descriptor leak.
For testing printf, we were saving the original stdout in a new fd, redirecting stdout to a temporary file, running the test, restoring stdout from that fd, and reading from that file. What is missing here is closing that new fd after we are done with it, so we would open more and more and more file descriptors. On macOS, the file descriptor limit is lower than it is on Linux and we would run out of file descriptors.
Close file descriptor after we are done with it.
* Make sure …
> Fix UnitCL file descriptor leak.

- modules/compiler/source/base/source/printf_replacement_pass.cpp
- source/cl/test/UnitCL/kernels/kernel_source_list.cmake
- source/cl/test/UnitCL/kernels/printf.24_empty_string_param.cl
- source/cl/test/UnitCL/kernels/printf.24_empty_string_param.spvasm32
- source/cl/test/UnitCL/kernels/printf.24_empty_string_param.spvasm64
- source/cl/test/UnitCL/source/ktst_printf.cpp
Added check for zero initializer and added a UnitCL test.
OpenCL CTS showed a failure in test_printf. This is due to not recognizing a zero initializer as a string.
> Fix for printf("%s\n", "") and test.

- modules/compiler/targets/host/source/info.cpp
- source/cl/test/UnitCL/source/ktst_precision.cpp
Fix x86 compiler, disable test for macOS.
* We were setting up the x86 compiler for the host OS, rather than for Linux, but we only support cross-compilation for Linux. For AArch64 and RISC-V, we were already forcing Linux, do the same for x86 so that we do not attempt to cross-compile from macOS/arm64 to macOS/x86.
* Disable Precision_01_Pow_Func on macOS. This test only passes when a sufficiently large long double type is available. On macOS/arm64, long double is the same as double.
* Read and follow the project [Code …
> Fix x86 compiler, disable test for macOS.

- modules/compiler/cookie/{{cookiecutter.target_name}}/source/info.cpp
- modules/compiler/include/compiler/info.h
- modules/compiler/riscv/source/info.cpp
- modules/compiler/targets/host/include/host/info.h
- modules/compiler/targets/host/source/info.cpp
- modules/compiler/targets/host/source/target.cpp
- modules/compiler/test/common.h
- source/cl/source/program.cpp
Auto-disable deferred compilation.
CA_HOST_DUMP_ASM=1 and deferred compilation are incompatible. Our current behavior is that CA_HOST_DUMP_ASM is effectively silently ignored, making for a poor user experience.
With this change, when CA_HOST_DUMP_ASM=1 is set and deferred compilation would normally be implicitly enabled, deferred compilation will be disabled and a warning is printed for it.
If an explicit CA_HOST_DEFERRED_COMPILATION=1 is set, deferred compilation can be forced. This still works and results in no assembly being printed.
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/m …
> Auto-disable deferred compilation.

- modules/loader/include/loader/relocation_types.h
- modules/loader/source/relocations.cpp
Added support for relocations R_RISCV_JAL and R_RISCV_RVC_JUMP
Supports ELF files which have been compiled externally.
> Added support for relocations R_RISCV_JAL and R_RISCV_RVC_JUMP for host

- modules/loader/source/relocations.cpp
R_RISCV_JAL and R_RISCV_RVC_JUMP were using the upper bit index rather than the size for the last parameter. This update correctly uses the size.
clang-tidy showed the issue
> Fix relocs for risc-v

- modules/compiler/test/lit/passes/barriers-dbg.ll
dbg output showed a poison value rather than an undef on llvm 20. Fixed up lit test
nightly testing failure.
> Fix dbg out in lit test for llvm 20

- source/cl/include/cl/command_queue.h
- source/cl/source/command_queue.cpp
- source/cl/source/export-apple.def
- source/cl/source/export-linux.map
- source/cl/source/export-linux.sym
- source/cl/source/export-windows.def.cmake
- source/cl/source/exports.cpp
- source/cl/source/extension/source/khr_icd.cpp
- source/cl/test/UnitCL/CMakeLists.txt
- source/cl/test/UnitCL/source/clSetCommandQueueProperty.cpp
OpenCL CTS has been changed to accept a failure for clSetCommandQueueProperty rather than it not existing, so it is added as an error reporting function.
CTS failure.
Added to exports, a test and a CL_INVALID_OPERATION return.
> Add support for returning an error for clSetCommandQueueProperty

- modules/compiler/vecz/test/lit/llvm/ScalableVectors/broadcast_vector.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_interleaved_store.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_interleaved_store_as_masked.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_subgroup_scans.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_subgroup_scans_vp.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/extract_element.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/insert_element.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/interleaved_load.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/packetize_mask_varying.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/select_scalar_vector.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/shuffle.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/subgroup_builtins.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/workitem_funcs.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/define_interleaved_load_store.ll
- modules/compiler/vecz/test/lit/llvm/irreducible_loop.ll
[LLVM 20] Adjust irreducible_loop test, adjust for non-experimental builtins
- LLVM 20 is able to produce simpler IR.
- Several llvm.stepvector builtins are no longer experimental.
- Handle this simpler IR in our checks.
- Adjust tests to allow both llvm.stepvector and llvm.experimental.stepvector names.
This test still had some support for LLVM 15, but we require LLVM 17+ already, so this is removed.
> [LLVM 20] Adjust irreducible_loop test, adjust for non-experimental builtins

- modules/compiler/vecz/test/lit/llvm/VectorPredication/packetize_mask_varying.ll
[LLVM 20] Adjust packetize_mask_varying test
LLVM 20 is able to figure out that the mask for this load is unnecessary, as it is always a splat of true.
Adjust the test to allow for this.
> [LLVM 20] Adjust packetize_mask_varying test

- modules/compiler/vecz/source/include/simd_packet.h
- modules/compiler/vecz/source/simd_packet.cpp
- modules/compiler/vecz/source/transform/scalarizer.cpp
- modules/compiler/vecz/test/lit/llvm/scalarize-bitcast.ll
[vecz] Avoid scalarization using large ints
When we scalarize, when needed, we bitcast values to integer types, shift and mask as needed, and then bitcast to the destination type. This is not generally valid: when any source element is poison, if it is inserted into a full-width integer type, the full integer becomes poison, it is not possible to mask out bits.
This commit avoids creating the full-width integer by bitcasting individual elements of the source vector, which not only avoids the bug but also generally results in simpler shorter code.
This commit also removes some dead code from scalarizer.cpp. UndefValue is already handled by the code immediately above.
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/CODE_OF …
> [vecz] Avoid scalarization using large ints

- modules/compiler/multi_llvm/include/multi_llvm/loop_utils.h
This has been renamed in llvm to createSimpleReduction, so modify multi_llvm.
llvm 20 change causes a breakage in ock build
Update in multi_llvm.
> Fix compiler breakage on llvm 20 for createSimpleTargetReduction.

- modules/compiler/vecz/source/vectorization_context.cpp
[LLVM20] Handle USubCond, USubSat.
LLVM 20 adds usub_cond and usub_sat atomicrmw instructions.
Handle them.
> [LLVM20] Handle USubCond, USubSat.

- modules/compiler/vecz/source/analysis/uniform_value_analysis.cpp
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/broadcast_vector.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/extract_element.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/insert_element.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/packetize_mask_varying.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/select_scalar_vector.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/shuffle.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/subgroup_builtins.ll
- modules/compiler/vecz/test/lit/llvm/control_flow_conversion_uniform_loop.ll
- modules/compiler/vecz/test/lit/llvm/extractelement_constant_index.ll
- modules/compiler/vecz/test/lit/llvm/load_add_store.ll
- modules/compiler/vecz/test/lit/llvm/packetization_uniform_branch.ll
- modules/compiler/vecz/test/lit/llvm/packetize_struct_gep.ll
- modules/compiler/vecz/test/lit/llvm/pass_pipeline_printafter.ll
- modules/compiler/vecz/test/lit/llvm/scalarization_instructions.ll
- modules/compiler/vecz/test/lit/llvm/scalarize_mixed_gep.ll
- modules/compiler/vecz/test/lit/llvm/squash_float2_gather.ll
- modules/compiler/vecz/test/lit/llvm/stride_analysis.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_broadcast.ll
- modules/compiler/vecz/test/lit/llvm/subgroup_builtins.ll
- modules/compiler/vecz/test/lit/llvm/uniform_address_base.ll
- modules/compiler/vecz/test/lit/llvm/uniform_address_index.ll
[vecz] Clear getelementptr flags.
If a getelementptr has inbounds/nusw/nuw flags, it is valid for the result to be out of bounds or to wrap so long as the result is not used to access any object. However, if we vectorize, multiple elements will all be loaded based on the first element's address, and in that we may add accesses, so we need to clear the inbounds/nusw/nuw flags unless we can prove they are still valid.
points, etc.*
*If you have added new testing, provide details on what tests you have …
> [vecz] Clear getelementptr flags.

- source/cl/test/UnitCL/source/C11Atomics.cpp
[UnitCL] Fix C11Atomics_73_*, C11Atomics_74_*, C11Atomics_75_*
These tests test atomic_compare_exchange_weak_explicit which is allowed to fail for no clear reason. The test tries to account for this by detecting output differences, using that to set a weak_exchange_failed boolean, and using that weak_exchange_failed boolean to detect where the result of atomic_compare_exchange_weak_explicit does not match expectations. That is, in output_reference, it does:
if (value == expected_values[success_index]) {
weak_exchange_failed = true;
return true;
}
Then, bool_output_reference is:
[success_index, weak_exchange_failed](size_t index) {
return index == success_index && !weak_exchange_failed;
};
The problem here is that bool_output_reference is constructed capturing weak_exchange_failed by …
> [UnitCL] Fix C11Atomics_73_*, C11Atomics_74_*, C11Atomics_75_*

- modules/compiler/utils/source/lld_linker.cpp
lldLinkToBinary: disable subreg liveness.
On LLVM versions prior to LLVM 20, enabling subreg liveness would lead to invalid code generation if an instruction defined an early-clobber register, used another register, and the register allocator wrongly allocated the subregister of the other register as the early-clobber def.
Work around this by disabling subreg liveness.
This is done in lldLinkToBinary so that it does not affect host: at the moment, we only know this to be a problem with RISC-V, and only when RVV is enabled. On host, we do not yet provide a supported way of enabling RVV.
* …
> lldLinkToBinary: disable subreg liveness.

- modules/compiler/targets/host/CMakeLists.txt
[NFC] Fix CMakeCache comments.
We were using the wrong host in the comment for e.g. CA_HOST_TARGET_AARCH64_FEATURES so that depending on configuration, we might document that as controlling RISCV64 features, and giving RISCV64-specific features as an example.
- Leave off "e.g. '+v,+zfh'" when the target is not RISC-V.
- For cross compilers, use the correct host.
* Run …
> [NFC] Fix CMakeCache comments.

- .github/dependabot.yml
- .github/workflows/scorecard.yml
- README.md
Enable OpenSSF scorecard, dependabot and add security policy. 
This is part of the security policy for Codeplay open source repositories. 
Dependabot will check for new versions of the external GitHub actions used and open pull requests with the required changes. By default the codeplaysoftware/security-managers team will be mentioned on these PRs.
OpenSSF Scorecard flags security issues and best practices that can be adopted. The README file will contain the score badge.
Also added Codeplay security policy file.
* Run …
> Enable OpenSSF scorecard, dependabot and add security policy

- .github/workflows/build_pr_cache.yml
- .github/workflows/create_llvm.yml
- .github/workflows/create_publish_artifacts.yml
- .github/workflows/docs.yml
- .github/workflows/run_ock_demo.yml
- .github/workflows/run_pr_tests.yml
Add top-level permissions to workflows.
Token-Permissions is one of the HIGH priority items on [OpenSSF Scorecard](https://scorecard.dev/viewer/?uri=github.com/codeplaysoftware/oneapi-construction-kit)
Top level token permissions limit the scope of the github token so it can't access more resources than needed. 
Most actions don't need access to all available resources. 
Documentation can be found here: 
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
* Run …
> Add top-level permissions to workflows

- .github/actions/build_portBLAS_action/action.yml
- .github/actions/build_portDNN_action/action.yml
- .github/actions/build_vgg_resnet_action/action.yml
- .github/actions/setup_ubuntu_build/action.yml
- .github/dependabot.yml
- .github/workflows/build_pr_cache.yml
- .github/workflows/create_llvm.yml
- .github/workflows/create_publish_artifacts.yml
- .github/workflows/docs.yml
- .github/workflows/run_ock_demo.yml
- .github/workflows/run_pr_tests.yml
- .github/workflows/scorecard.yml
- README.md
Pin external workflow actions to the commit hash. Also fix Scorecard badge.
Pinning external workflow actions to the hashed version is a good practice to help against supply chain attacks. This change will raise the OpenSSF score too.
External workflow actions have been pinned to the commit hash. The only actions not pinned are `llvm/actions/install-ninja` and `llvm/actions/setup-windows` as they don't have releases.
Dependabot will open PRs in the future, whenever pinned actions need update. 
By default, PRs open by dependabot to update dependencies will be tagged to be reviewed by @codeplaysoftware/security-managers and @codeplaysoftware/ock-workflow-reviewers as the code owners. 
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/ …
> Dependency pinning

- .github/workflows/codeql.yml
Add a workflow to run CodeQL on main branch and pull requests. 
CodeQL is a static application security testing (SAST) toolchain that allows to automate security checks and integrate them into our development workflows. 
Enabling CodeQL will run the scan process on main branch and pull requests. Results are accessible through the project `Security` tab. 
Workflow requires building the source code so it uses similar jobs to the ones defined in the `build_pr_cache.yml` workflow. 
* Run …
> Enable CodeQL SAST

- .github/workflows/create_llvm.yml
Add x86 support to create_llvm
x86 support
Add x86 llvm to cache. Tested in my fork.
> x86 updates to create_llvm

- .github/actions/do_build_ock/action.yml
Update build OCK action for new MR jobs. (A corresponding PR for the first such job will follow once this is merged)
Running a range of selected MR jobs in my Github fork has shown the need to update and expand the build action. The MR jobs are now also running without the build.py script previously used in Gitlab.
General approach has been to review existing settings and add new ones as required with a reasonable default.
The action has been tested against a range of MR jobs in my fork.
Changes and further additions are highly likely as more jobs are run.
> Update build OCK action

- clik/external/hal_cpu/include/cpu_hal.h
- clik/external/hal_cpu/source/cpu_hal.cpp
Support a cmake option to set the number of threads used on cpu hal
CPU HAL normally creates a number of threads for each kernel enqueue based on std::thread::hardware_concurrency. This is catastrophic on qemu where this causes memory to be continually increased. 
Add CA_HAL_CPU_WG_NUM_THREADS cmake variable
> Allow setting of CPU HAL WG mode number of threads

- modules/compiler/builtins/abacus/source/abacus_math/erfc.cpp
Fixes for double precision erfc.
- polynomial5 did not provide as many coefficients as needed for sufficiently accurate results around x=7. Use sollya to recompute.
- s6, s7, s8 multiplied by x rather than by xAbs, leading to incorrect results for x<0.
- s6, s7, s8 lost precision in the multiplication by x. Use multiply_exact_unsafe instead, and then transform exp(mul_hi + mul_lo) into exp(mul_hi) * exp(mul_lo).
- The transformation of erfc(-x) = 2 - erfc(x) checked the sign bit of the intermediate result, rather than the sign bit of x, again leading to incorrect results for x<0.
- The cut-off point for returning 0 was set as x > 27.0, but this is not right, …
> Fixes for double precision erfc.

- CONTRIBUTING.md
Explain to users how to create a pull request and request CI
We wish to be available for pull requests and are tightening up the requirements for things like CI
Updated section in CONTRIBUTING.md
> Updated CONTRIBUTING guide to explain pull request protocol

- modules/compiler/builtins/abacus/source/abacus_extra/refract.cpp
refract: match argument types earlier.
refract takes it eta parameter as a float even when I and N are double. However, in this case, we still want the eta * eta multiplication to be performed in double precision.
Change the internal implementation function to not have mismatched parameter types.
> refract: match argument types earlier.

- modules/compiler/builtins/abacus/generate/abacus_detail_geometric/abacus_detail_geometric.in
- source/vk/examples/VectorAddition/source/main.c
Fix build with MSVC, fix VectorAddition test.
- MSVC wants max to be captured if it has automatic storage. It should not, but the MSVC option to behave in a standards-conforming manner is only available in newer versions than what we aim to support.
- VectorAddition calls vkMapMemory which takes a pointer to a void* output parameter, then copies the result to a int32_t* variable for easier access. In commit ea1a63d005, I missed one copy.
- Work around this by changing the storage to static.
- Add the missing copy.
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/CODE_OF_CONDUCT.md) …
> Fix build with MSVC, fix VectorAddition test.

- .github/actions/do_build_ock/action.yml
- .github/actions/do_build_ock/do_build_m1/action.yml
- .github/workflows/pull-request.yml
- .github/workflows/pull_request.yml
Add an initial PR job: mr-ubuntu-gcc-x86_64-riscv-fp16-cl3-0-unitcl_vecz
Also fix an upper-case anomaly with the build action inputs strings.
Allows basic PR testing - a single job with others to follow.
Add pull-request workflow containing single PR job.
Notable changes from Gitlab:
- build.py is retired. PR job calls an updated Github build action instead.
- setup and build actions are subject to change as other PR jobs are added.
Test results are the same as for the latest corresponding Gitlab MR job.
> add single pr job

- modules/mux/targets/host/test/UnitCL/hostBuiltInKernels.cpp
[NFC] Address remaining clang-tidy warnings.
clang-tidy wants multi-level pointer conversions to be explicit.
Do so.
> [NFC] Address remaining clang-tidy warnings.

- .github/actions/setup_ubuntu_build/action.yml
Upgrade one more clang-format.
The adding of the Ubuntu job and the upgrade to clang-format 19 were done at the same time, so we missed this.
points, etc.* …
> Upgrade one more clang-format.

- .github/workflows/run_pr_tests.yml
clang-format: fix output.
Now that we have upgraded to clang-format-19, its exit status already indicates whether any changes were suggested. We no longer need to save it to a file and count the lines, and our efforts were causing the output to be hidden.
points, etc.*
understanding and verifying your patch, please …
> clang-format: fix output.

- modules/compiler/compiler_pipeline/source/add_scheduling_parameters_pass.cpp
- modules/compiler/compiler_pipeline/source/barrier_regions.cpp
- modules/compiler/compiler_pipeline/source/builtin_info.cpp
- modules/compiler/compiler_pipeline/source/cl_builtin_info.cpp
- modules/compiler/compiler_pipeline/source/degenerate_sub_group_pass.cpp
- modules/compiler/compiler_pipeline/source/optimal_builtin_replacement_pass.cpp
- modules/compiler/compiler_pipeline/source/pass_functions.cpp
- modules/compiler/compiler_pipeline/source/replace_local_module_scope_variables_pass.cpp
- modules/compiler/multi_llvm/include/multi_llvm/intrinsic.h
- modules/compiler/source/base/source/builtin_simplification_pass.cpp
- modules/compiler/source/base/source/combine_fpext_fptrunc_pass.cpp
- modules/compiler/source/base/source/fast_math_pass.cpp
- modules/compiler/source/base/source/printf_replacement_pass.cpp
- modules/compiler/source/base/source/software_division_pass.cpp
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/targets/host/source/AddFloatingPointControl.cpp
- modules/compiler/vecz/source/include/memory_operations.h
- modules/compiler/vecz/source/include/transform/control_flow_conversion_pass.h
- modules/compiler/vecz/source/memory_operations.cpp
- modules/compiler/vecz/source/transform/basic_mem2reg_pass.cpp
- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- modules/compiler/vecz/source/transform/packetization_helpers.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/source/transform/pre_linearize_pass.cpp
- modules/compiler/vecz/source/transform/remove_intptr_pass.cpp
- modules/compiler/vecz/source/transform/simplify_infinite_loop_pass.cpp
- modules/compiler/vecz/source/transform/ternary_transform_pass.cpp
- modules/compiler/vecz/source/transform/uniform_reassociation_pass.cpp
- modules/compiler/vecz/source/vector_target_info.cpp
- modules/compiler/vecz/source/vector_target_info_arm.cpp
Fix build with LLVM 20.
* LLVM 20 renames Intrinsic::getDeclaration to Intrinsic::getOrInsertDeclaration.
* LLVM 20 deprecates instruction creation overloads that take an Instruction * as an insertion point, recommending the ones that take an iterator instead. In LLVM 18, for the most part, those overloads taking iterators do not yet exist.
* Handle the Intrinsic function rename with a multi_llvm::GetOrInsertIntrinsicDeclaration helper function.
* In LLVM 18, Instruction::insertBefore does already take iterators, so rework the code to consistently use that. This removes some bitcast instructions in memory_operations.cpp that could not be updated, but had become unnecessary ever since LLVM switched to opaque pointers.
*If there's any other relevant information we should know that may help …
> Fix build with LLVM 20.

- doc/overview/compiler/supported-llvm-versions.rst
Update supported LLVM versions.
We regularly (not daily) test and support LLVM 18 and 19.
points, etc.*
Note that we also regularly test LLVM 20, but do not plan to support it until a release is out, so for now it stays out of this document.
* Make sure …
> Update supported LLVM versions.

- modules/compiler/builtins/abacus/include/abacus/internal/add_exact.h
- modules/compiler/builtins/abacus/include/abacus/internal/log2_extended_precision.h
- modules/compiler/builtins/abacus/include/abacus/internal/log_extended_precision.h
- modules/compiler/builtins/abacus/include/abacus/internal/multiply_extended_precision.h
- modules/compiler/builtins/abacus/include/abacus/internal/pow_unsafe.h
- modules/compiler/builtins/abacus/sollya/log2_extended_precision.sollya
- modules/compiler/builtins/abacus/source/abacus_math/acos.cpp
- modules/compiler/builtins/abacus/source/abacus_math/atan2pi.cpp
- modules/compiler/builtins/abacus/source/abacus_math/cospi.cpp
- modules/compiler/builtins/abacus/source/abacus_math/erfc.cpp
- modules/compiler/builtins/abacus/source/abacus_math/sinpi.cpp
- modules/compiler/builtins/abacus/source/abacus_math/tan.cpp
- source/cl/test/UnitCL/source/ktst_regression_04.cpp
Abacus: improve log2_extended_precision.
Our log2_extended_precision function used for implementing pow() had proved insufficiently precise for some input values. We already had a concept of a more precise implementation.
This commit takes the idea of that implementation, but uses Sollya to recompute the exact constants to use.
This PR includes a refactor to rename Abacus's add_exact and add_exact_safe functions. Elsewhere in Abacus, we use f_unsafe as a convention for a version of f that makes specific assumptions about its input parameters, and f for the version that does not make those assumptions. For add_exact, we had it the other way around, we had add_exact make specific assumptions about its input parameters, and add_exact_safe which did not. …
> Abacus: improve log2_extended_precision.

- README.md
Update OpenSSF scorecard badge and link on UXL foundation organization. 
It's showing the score when the repository was on Codeplay organization. 
> Update README file after migration to UXL foundation organization

- modules/compiler/spirv-ll/source/builder_core.cpp
Builder::create<OpBranchConditional>: Fix access to destroyed array.
Previously, md_arr was a named ArrayRef variable constructed from an initializer list. This initializer list causes a temporary array to be created, the ArrayRef is then bound to that temporary array, and then the temporary array gets destroyed. In the subsequent call to llvm::MDTuple::get(*context.llvmContext, md_arr) then, md_arr no longer referenced any array still in existence.
Make md_arr an array instead, like its name implies, to ensure it lives long enough to still be valid during MDTuple::get. …
> Builder::create<OpBranchConditional>: Fix access to destroyed array.

- modules/compiler/targets/host/source/target.cpp
Enable vfp4 for ARM.
We made the decision at the start of the year to only support targets that have hardware FMA support. This is available on 32-bit ARM, but only as of VFPv4.
Make sure to enable this.
> Enable vfp4 for ARM.

- modules/compiler/compiler_pipeline/source/add_kernel_wrapper_pass.cpp
- modules/compiler/compiler_pipeline/source/cl_builtin_info.cpp
- modules/compiler/compiler_pipeline/source/mux_builtin_info.cpp
- modules/compiler/compiler_pipeline/source/replace_atomic_funcs_pass.cpp
- modules/compiler/compiler_pipeline/source/replace_local_module_scope_variables_pass.cpp
- modules/compiler/source/base/source/printf_replacement_pass.cpp
- modules/compiler/targets/host/source/HostMuxBuiltinInfo.cpp
- modules/compiler/vecz/source/transform/builtin_inlining_pass.cpp
- modules/compiler/vecz/source/transform/remove_intptr_pass.cpp
- modules/compiler/vecz/source/vector_target_info.cpp
[NFC] Avoid deprecated Type::getPointerTo.
Type::getPointerTo has been deprecated in favour of PointerType::get.
This commit updates the calls accordingly.
Exceptions:
- Some uses were to perform bitcasts between pointer types. These bitcasts did nothing ever since LLVM moved to opaque pointers, and are removed instead.
- Some uses were in a context where an IRBuilder was available, in which case IRBuilder::getPtrTy provides a simpler alternative.
> [NFC] Avoid deprecated Type::getPointerTo.

- .github/actions/do_build_ock/action.yml
- .github/workflows/run_pr_tests.yml
- .github/workflows/run_pr_tests_caller.yml
- source/cl/test/UnitCL/CMakeLists.txt
Reduce PR testing overheads
PR testing is taking too long
Add CMake option  CA_CL_ENABLE_UNITCL_EXPENSIVE_CHECK to disable full
unitcl testing for some cases. Per job we can enable/disable per job
with the pull_request flag. Currently only apply the expensive flag to a long running windows job.
> Reduce PR testing overheads

- .github/workflows/codeql.yml
Switch off cache build save with CodeQL PR jobs - and make them use the standard PR "changed files" set.
Cache build save not needed.
Set CodeQL's setup_build action params correctly and update its `on:pull_request:` settings.
> Switch off codeql cache build save for PR jobs

- .github/workflows/create_llvm.yml
This reduces the amount of space required substantially by passing -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON for Ubuntu builds.
llvm artefacts were taking up a substantial amount of room in our cache space.
> Added shared library flags for llvm builds to create smaller artefacts

- source/cl/test/FuzzCL/CMakeLists.txt
Add missing reference for threads.
After the bump to OpenCL ICD Loader, on Ubuntu 20, linking FuzzCL fails with an undefined reference to pthread_create. It appears that the older version of OpenCL ICD Loader implicitly referenced libpthread, whereas the newer version does not.
Explicitly add the reference instead.
* Run [clang-format-19](https://clang.llvm.org/docs/ClangFormat.html) on all …
> Add missing reference for threads.

- modules/compiler/vecz/test/lit/llvm/loop_call_instantiation.ll
- modules/compiler/vecz/test/lit/llvm/struct_select.ll
[LLVM 20] Update tests.
loop_call_instantiation sees an extra flag added to icmp. Allow that.
struct_select hits a new optimization that happens because both structure elements are the same type. Use different types to get the same IR we got before.
* Run …
> [LLVM 20] Update tests.

- modules/compiler/source/base/source/module.cpp
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/broadcast_vector.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/cmpxchg.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_interleaved_store.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_interleaved_store_as_masked.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/define_subgroup_scans.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/extract_element.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/insert_element.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/interleaved_load.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/packetize_mask_varying.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/select.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/select_scalar_vector.ll
- modules/compiler/vecz/test/lit/llvm/ScalableVectors/shuffle.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/define_interleaved_load_store.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/load_add_store.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/udiv.ll
LLVM 20: Pass in VFS to createDiagnostics.
LLVM 20 makes VFS a required parameter of createDiagnostics.
Pass it in.
> LLVM 20: Pass in VFS to createDiagnostics.

- .github/actions/build_portDNN_action/action.yml
- .github/actions/calc_vars/action.yml
- .github/actions/do_build_icd/action.yml
- .github/actions/do_build_ock_artefact/action.yml
- .github/actions/do_build_tornado/action.yml
- .github/actions/run_tornado/action.yml
- .github/actions/setup_build/action.yml
- .github/workflows/create_llvm.yml
- .github/workflows/planned_testing.yml
- .github/workflows/planned_testing_caller.yml
- .github/workflows/run_pr_tests.yml
- .github/workflows/run_pr_tests_caller.yml
Add ock artefact building, icd building and tornado run for planned testing
Need to port some of our local testing to planned to improve public level of testing.
Added planned testing which is intended to run long running scheduled
tests. Added a base which they can all use which allows all jobs to
follow a similar method of using a matrix, a named target and a flag
which dictates what tests are enabled.
icd, ock artefacts and tornado are done as part of this.
> Add ock artefact building

- .github/dependabot.yml
Remove reviewers for depedabot PRs. 
Dependabot PRs were configured to request review from a team not present in current organization. security-managers  team on UXL foundation is not in charge of updating workflow dependencies. 
Remove reviewers configuration. 
N/A
> Remove uxlfoundation/security-managers as dependabot reviewers

- modules/compiler/vecz/test/lit/llvm/constant_address.ll
- modules/compiler/vecz/test/lit/llvm/constant_address_with_uniform.ll
- modules/compiler/vecz/test/lit/llvm/emit_memintrinsics.ll
- modules/compiler/vecz/test/lit/llvm/gep_duplication.ll
[LLVM 20] Allow getelementptr nuw flag.
LLVM 20 adds more flags to getelementptr.
Allow this.
> [LLVM 20] Allow getelementptr nuw flag.

- .github/workflows/run_pr_tests.yml
- .github/workflows/run_pr_tests_caller.yml
Fix scheduling of pr test workflow
Scheduled pr testing did not run.
Having the same concurrency group in the caller and the callee was causing
issues. This removes the concurrency group setting in run_pr_tests.yml.
It also simplifies the original calling workflow to one job.
> Fix scheduling of pr test workflow

- CONTRIBUTING.md
- README.md
Updated CONTRIBUTING and README.md to refer to the slack channel.
Make it easier for users to see that as an option. Fits with uxlfoundation.
Added some references to readme and contributing guides.
> Updated CONTRIBUTING and README.md to refer to the slack channel.

- CONTRIBUTING.md
- README.md
Use GitHub Discussions instead of Slack.
#612 updated the documentation to refer to a new Slack channel, but after some more discussion, that turns out to not be what we want to be using since we have GitHub Discussions already.
Additionally, the CONTRIBUTING page is not where I would expect to find the instructions on how to ask questions.
- Change references to Slack to reference GitHub Discussions instead
- Move support section of CONTRIBUTING to README …
> Use GitHub Discussions instead of Slack.

- .github/actions/do_build_icd/action.yml
- .github/actions/do_install_ubuntu_cross_tools/action.yml
- .github/actions/setup_build/action.yml
This fixes the ICD overnight failure for aarch64 by calling a new action do_install_ubuntu_cross_tools which will also be used by setup_build.
> [GITHUB CI] Add support for cross compilation installation for ICD

- .github/workflows/create_llvm.yml
Add riscv64 support to create_llvm
Part of OpenCL CTS work for aarch64 and riscv64
Added riscv64 support on the same basis as aarch64
Version numbers for build tool install (aarch64 & riscv64) have been removed.
> Add riscv64 support to create_llvm

- .github/actions/setup_build/action.yml
- .github/workflows/run_pr_tests.yml
Use cp-ubuntu-24.04 with ubuntu 22.04 image on slow PR job
Desire to speed up jobs and provide a pathway to use these runners.
Uses cp-ubuntu-24.04, but with ubuntu 22.04 image from intel/llvm. Required a few small additional installs/env vars etc to make it work.
> Use cp-ubuntu-24.04 with ubuntu 22.04 image on slow PR job

- .github/workflows/create_llvm.yml
fix llvm cache riscv64/aarch64 mismatch
cut'n'paste issue unearthed by aarch64 rebuild
use riscv64
> fix riscv64/aarch64 mismatch

- .github/workflows/create_llvm.yml
Roll-back inclusion of llvm cache riscv64
Issues associated with riscv64 llvm cache build need fuller consideration prior to inclusion.
Exclude riscv64
Note: removal of `g++-11-aarch64-linux-gnu` version number has been retained. (this was unintentionally omitted when other similar version numbers were removed)
> Roll-back inclusion of llvm cache riscv

- .github/actions/do_build_ock_artefact/action.yml
- .github/workflows/planned_testing.yml
- .github/workflows/planned_testing_caller.yml
Switch over planned testing to use cp-ubuntu-24.04 for ock/OpenCL
Speed up overnight builds
Switched ock artefact creation and OpenCL build/run to use cp-ubuntu-24.04 (with docker).
> Switch over planned testing to use cp-ubuntu-24.04 for ock/OpenCL

- modules/compiler/compiler_pipeline/source/work_item_loops_pass.cpp
- modules/compiler/test/lit/passes/work-item-loops-broadcast-4.ll
- modules/compiler/test/lit/passes/work-item-loops-scan-4.ll
[compiler] Handle skipped vectorized functions.
In corner cases, we may end up with a vectorized function that is unconditionally skipped because the trip count can be determined at compilation time to be 0. The code that was already there to handle this was not quite right.
points, etc.*
understanding and …
> [compiler] Handle skipped vectorized functions.

- .github/actions/do_build_sycl_cts/action.yml
Fix sycl cts building on self-hosted runner
The runner was failing to run as it could not run swapoff which is not needed on the self-hosted runner.
Deleted section which did the swapoff in ci.
> Fix sycl cts building on self-hosted runner

- modules/compiler/compiler_pipeline/source/work_item_loops_pass.cpp
[compiler] Avoid out of bounds access.
If !isScan, ivs1 is not guaranteed to hold at least two items and we could fail trying to retrieve ivs1[1] even if the result would be unused.
points, etc.* …
> [compiler] Avoid out of bounds access.

- .github/actions/do_build_ock/action.yml
- .github/actions/setup_build/action.yml
- .github/workflows/planned_testing.yml
- .github/workflows/run_pr_tests.yml
Update to use dockers built for OCK
Using different runners is causing issues with not always using the same dockers. This also allows us to move more setup into the dockers.
Added container:/image: to most jobs
Note  run_clang_tidy_changes is currently disabled until we can resolve the errors brought up
> Update to use dockers built for OCK

- .github/workflows/run_pr_tests.yml
Fix clang-tidy job
This was both incorrect and did not work with the new dockers.
This replicates our original code in our previous internal CI.  We cannot reliably get dependencies of clang-tidy targets by grepping for add_dependencies. Luckily, we do not need to: we can simply look for all targets ending in '.cpp' or '.h' instead.
> Fix clang-tidy job

- .github/dockerfiles/Dockerfile_22.04
- .github/dockerfiles/Dockerfile_24.04
- .github/workflows/publish_docker_images.yml
Add more baseline content to the dockerfiles. Most of this comes from existing Gitlab dockers - a little from additional settings included in the Github scripts (A forthcoming PR will complete the migration from the scripts). New "test" images will be created.
On-going migration to containers in Github.
Misc updates to both 22.04 and 24.04 dockerfiles and creation of corresponding "test" images.
Image filenames include the string `_test_` to distinguish the new images from existing "official" images. The intention is to make test images available for read/write from dev branches without standing on the toes of the official set. The official images will be updated with latest content in due course.
> Update dockerfiles with baseline content

- modules/compiler/compiler_pipeline/source/pass_functions.cpp
- modules/compiler/compiler_pipeline/source/work_item_loops_pass.cpp
- modules/compiler/test/lit/passes/barriers-cfg-reduce.ll
- modules/compiler/test/lit/passes/subgroup-loop-unroll.ll
- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- source/cl/test/UnitCL/cmake/CompileKernelToBin.cmake
[compiler] Do not mix kernels with different sub-group sizes.
Per OpenCL 3.0 API 3.2.1 Mapping Work-items Onto an Nd-range, all sub-groups within a work-group will be the same size, apart from the sub-group with the maximum index which may be smaller if the size of the work-group is not evenly divisible by the size of the sub-groups. We were not meeting this requirement: in cases where we would not or could not generate a predicated vectorized kernel, we would execute the scalar kernel in a loop for any remaining work items, possibly resulting in multiple sub-groups that are smaller than the maximum sub-group size.
To avoid this situation, we need to avoid mixing vector and scalar kernels if those kernels use different sub-group sizes. If we can handle all items with vector kernels, …
> [compiler] Do not mix kernels with different sub-group sizes.

- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/packetize_i48.ll
[vecz] Handle missing gather/scatter functions.
If we encounter types we do not know how to mangle, we cannot generate gather or scatter functions.
Just use scalar loads and stores for this.
> [vecz] Handle missing gather/scatter functions.

- modules/compiler/spirv-ll/include/spirv-ll/builder.h
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
Builder::create<OpVariable>: Set address space of builtins.
Builtins are supposed to be declared with the Input storage class, but are not. We were working around this by ignoring the storage class and forcibly overriding how the builtin got declared, but this breaks now that DPC++ generates different SPIR-V, which puts it in a different storage class, resulting in us seeing address space casts where there should be none.
Work around this by putting globals in whatever address space is implied by the storage class.
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/CODE_OF_CONDUCT.md …
> Builder::create<OpVariable>: Set address space of builtins.

- .github/actions/do_build_dpcpp/action.yml
- .github/actions/do_build_ock_artefact/action.yml
- .github/actions/do_build_sycl_cts/action.yml
- .github/actions/setup_gh/action.yml
- .github/workflows/planned_testing.yml
- .github/workflows/planned_testing_caller.yml
Support a method of using a previous workflow runs's artefact
Sometimes we want to fix something far down the chain running sycl cts and don't want to run all the way through.
Add inputs to planned_testing:
download_ock_artefact, download download_dpccp_artefact and download_sycl_cts_artefact which can allow downloading an artefact from a previous workflow run for a particular target or set of targets.
> Reuse previous workflow run's artefacts

- modules/compiler/compiler_pipeline/source/work_item_loops_pass.cpp
- modules/compiler/spirv-ll/source/builder_debug_info.cpp
Update for LLVM 20.
* dib.createObjectPointerType now takes an extra argument indicating whether we have an implicit or an explicit 'this'. Pass this along.
* PointerUnion::get has been deprecated in favor of llvm::cast. Since this works on LLVM 19 too, just use this unconditionally. …
> Update for LLVM 20.

- modules/compiler/vecz/source/transform/packetization_helpers.cpp
- modules/compiler/vecz/test/lit/llvm/vector_size_1.ll
[vecz] Handle vectors of size 1.
Vectors of size 1 are valid, but were internally getting mishandled by the packetization treating them as scalars.
Check whether the vecz source instruction was using vectors and if so, keep it using vectors.
> [vecz] Handle vectors of size 1.

- modules/mux/targets/riscv/source/device_info.cpp
For the riscv mux target, GetDeviceInfos always returned 1 when called with device_infos_length = 0 and out_device_infos = nullptr to query the number of available devices, regardless of the actual number of devices detected in the system.
This fixes it by always returning the number of available devices in the system, but still only filling the provided vector up to its own capacity.
> Fix logic to query the number of available devices

- .github/actions/run_opencl_cts/action.yml
- .github/actions/run_sycl_cts/action.yml
- .github/opencl_cts/expect_fail_all.csv
- .github/opencl_cts/expect_fail_host_riscv64_linux.csv
- .github/sycl_cts/expect_fail_all.csv
Ensure that expected fails on CTS always show as a pass.
When we have regular fails which we do not expect an immediate fix, we
want to show as pass so we can catch be failures more easily.
When we know there is an expected fail, we create files to cover fails
on all targets or fails on a particular target for OpenCL CTS and
SYCL CTS. These will be under .github/opencl_cts and .github/sycl_cts.
Fails files will be of the form expect_fail_all.csv or expect_fail_<target>.csv.
These should match lines in the original csv file being used.
> Ensure that expected fails on CTS always show as a pass.

- rfc-0003.md
Added rfc for removing vulkan SDK.
See rfc
See rfc
> Added rfc for removing vulkan SDK.

- doc/modules.md
- modules/CMakeLists.txt
- modules/cargo/CMakeLists.txt
- modules/compiler/builtins/CMakeLists.txt
- modules/compiler/multi_llvm/CMakeLists.txt
- modules/compiler/spirv-ll/CMakeLists.txt
- modules/compiler/vecz/CMakeLists.txt
- modules/kts/CMakeLists.txt
- modules/mux/CMakeLists.txt
- modules/tracer/CMakeLists.txt
- modules/utils/CMakeLists.txt
- source/cl/source/extension/CMakeLists.txt
[NFC] Remove unused CMake variables.
MODULES_INCLUDE_DIRS and MODULES_LIBRARIES were still around to support libraries that could not use target_include_directories for whatever reason, but the only library that ever made use of this was cargo, and we changed that in 2016 already. This has been dead code ever since.
points, etc.*
*If there's any other relevant information we should know that …
> [NFC] Remove unused CMake variables.

- scripts/testing/city_runner/profiles/default.py
change city runner default to cd into directory of test.
A recent change to an OpenCL CTS test showed that their usage of the csv file changes to the directory of the test before running it.
This changes city runner to follow the same method as OpenCL CTS for csv files by default.
> Change city runner default to cd into directory of test.

- .github/actions/run_opencl_cts/action.yml
The qemu path for city runner was having slightly different behaviour  than the default profile. Rather than fixing it there,
move to using  --prepend-path which means the same profile is used. 
aarch64/riscv64 qemu failures on spirv_new in opencl-cts
> [CI] Change to use --prepend-path for qemu using city runner

- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/builder_opencl.cpp
- modules/compiler/spirv-ll/test/spvasm/op_lifetime_unsized.spvasm
- modules/compiler/spirv-ll/test/spvasm/op_opencl_printf.spvasm
- modules/compiler/test/lit/passes/image-arg-subst-tgt-tys-64.ll
- modules/compiler/test/lit/passes/image-arg-subst-tgt-tys.ll
- modules/compiler/test/lit/passes/replace-image-tys-64.ll
- modules/compiler/test/lit/passes/replace-image-tys.ll
- modules/compiler/test/lit/passes/replace-local-module-scope-mem_builtins.ll
- modules/compiler/test/lit/passes/replace-local-module-scope-vars-cmp.ll
- modules/compiler/vecz/test/lit/llvm/VectorPredication/boscc_reduction.ll
LLVM 21: Update for Attribute::NoCapture removal.
LLVM 21 removes the nocapture attribute in favor of captures(none).
Make sure we handle that.
In tests where nocapture was not relevant to what was being tested and where it can be removed, remove it. In other tests, change the CHECK lines to permit both nocapture and captures(none).
* Run [clang-format-19](https://clang.llvm.org/docs/ClangFormat.htm …
> LLVM 21: Update for Attribute::NoCapture removal.

- .github/workflows/planned_testing.yml
Fix incorrect image organisation spec for aarch64 OpenCL CTS runs
Organisation is wrong - mistakenly points to dev account
Point to uxlfoundation which now houses the image concerned. By chance the incorrect image currently has the correct content so workflows will pass, but its clearly wrong.
> Fix image organisation for aarch64

- modules/compiler/compiler_pipeline/source/barrier_regions.cpp
- modules/compiler/compiler_pipeline/source/pass_functions.cpp
- modules/compiler/multi_llvm/include/multi_llvm/dibuilder.h
- modules/compiler/spirv-ll/include/spirv-ll/builder.h
- modules/compiler/spirv-ll/include/spirv-ll/builder_debug_info.h
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/source/builder_debug_info.cpp
- modules/compiler/vecz/source/transform/instantiation_pass.cpp
- modules/compiler/vecz/source/transform/pre_linearize_pass.cpp
- modules/compiler/vecz/source/transform/scalarizer.cpp
- modules/compiler/vecz/source/vectorization_helpers.cpp
Update for LLVM 20, 21.
More functions have had their overloads taking Instruction * deprecated in favour of using iterators to mark insertion points.
Make the suggested changes.
> Update for LLVM 20, 21.

- README.md
- modules/compiler/riscv/CMakeLists.txt
- modules/mux/targets/riscv/source/kernel.cpp
Address several refsi issues.
* Be clearer in the README when refsi is and is not meant to be used.
* Ensure that when compiler-linker-utils cannot be built because liblld is not available, that liblld is mentioned in the error message.
* Avoid a potential unused capture in a lambda, which breaks the build when using clang. …
> Address several refsi issues.

- modules/mux/targets/riscv/include/riscv/device_info.h
- modules/mux/targets/riscv/source/device_info_get.cpp
There was a harcoded maximum of devices used as static size for a std::array.
This removes the limit and uses a dynamically sized std::vector instead.
> Remove max_device_infos limit in riscv mux target

- .github/actions/do_build_pr/run_host_x86_64/action.yml
- .github/actions/do_build_pr/run_riscv_m1/action.yml
- .github/actions/do_build_pr/run_ubuntu_clang_x86_llvm_latest_cl3_0_offline/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_aarch64_llvm_latest_cl3_0_fp16/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_64_refsi_g1_wi_cl3_0/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_64_riscv_fp16_cl3_0/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_64_riscv_fp16_cl3_0_unitcl_vecz/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_llvm_latest_x86_64_images_cl3_0_release/action.yml
- .github/actions/do_build_pr/run_windows_msvc_x86_64_llvm_latest_cl3_0_offline/action.yml
- .github/actions/setup_build/action.yml
- .github/workflows/pr_tests_cache.yml
- .github/workflows/run_pr_tests.yml
- .github/workflows/run_pr_tests_caller.yml
Switch to calling an action for PR tests and populate the cache sequentially
There was a race condition in updating the cache as it just ran the tests overnight in parallel. 
Move all the build parts of PR jobs to an action. Add a workflow pr_tests_cache.yml to seed the caches by calling the actions in sequence. The scheduled run_pr_tests overnight will no longer have the ability to seed the cache and this will only be done via pr_tests_cache.yml.
This does not yet delete the caches. We can't be sure this works so this is initially commented out. …
> Switch to calling an action for PR tests and improve caching

- .github/actions/run_opencl_cts/action.yml
- .github/actions/run_sycl_cts/action.yml
- .github/opencl_cts/expect_fail_all.csv
- .github/opencl_cts/expect_fail_host_riscv64_linux.csv
- .github/opencl_cts/override_all.csv
- .github/opencl_cts/override_host_riscv64_linux.csv
- .github/sycl_cts/expect_fail_all.csv
- .github/sycl_cts/override_all.csv
- .github/workflows/planned_testing_caller.yml
- doc/scripts/city_runner.rst
- scripts/testing/city_runner/profile.py
- scripts/testing/city_runner/profiles/basic.py
- scripts/testing/city_runner/profiles/gtest.py
- scripts/testing/city_runner/profiles/tensorflow.py
- scripts/testing/city_runner/runner.py
- scripts/testing/city_runner/test_info.py
- scripts/testing/city_runner/ui.py
Support attribute Xfail and Mayfail for city runner and an add a --override option to override entries in the main csv file. 
We want to be able to run tests that we know fail, but we don't want an overall fail.
Added xfail and Mayfail as attributes to city runner.
Xfail means we expect it to fail and will give a failing return code if it unexpectedly pass, otherwise it does not contribute to an overall fail.
Mayfail means it sometimes fails and will not contribute to a failing return code.
Unlike some of the other attributes, these cannot be set with additional csv files, as it was felt this leads to overcomplexity. Instead it is expected that some form of csv combination script could be used alongside this.
Added --override option. This provides an additional csv file which can override …
> Added Xfail and Mayfail attributes to city runner

- .github/workflows/delete_cache_entries.yml
Add a workflow to tidy up cache entries
Old cache timestamped files are cluttering up our cache space
Use gh to delete old cache entries
> Add a workflow to tidy up cache entries

- .github/dockerfiles/Dockerfile_22.04-aarch64
Changes for aarch64 dockerfile
Changes made to build/run SYCL CTS on graviton (aarch64)
Additions as required.
This is a companion prerequisite PR to: https://github.com/uxlfoundation/oneapi-construction-kit/pull/681
... which is on-going. No further updates should be needed here.
> Docker changes for aarch64 (graviton)

- .github/dockerfiles/Dockerfile_22.04-aarch64
Docker updates to support: changing of PR job for cross aarch64 to use aarch64 runner and not build as cross platform.
Dockerfile updates as required.
Add missing install components.
> Updates to aarch64 docker for PR job on internal runner

- .github/actions/do_build_pr/run_ubuntu_gcc_aarch64_llvm_latest_cl3_0_fp16/action.yml
- .github/workflows/pr_tests_cache.yml
- .github/workflows/run_pr_tests.yml
Switch run-ubuntu-gcc-aarch64-llvm-latest-cl3-0-fp16 to run as a non-cross platform job using a github hosted aarch64 runner.
Use aarch64 github runner.
Updates runner, docker image and "cross" status
Depends on: https://github.com/uxlfoundation/oneapi-construction-kit/pull/696
Comment from Colin re. vulkan: 
> I'm inclined to drop the vulkan in the test rather than bloating the aarch64 docker - I also don't see an aarch64 non-windows vulkak sdk and we want to drop it anyway
> Switch aarch64 PR job to run non-cross using github runner. 

- .github/dockerfiles/Dockerfile_22.04-aarch64
- .github/dockerfiles/Dockerfile_22.04-x86-64
- .github/dockerfiles/Dockerfile_24.04-x86-64
Add llvm 18 and 19 as apt sources to the docker
Required for running PRs where we install llvm
Updated dockers to add apt sources for 18 and 19 to all dockers.
This also installs gpg and wget in the aarch64 docker.
> Add llvm 18 and 19 as apt sources to the dockers

- .github/actions/setup_build/action.yml
- .github/workflows/pr_tests_cache.yml
- .github/workflows/run_pr_tests.yml
- .github/workflows/run_pr_tests_caller.yml
Change llvm over to a choice of install or cache. Default PRs to install.
Dependency on caches can cause failures for users which cannot be remedied quickly
Pass a flag into setup_build llvm_source which dictates whether it should
get the llvm from cache or install. It will set a symbolic link if
required for an install so it's in the same place. All pr tests if run
as a pull request will run using an install except windows where this
is not yet supported.
Move 32 bit x86 job to only run on nightly.
> Change llvm over to a choice of install or cache, default PRs to install

- cmake/ImportLLVM.cmake
- doc/developer-guide.md
- modules/compiler/riscv/CMakeLists.txt
- modules/compiler/source/base/CMakeLists.txt
- modules/compiler/utils/CMakeLists.txt
Add CA_LLVM_LIBDIR_SUFFIX.
When building against an LLVM that was built with LLVM_LIBDIR_SUFFIX set, we would fail to locate that LLVM's CMake files due to hardcoded paths.
Allow CA_LLVM_LIBDIR_SUFFIX to be set to the same value to work around that.
> Add CA_LLVM_LIBDIR_SUFFIX.

- cmake/AddCA.cmake
- modules/compiler/builtins/libimg/CMakeLists.txt
For CMake 3.24+, use COMPILE_WARNINGS_AS_ERRORS.
Unlike the hardcoded -Werror in CA_COMPILE_OPTIONS, COMPILE_WARNINGS_AS_ERRORS can be disabled by the user if desired with `cmake --compile-no-warning-as-error`.
points, etc.*
* Read and follow the …
> For CMake 3.24+, use COMPILE_WARNINGS_AS_ERRORS.

- modules/compiler/riscv/source/module.cpp
- modules/compiler/source/base/source/module.cpp
- modules/compiler/source/base/source/target.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/targets/host/source/target.cpp
- modules/compiler/vecz/test/lit/llvm/packetization_debug_info.ll
- modules/compiler/vecz/tools/source/veczc.cpp
Update for LLVM 21.
LLVM 21 has made changes to have modules store a triple, rather than a triple string, and several APIs were adjusted accordingly.
Update OCK to handle the new APIs.
> Update for LLVM 21.

- .github/opencl_cts/override_all.csv
- .github/opencl_cts/override_host_riscv64_linux.csv
Delete the override_all.csv file and move test_api over to the host_riscv64_linux target.
test_api now passes for host x86_64 and aarch64, although still fails for riscv64
> [CI] Update opencl_cts override files for test_api

- .github/opencl_cts/override_host_riscv64_linux.csv
- modules/compiler/targets/host/source/HostPassMachinery.cpp
- modules/compiler/targets/host/source/module.cpp
Fix more CL_KERNEL_LOCAL_MEM_SIZE.
In addition to the previous issue in handling local kernel arguments, CL_KERNEL_LOCAL_MEM_SIZE was also incorrect for non-deferred-compilation targets due to running
ComputeLocalMemoryUsagePass either not at all, or after ReplaceLocalModuleScopeVariablesPass. In order to get the correct local memory usage, the former needs to be run before the latter.
Update where it gets run.
This fixes the same OpenCL CTS test as before, `test_api`'s `kernel_local_memory_size`, in other configurations.
This PR leaves CL_KERNEL_LOCAL_MEM_SIZE unmodified for non-host targets. …
> Fix more CL_KERNEL_LOCAL_MEM_SIZE.

- .github/workflows/run_pr_tests.yml
This is a precursor to running the tests overnight on a single version, by using inputs for run_pr_tests for llvm versions rather than hardwiring it.
It also simplifies the switch to the next llvm to changing two lines.
> [CI] Update run_pr_tests to take flags for llvm_current and llvm_previous

- modules/compiler/targets/host/source/module.cpp
Fix CL_KERNEL_LOCAL_MEM_SIZE a third time.
My previous change made it so that ComputeLocalMemoryUsagePass assuredly ran before ReplaceLocalModuleScopeVariablesPass which is necessary for correct results, but also made it so that with deferred compilation, it could run after encoding the kernel metadata, meaning the correct results came in too late.
Previously, it was getting additionally run in HostModule::createKernel so that results would always be available. Restore this.
* Make sure the project builds …
> Fix CL_KERNEL_LOCAL_MEM_SIZE a third time.

- .github/sycl_cts/override_all.csv
Remove test_language fail from our xfail list for sycl_cts
This tests now passes okay.
> Remove test_language fail from our xfail list for sycl_cts

- hal/hal_remote/include/hal_remote/hal_server.h
Fix hal_remote build
The previous attempt to address the issue raised by clang-tidy (virtual class with public non-virtual destructor) was not right: hal_server is constructed directly, not through any derived class.
hal_server is never derived from, so we can make it a non-virtual class instead.
> Fix hal_remote build

- .github/workflows/planned_testing.yml
Switch most jobs over to internal runners and split sycl-cts jobs
We were seeing some issue with the github hosted runners which meant that we could lose the whole run if anything went wrong.
Reduce dependency by moving most jobs over to github runners and splitting sycl cts so we don't stall the x86 run.
> Switch most jobs over to internal runners and split sycl-cts jobs

- scripts/testing/city_runner/test_info.py
- scripts/testing/city_runner/ui.py
Added an xfail_list to city runner which is output at the end.
For clarity, we wish to see any expected fails in the summary at the end.
> Update city runner to always output xfails

- modules/compiler/vecz/source/include/transform/packetization_helpers.h
- modules/compiler/vecz/source/transform/packetization_helpers.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/packetize_phi_struct.ll
[vecz] Fix packetization of PHIs of literal structs.
We packetize literal structs elementwise, but were failing to account for that in the handling of PHIs.
Handle this and add a test that covers it.
> [vecz] Fix packetization of PHIs of literal structs.

- .github/actions/setup_build/action.yml
Windows build was complaining because the ICD loader minumum version was < 3.5. This fixes this until they have updated that.
> Set minimum cmake version via cmake options to 3.5

- .github/workflows/planned_testing_caller.yml
Removed concurrency group from planned_testing_caller.yml
Having the same concurrency group at the top level (planned_testing_caller_19.yml) and the next level down (planned_testing_caller.yml) was causing a deadlock on the scheduled run.
> Fix concurrency issue on scheduling.

- modules/compiler/multi_llvm/include/multi_llvm/target_transform_info.h
- modules/compiler/vecz/include/vecz/vecz_target_info.h
- modules/compiler/vecz/source/vector_target_info.cpp
[LLVM 21] Take address space into account for legality.
LLVM 21 allows for the possibility that some operations are legal only in some address spaces.
points, etc.* …
> [LLVM 21] Take address space into account for legality.

- .github/sycl_cts/override_opencl.csv
This fails to build due to an upstream issue, so xfail it.
> xfail sycl cts test_hierarchical

- modules/compiler/vecz/source/analysis/vectorizable_function_analysis.cpp
- modules/compiler/vecz/source/include/analysis/vectorizable_function_analysis.h
- source/cl/test/UnitCL/source/ktst_vecz_tasks_task_11.cpp
Do not vectorize NoInline kernels.
A recent LLVM 21 change prevents us from being able to vectorize NoInline kernels.
It was probably never a good idea to vectorize them anyway: it is not clear whether the vectorization we perform is something that a user who writes `__attribute__((noinline))` would want. Therefore, explicitly reject vectorization of NoInline functions and restore affected tests to their original version that permitted them to not be vectorized.
* Make sure the project builds successfully with …
> Do not vectorize NoInline kernels.

- .github/actions/do_build_dpcpp/action.yml
- .github/actions/do_build_sycl_cts/action.yml
- .github/actions/run_sycl_cts/action.yml
- .github/sycl_cts/override_opencl_host_riscv64_linux.csv
- .github/workflows/planned_testing_caller_19.yml
- .github/workflows/run_ock_external_tests.yml
Add SYCL_CTS CI for riscv64 opencl & native_cpu
Completes SYCL_CTS for all supported architectures.
- added riscv64 SYCL_CTS build & run workflow jobs.
- dpc++ build action updated to handle download/unpackage pre-reqs for riscv64 cross compilation artifacts, with architecture strings added to the install directories for clarity.
- cross-compilation options added to the dpc++ configuration job
- dpc++ configuration files now installed to pick up libraries for cross compilation.
- sycl_cts build action updated to handle download/unpackage pre-reqs for riscv64 cross compilation artifacts, again with architecture strings added to the install directories for clarity.
- PREPEND_PATH options (qemu) added to sycl_cts run job for riscv64.
- single opencl XFAIL test added to the new …
> SYCL_CTS CI for RISC-V on Opencl & Native_cpu

- modules/compiler/compiler_pipeline/CMakeLists.txt
- modules/compiler/compiler_pipeline/include/compiler/utils/remove_address_spaces_pass.h
- modules/compiler/compiler_pipeline/source/remove_address_spaces_pass.cpp
- modules/compiler/source/base/source/base_module_pass_machinery.cpp
- modules/compiler/source/base/source/base_module_pass_registry.def
- modules/compiler/targets/host/source/HostPassMachinery.cpp
- scripts/testing/sycl_cts/override_opencl_llvm_19.csv
[LLVM 19] Work around loop vectorizer issue.
The loop vectorizer gets confused by having pointers to distinct address spaces that are derived from the same object. This has been fixed for LLVM 20, but as long as we support LLVM 19, work around it there.
points, etc.*
understanding and verifying your patch, please …
> [LLVM 19] Work around loop vectorizer issue.

- scripts/testing/sycl_cts/override_opencl_host_riscv64_linux.csv
Remove RISC-V math_builtin_float_half_* XFail.
This too was fixed by #762.
points, etc.* …
> Remove RISC-V math_builtin_float_half_* XFail.

- .github/actions/do_build_llvm/action.yml
- .github/workflows/planned_testing_caller_20.yml
Add initial `apt-get update` commands for llvm builds. Previously in place for x86_64 only.
Omission of commands fails llvm 20 builds.
Add missing updates.
Test builds get passed previous point of failure.
Any dev/test scaffolding will be removed prior to final merge.
> Add initial apt-get updates for aarch64/riscv64 llvm (20) builds

- .github/actions/build_portBLAS_action/action.yml
- .github/actions/setup_build/action.yml
- .github/workflows/codeql.yml
- .github/workflows/create_publish_artifacts.yml
- .github/workflows/pr_tests_cache.yml
- .github/workflows/run_ock_demo.yml
- .github/workflows/run_ock_internal_tests.yml
Update llvm versions to 19/20 for pr_test_cache, codeql etc.
18 has been dropped, these workflow should have been updated too.
Dropped default from setup_build and updated to 19/20 on pr_test_cache, codeql and the ock demo
> Update llvm versions to 19/20 for pr_test_cache, codeql etc.

- .github/workflows/planned_testing_caller_19.yml
- .github/workflows/run_ock_external_tests.yml
Allow riscv64 variant of the ock_external workflow to be run independently from other architectures.
Cross-compile job dependencies were wrong for riscv64 when run alone, leaving a loophole which failed the ock_external workflow. This fix restores "run alone" support for riscv, bringing it into line with other architectures.
- Refactor the `build_dpcpp_native_*` ock_external  jobs to allow riscv64 to be run independently of x86_64. 
- Update downstream jobs `needs:` to indicate the new dependencies involved.
- Various combinations of architectures - run-alone and otherwise - have been tested to verify the fix.
- Test results match those currently produced on `main`.
- Some planned_testing_caller development/testing scaffolding remains in place to reduce test time and will be removed prior …
> CI ock_external workflow update for stand-alone riscv64 

- .github/workflows/pr_tests_cache.yml
This resolves previous failures, by dropping 32 bit x86 caching and commenting out the windows seeding.
Note the windows seeding should be restored as soon as PR #707 is merged.
Failing to run to completion due to cache dependencies which are no longer valid.
> Fix pr tests cache for cases where it required a cache

- .github/workflows/planned_testing_caller.yml
- .github/workflows/planned_testing_caller_19.yml
- scripts/testing/city_runner/test_info.py
- scripts/testing/sycl_e2e/override_opencl.csv
The fix is to restore the updating of test_info's variables from the disabled list amongst others, whilst keeping the refactored update using a function.
This was broken in a recent refactoring causing some test to be run that were disabled.
> Fix for disabled path for city runner

- modules/compiler/compiler_pipeline/source/builtin_info.cpp
- modules/compiler/multi_llvm/include/multi_llvm/intrinsic.h
Support multiple Intrinsic::getAttributes() versions by using templates to allow support for both. This can be simplified in the future once dpc++ catches up with LLVM in this aspect.
LLVM has changed the function signature of Instrinsic::getAttributes
> Fix up Instrinsic::getAttributes to work across LLVM versions

- scripts/testing/sycl_cts/tests.csv
Revert "Update override_native_cpu file after dpc++ fix."
This partially reverts commit 614d201894bcae30d5dadac7c855d6af7ee3a29d.
The commit inadvertently removed tests.csv entirely.
points, etc.* …
> Revert "Update override_native_cpu file after dpc++ fix."

- source/cl/test/UnitCL/source/cl_khr_command_buffer/clEnqueueCommandBufferKHR.cpp
This fixes the IncrementKernelTwiceDifferentQueues UnitCL test by doing a clFinish on the command queue immediately after the fill.
This test was occasionally failing due to a race condition on the fill, which must take place before enqueuing the command buffers.
> Fix UnitCL test IncrementKernelTwiceDifferentQueues

- scripts/testing/city_runner/profiles/lit.py
- scripts/testing/city_runner/test_info.py
- scripts/testing/sycl_cts/override_native_cpu_host_aarch64_linux.csv
- scripts/testing/sycl_cts/override_opencl.csv
- scripts/testing/sycl_e2e/override_all.csv
- scripts/testing/sycl_e2e/override_native_cpu.csv
Fix city runner lit profile to support multiple overrides for same test
The lit profile incorrectly handled the case where there was multiple  override entries matching the same test. 
This handles this case by copying  the each csv entry line that matches the test and processing the final match.
This also removes the test sycl-external-with-optional-features.cpp from an override for xfail.
> Fix city runner lit profile to support multiple overrides for same test

- modules/compiler/compiler_pipeline/include/compiler/utils/builtin_info.h
- modules/compiler/compiler_pipeline/include/compiler/utils/cl_builtin_info.h
- modules/compiler/compiler_pipeline/source/add_scheduling_parameters_pass.cpp
- modules/compiler/compiler_pipeline/source/barrier_regions.cpp
- modules/compiler/compiler_pipeline/source/builtin_info.cpp
- modules/compiler/compiler_pipeline/source/cl_builtin_info.cpp
- modules/compiler/compiler_pipeline/source/define_mux_builtins_pass.cpp
- modules/compiler/compiler_pipeline/source/define_mux_dma_pass.cpp
- modules/compiler/compiler_pipeline/source/lower_to_mux_builtins_pass.cpp
- modules/compiler/compiler_pipeline/source/optimal_builtin_replacement_pass.cpp
- modules/compiler/compiler_pipeline/source/prepare_barriers_pass.cpp
- modules/compiler/compiler_pipeline/source/replace_wgc_pass.cpp
- modules/compiler/compiler_pipeline/source/sub_group_analysis.cpp
- modules/compiler/compiler_pipeline/source/work_item_loops_pass.cpp
- modules/compiler/source/base/source/set_convergent_attr_pass.cpp
- modules/compiler/test/group_ops.cpp
- modules/compiler/vecz/source/analysis/instantiation_analysis.cpp
- modules/compiler/vecz/source/analysis/simd_width_analysis.cpp
- modules/compiler/vecz/source/analysis/uniform_value_analysis.cpp
- modules/compiler/vecz/source/analysis/vectorizable_function_analysis.cpp
- modules/compiler/vecz/source/offset_info.cpp
- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- modules/compiler/vecz/source/transform/inline_post_vectorization_pass.cpp
- modules/compiler/vecz/source/transform/instantiation_pass.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/source/transform/scalarizer.cpp
- modules/compiler/vecz/source/vectorization_context.cpp
- modules/compiler/vecz/source/vectorization_heuristics.cpp
- modules/compiler/vecz/test/lit/llvm/vector_printf_def.ll
[builtins] Improve robustness.
* Replace eBuiltinInvalid with std::optional to force callers to figure out what to do when a function is not a built-in.
* Do not assert that CallInst::getCalledFunction() returns a function. The called operand is not required to be a function, and even if it is a function, getCalledFunction() can return nullptr on signature mismatches.
* Add a test that we no longer crash on vectorizing a kernel containing calls to printf() when a conflicting definition of printf() has been provided. This cannot happen in OpenCL, but can happen in NativeCPU. …
> [builtins] Improve robustness.

- examples/refsi/refsi_m1/compiler/refsi_m1/source/refsi_mux_builtin_info.cpp
- modules/compiler/compiler_pipeline/source/cl_builtin_info.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
[NFC] Fix comments.
getPtrTy()'s parameter is called AddrSpace, not AddressSpace. Adjust comments accordingly.
> [NFC] Fix comments.

- scripts/testing/sycl_cts/override_native_cpu.csv
Mark OpenCL interop tests as ignored for NativeCPU.
Marking them as Xfail gets confusing in the error log. These tests make no sense for NativeCPU and are not built, so should not be run.
points, etc.* …
> Mark OpenCL interop tests as ignored for NativeCPU.

- scripts/testing/sycl_cts/override_native_cpu.csv
- scripts/testing/sycl_cts/tests.csv
SYCL-CTS scalars_interopability_types: remove XFail.
We marked this as failing on NativeCPU because there are no interoperability tests there, but that is inconsistent with how we handle possibly nonexistent tests elsewhere.
We can just run with --allow-running-no-tests to not treat that as an error.
> SYCL-CTS scalars_interopability_types: remove XFail.

- modules/compiler/targets/host/source/target.cpp
- modules/mux/targets/host/test/UnitCL/host_clGetDeviceInfo.cpp
- modules/utils/include/utils/system.h
- modules/utils/targets/host/source/relocations.cpp
Fixes for Windows on ARM.
* HostTarget::initWithBuiltins was overly complicated in a way that needs each triple to be spelled out. For non-Linux, we do not support cross-compilation and can just always use llvm::sys::getProcessTriple() + "-elf".
* MSVC on ARM defines _M_ARM64, not __aarch64__. Check that.
* We have special MinGW exceptions for where they use different function names than MSVC, but MinGW (MSYS) on ARM matches MSVC.
This change is not to mark Windows for ARM as a supported target. Although it works after this pull request, it is not a platform we test regularly and future changes may inadvertently break it again.
* Read and follow the project …
> Fixes for Windows on ARM.

- rfc-0003.md
Additional clarification on Vulkan SDK removal
Some comments were not fully addressed in discussions and further discussion has taken place.
Mention code removal and support.
> Additional clarification on Vulkan SDK removal

- scripts/testing/sycl_e2e/override_opencl.csv
Set xfail on graph test fails
https://github.com/intel/llvm/pull/18177/files removed UNSUPPORTED from multiple tests, and we now see some new graph fails.
> Added more e2e xfails opencl / sycl e2e  for new graph fails

- modules/compiler/multi_llvm/include/multi_llvm/targetinfo.h
- modules/compiler/source/base/source/module.cpp
[LLVM 21] Update for CreateTargetInfo API change.
CreateTargetInfo no longer receives a shared_ptr, it receives a reference instead.
points, etc.*
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-k …
> [LLVM 21] Update for CreateTargetInfo API change.

- modules/compiler/cookie/{{cookiecutter.target_name}}/source/module.cpp
Update cookiecutter analyzeBuiltin.
In #789 I changed the signature of analyzeBuiltin to use std::optional, but did not update the cookiecutter override of it to match.
This commit fixes that.
> Update cookiecutter analyzeBuiltin.

- .github/actions/do_build_pr/run_windows_msvc_x86_64_llvm_latest_cl3_0_offline/action.yml
- .github/actions/setup_build/action.yml
- .github/workflows/pr_tests_cache.yml
- .github/workflows/run_ock_internal_tests.yml
- .github/workflows/run_pr_tests_caller.yml
Update Windows PR test to build via LLVM github release 'download & extract' (rather than cache)
First use of non-cache for windows (previously hard-wired).  
First use of download&extract Github LLVM artefacts.
- Use Github download/extract artefacts for Windows PR jobs. 
- Update `llvm_version` setting to incorporate downloads from `llvm-release`. 
- Work-around hard-wired reference to VS "Professional" lib (when "Enterprise" is actually installed)
- Fix `pull_request:` param - should be `is_pull_request:`
The test to which this PR refers was blocked by the following issue: https://codeplaysoft.atlassian.net/browse/OR-750
Now unblocked.
> Run Windows PR test via github llvm release download

- modules/compiler/multi_llvm/include/multi_llvm/instructions.h
- modules/compiler/multi_llvm/include/multi_llvm/instructions.inc
- modules/compiler/vecz/source/vectorization_context.cpp
[NFC] Address LLVM 21's BinOp additions in a better way.
The earlier change to restore compatibility with LLVM 21 required suppressing compiler warnings and made it so that we would not be alerted when we need to account for future BinOp additions.
This change moves the complexity of dealing with the different LLVM versions from vectorization_context.cpp into multi_llvm, and handles it in a way that does not require suppressing compiler warnings.
* …
> [NFC] Address LLVM 21's BinOp additions in a better way.

- .github/actions/do_build_ock/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_64_refsi_tutorial/action.yml
- .github/workflows/pr_tests_cache.yml
- .github/workflows/run_ock_internal_tests.yml
Added refsi_tutorial as an internal test
This tests the "end" part of refsi_tutorial as a PR job. "start" is to follow in a separate PR.
Test not yet ported over. We were getting breakages from changes.
points, etc.*
* Read and follow the project …
> Added refsi_tutorial as an internal test

- scripts/testing/patches/DPCPP-0004-Revert-SelectionDAG-Introducing-a-new-ISD-POISON-SDN.patch
Add LLVM patch to DPC++ to fix crashes on RISC-V.
We see crashes building SYCL-CTS for RISC-V.
The fix for this has been merged in upstream LLVM but will not be included in DPC++ until their next pulldown. Apply it as a patch until then.
> Add LLVM patch to DPC++ to fix crashes on RISC-V.

- scripts/testing/city_runner/profiles/lit.py
Fix city runner lit profile for windows
This was not setting the correct flag for windows when setting up the lit config
points, etc.*
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main …
> Fix city runner lit profile for windows

- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/test/spvasm/op_function_call_regression.spvasm
Set SPIR-V ByVal and Sret alignment
In SPIR-V, the ByVal and Sret attributes on function parameters are not stated to specify any requirements on alignment. In LLVM, the byval attribute on function parameters implies "a target-specific assumption" on alignment if no explicit alignment is specified, which is an incorrect translation: we need to ensure that no invalid assumptions are made.
Explicitly set the alignment to 1.
Setting an explicit alignment also works around LLVM bug 138356 where the ARM backend assumes that alignment is always set. …
> Set SPIR-V ByVal and Sret alignment

- scripts/testing/sycl_e2e/override_all.csv
Updated xfails for e2e to include new thread san fails
New tests have been added, these fail too.
> Updated xfails for e2e to include new thread san fails

- .github/actions/do_build_ock/action.yml
- .github/workflows/docs.yml
- CHANGELOG.md
- CMakeLists.txt
- cmake/AddCA.cmake
- doc/developer-guide.md
- doc/modules/mux/targets/host/lit.md
- doc/overview/tutorials/creating-a-new-mux-target/building-and-running-tests.rst
- examples/hal_cpu_remote_server/README.md
- examples/technical_blogs/refsi_simple_blog1/run_tech_blog_1.sh
- modules/compiler/targets/riscv/test/lit/CMakeLists.txt
- modules/mux/targets/host/CMakeLists.txt
- modules/mux/targets/host/test/lit/CMakeLists.txt
- source/CMakeLists.txt
Remove CA_ENABLE_API as a CMake option
We only support OpenCL as a an API now, so it makes sense to remove this option.
> Remove CA_ENABLE_API as a CMake option

- source/cl/test/UnitCL/source/cl_khr_command_buffer/clCommandNDRangeKernelKHR.cpp
Add missing clean-up.
The newly added command_buffer created a memory buffer without releasing it.
points, etc.* …
> Add missing clean-up.

- .github/actions/do_build_pr/run_ubuntu_clang_x86_llvm_latest_cl3_0_offline/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_aarch64_llvm_latest_cl3_0_fp16/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_64_refsi_g1_wi_cl3_0/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_64_refsi_tutorial/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_64_riscv_fp16_cl3_0/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_64_riscv_fp16_cl3_0_unitcl_vecz/action.yml
- .github/actions/do_build_pr/run_ubuntu_gcc_x86_llvm_latest_x86_64_images_cl3_0_release/action.yml
- .github/workflows/run_pr_tests_caller.yml
Stop using gold.
[gold has been deprecated][1] and so we should stop relying on it.
[1]: https://lists.gnu.org/archive/html/info-gnu/2025-02/msg00001.html
Use the default linker instead.
> Stop using gold.

- modules/compiler/source/base/include/base/module.h
- modules/compiler/source/base/source/module.cpp
[LLVM 21] Pass diags by reference.
LLVM 21 changes who owns a clang::DiagnosticOptions and changes the API to match, changing pointers to references.
Update accordingly.
> [LLVM 21] Pass diags by reference.

- modules/compiler/include/compiler/module.h
- modules/compiler/source/base/source/module.cpp
- modules/compiler/spirv-ll/include/spirv-ll/builder.h
- modules/compiler/spirv-ll/include/spirv-ll/module.h
- modules/compiler/spirv-ll/source/builder.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/spirv-ll/source/context.cpp
- modules/compiler/spirv-ll/source/module.cpp
[spirv-ll][NFC] Remove shader-specific SPIR-V support.
This was only used with the Vulkan API which we no longer support.
points, etc.*
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/mai …
> [spirv-ll][NFC] Remove shader-specific SPIR-V support.

- .github/actions/do_build_dpcpp/action.yml
- .github/workflows/planned_testing_caller_20.yml
[CI] Specify specific OCK commit to fetch when building DPC++.
We were fetching refs/pull/* in order to ensure that we would always have pull/<id>/merge available, without accounting for the fact that pull/<id>/merge may change after CI has been triggered.
We should not need to fetch all PRs anyway, we only need the specific commit that we are trying to build, so explicitly fetch that instead.
This approach cannot be used with arbitrary ock_git_tag. We were not using that functionality so this removes the option.
* Run …
> [CI] Specify specific OCK commit to fetch when building DPC++.

- cmake/AddCA.cmake
- cmake/FindLit.cfg
- cmake/FindLit.cmake
- modules/lit/ca-lit.in
Pick up correct Python for ca-lit.
When lit has been installed in a venv (possibly using pipx), a Python outside of that venv will not be able to load any lit module.
Make sure we use whatever Python lit itself uses.
> Pick up correct Python for ca-lit.

- scripts/testing/sycl_e2e/override_native_cpu.csv
Remove overrides for passing work group e2e tests on native cpu
> Remove overrides for passing work group e2e tests on native cpu

- .github/workflows/pr_tests_cache.yml
Drop implicit permissions again.
When I moved the workflow-level permissions to the job level, I forgot that this re-enables implicit permissions unless we explicitly specify otherwise.
points, etc.* …
> Drop implicit permissions again.

- external/CMakeLists.txt
Define BENCHMARK_STATIC_DEFINE.
For Windows builds, BENCHMARK_STATIC_DEFINE needs to be defined to tell Google Benchmark not to apply DLL attributes.
points, etc.* …
> Define BENCHMARK_STATIC_DEFINE.

- .github/dockerfiles/Dockerfile_22.04-aarch64
- .github/dockerfiles/Dockerfile_22.04-x86-64
- .github/dockerfiles/Dockerfile_24.04-x86-64
These can be simplified to be useful for the vast majority to jobs, but still have most of the useful installations present, so installing things will still be mostly not required.
Simplify dockers, including removing vulkan sdk and clang-tidy
The current dockers take about 1m20s to load.  Vulkan SDK is also no longer needed, along with llvm 18.
Removed a lot of installs, particularly llvm ones that only apply to single jobs like clang-tidy. Where it doesn't add too much to the docker and is used in multiple jobs, I've tried to keep it with the aim of having the load under 25 seconds. https://github.com/uxlfoundation/oneapi-construction-kit/pull/819/ shows approximately what would be required beyond now to work with these docker changes.
> Simplify dockers, including removing vulkan sdk and clang-tidy

- .github/workflows/codeql.yml
- .github/workflows/create_publish_artifacts.yml
- .github/workflows/planned_testing_caller_19.yml
- .github/workflows/pr_tests_cache.yml
- .github/workflows/run_ock_demo.yml
- .github/workflows/run_ock_external_tests.yml
- .github/workflows/run_ock_internal_tests.yml
Some additional installs are added to take into account the smaller docker
The docker is being shrunk slightly - see
https://github.com/uxlfoundation/oneapi-construction-kit/pull/852.
> Update to use smaller docker with a few extra installs

- .github/actions/do_build_run_remote_hal/action.yml
- .github/workflows/planned_testing_caller.yml
- .github/workflows/planned_testing_caller_19.yml
- .github/workflows/run_ock_external_tests.yml
Migrate remote_hal build/run to Github
On-going CI move to Github
- Add remote_hal test to planned testing.
- Add remote_hal job to external OCK tests.
- Add build/run remote_hal action. Server build/client build/run all live in the same action
- Updated server start-up check. Job fails if no start-up detected.
Github job replicates the corresponding output on Gitlab.
> Migrate remote_hal to Github CI

- scripts/testing/sycl_cts/override_all.csv
Remove test_atomic XFail.
The fix for this has been merged in DPC++.
points, etc.* …
> Remove test_atomic XFail.

- modules/compiler/compiler_pipeline/source/add_kernel_wrapper_pass.cpp
[NFC] Avoid deprecation warning.
ArrayRef(std::nullopt_t) is deprecated in favor of {}.
We use MDNode::get(..., {}) in other places already, do the same here.
> [NFC] Avoid deprecation warning.

- .github/dockerfiles/Dockerfile_22.04-aarch64
Add ninja to aarch64 docker builds for consistency.
> Add ninja to aarch64 docker builds for consistency.

- scripts/testing/city_runner/test_info.py
- scripts/testing/city_runner/ui.py
city runner: do not mark skipped tests as failing.
If we encounter a new test, we previously only allowed three scenarios: pass, timeout, or fail. If the test did not pass and did not time out, we treated it as a fail. This is incorrect for tests that self-report as skipped, which need to be treated as a separate category.
This change implements that.
* Run …
> city runner: do not mark skipped tests as failing.

- .github/workflows/planned_testing_caller.yml
- .github/workflows/planned_testing_caller_main.yml
- .github/workflows/run_ock_external_tests.yml
- .github/workflows/run_ock_internal_tests.yml
Change name of target host_refsi_linux to refsi_riscv64_linux
The original name was confusing and this makes more consistent.
> Change name of target host_refsi_linux to refsi_riscv64_linux

- modules/compiler/utils/CMakeLists.txt
Avoid linking in LLVMSPIRVLib.
If LLVM is built together with SPIRV-LLVM-Translator, we may inadvertently link in its library. This can result in errors.
Make sure we skip that.
> Avoid linking in LLVMSPIRVLib.

- .github/workflows/run_ock_internal_tests.yml
When we test daily llvm tip, we only build x86_64 llvm. Some of the internal tests require 32 bit llvm and had been wrongly tagged to try running. This updates the tags on jobs to host_i686_linux where necessary.
> Disable 32 bit x86 tests when only building 64 bit x86_64 llvm

- .github/workflows/create_publish_artifacts.yml
- .github/workflows/docs.yml
- .github/workflows/planned_testing_caller_19.yml
- .github/workflows/planned_testing_caller_20.yml
- .github/workflows/planned_testing_caller_21.yml
- .github/workflows/planned_testing_caller_main.yml
- .github/workflows/planned_testing_caller_mini_main.yml
- .github/workflows/pr_tests_cache.yml
Conditionals on running workflows didn't correctly check the repository due to the || github.event_name != 'schedule'.
Removed this ||, only allow workflow events where appropriate.
Workflows were running on forks
> Fix workflows running in forks.

- clik/examples/clik_async/barrier_print/barrier_print.cpp
- clik/examples/clik_async/barrier_sum/barrier_sum.cpp
- clik/examples/clik_async/concatenate_dma/concatenate_dma.cpp
- clik/examples/clik_async/copy_buffer/copy_buffer.cpp
- clik/examples/clik_async/hello/hello.cpp
- clik/examples/clik_async/ternary/ternary.cpp
- clik/examples/clik_async/vector_add/vector_add.cpp
- clik/examples/clik_async/vector_add_wfv/vector_add_wfv.cpp
- clik/examples/clik_sync/copy_buffer/copy_buffer.cpp
- clik/examples/clik_sync/hello/hello.cpp
- clik/examples/clik_sync/vector_add/vector_add.cpp
[clik] Add missing includes.
We were using strtoull without including <stdlib.h>, which may or may not work depending on exactly which headers get included implicitly by other headers. With newer libstdc++, it no longer works.
Include the header directly.
> [clik] Add missing includes.

- .github/workflows/planned_testing_caller.yml
- .github/workflows/run_ock_external_tests.yml
- scripts/testing/sycl_e2e/override_host_aarch64_linux.csv
- scripts/testing/sycl_e2e/override_native_cpu.csv
- scripts/testing/sycl_e2e/override_native_cpu_host_aarch64_linux.csv
- scripts/testing/sycl_e2e/override_native_cpu_host_x86_64_linux.csv
- scripts/testing/sycl_e2e/override_opencl.csv
- scripts/testing/sycl_e2e/override_opencl_host_aarch64_linux.csv
- scripts/testing/sycl_e2e/override_opencl_host_x86_64_linux.csv
Add github ci support for e2e aarch64
It is useful to test the aarch64 architecture along with x86_64.
Add jobs for e2e for opencl and native_cpu for aarch64. This also involves
some overrides to match specific fails for aarch64.
Also fixed some if: conditions on jobs as it was noticed they ran when
top level flags suggested they should not.
> [CI][E2E] Add support for e2e aarch64

- modules/compiler/compiler_pipeline/include/compiler/utils/device_info.h
- modules/compiler/compiler_pipeline/source/builtin_info.cpp
- modules/compiler/compiler_pipeline/source/cl_builtin_info.cpp
- modules/compiler/compiler_pipeline/source/mux_builtin_info.cpp
- modules/compiler/compiler_pipeline/source/replace_local_module_scope_variables_pass.cpp
- modules/compiler/compiler_pipeline/source/replace_mem_intrinsics_pass.cpp
- modules/compiler/compiler_pipeline/source/unique_opaque_structs_pass.cpp
- modules/compiler/compiler_pipeline/source/work_item_loops_pass.cpp
- modules/compiler/vecz/source/control_flow_boscc.cpp
- modules/compiler/vecz/source/pass.cpp
- modules/compiler/vecz/source/transform/basic_mem2reg_pass.cpp
- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/source/transform/ternary_transform_pass.cpp
- modules/compiler/vecz/source/vector_target_info.cpp
- modules/compiler/vecz/source/vector_target_info_arm.cpp
- modules/compiler/vecz/source/vector_target_info_riscv.cpp
- modules/compiler/vecz/source/vectorization_context.cpp
- modules/compiler/vecz/test/lit/llvm/basic_vecz_mem2reg.ll
- modules/compiler/vecz/test/lit/llvm/builtin_pointer_return.ll
- modules/compiler/vecz/test/lit/llvm/partial_linearization_exit_masks.ll
- modules/compiler/vecz/test/lit/llvm/ternary_transform.ll
There are multiple references which are not publicly visible. Remove the ones under compiler_pipeline and vecz as part of this process.
> Remove CA references under compiler_pipeline and vecz

- modules/compiler/compiler_pipeline/source/remove_lifetime_intrinsics_pass.cpp
- modules/compiler/spirv-ll/test/spvasm/op_lifetime_sized.spvasm
- modules/compiler/spirv-ll/test/spvasm/op_lifetime_unsized.spvasm
- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/divergent_loop_bug.ll
[LLVM 22] A few more lifetime fixes.
* Obtain lifetime_(start|end) pointer argument by getting last argument.
* Do not update size argument when there is no size argument.
* Update tests.
> [LLVM 22] A few more lifetime fixes

- scripts/testing/sycl_cts/tests.csv
[CI] Tweak test_vector_swizzles invocation.
The tests have been broken up so that we now have not vector_swizzles_bool, but vector_swizzles_bool_0,
vector_swizzles_bool_1, etc.
This commit updates our tests.csv accordingly.
> [CI] Tweak test_vector_swizzles invocation.

- modules/compiler/test/lit/passes/replace-local-module-scope-vars-dbg-2.ll
- modules/compiler/vecz/test/lit/llvm/inlined_function_debug_info.ll
- modules/compiler/vecz/test/lit/llvm/insert_element_debug_info.ll
- modules/compiler/vecz/test/lit/llvm/packetization_debug_info.ll
- modules/compiler/vecz/test/lit/llvm/phi_node_debug_info.ll
- modules/compiler/vecz/test/lit/llvm/scalarization_debug_info.ll
[NFC] Remove unused %pp-llvm-ver.
A number of tests were still using %pp-llvm-ver despite not having any LLVM-version-conditional checks.
points, etc.*
* Read and follow the project [Code of Conduct](https://github.com/uxlfoundation/oneapi-construction …
> [NFC] Remove unused %pp-llvm-ver.

- .github/actions/run_opencl_cts/action.yml
- .github/workflows/run_ock_external_tests.yml
Avoid +v warnings running OpenCL CTS.
We were setting CA_HOST_TARGET_FEATURES=+v to enable RVV, but for non-RISC-V it makes no sense and results in warnings.
This commit changes that so that we set it only for RISC-V.
> Avoid +v warnings running OpenCL CTS.

- .github/workflows/planned_testing_caller.yml
- .github/workflows/run_ock_internal_tests.yml
- .github/workflows/run_pr_tests_caller.yml
[CI] Fix branch for build-ock-in-tree-llvm.
We were using release/$version.x as the branch name, which is fine for versions 20 and 21, but which does not work for version main.
We already have the branch name as an input in planned_testing_caller.yml, so pass this along instead.
> [CI] Fix branch for build-ock-in-tree-llvm.

- .github/actions/do_build_dpcpp/action.yml
- .github/actions/do_build_sycl_cts/action.yml
- .github/actions/run_sycl_cts/action.yml
- .github/workflows/planned_testing_caller_20.yml
- .github/workflows/planned_testing_caller_21.yml
- .github/workflows/planned_testing_caller_main.yml
[NFC] Remove leftover RISC-V SYCL bits.
In !994, I removed RISC-V SYCL testing, but there were a few places that still had logic to handle it.
This commit cleans up those last bits.
> [NFC] Remove leftover RISC-V SYCL bits.

- scripts/testing/sycl_e2e/override_all.csv
Updated overrides for sycl e2e, sycl_cache and select_device_cpu
> [CI] Updated overrides for sycl e2e, sycl_cache and select_device_cpu
