- .github/workflows/docs.yml
Added a pull request workflow for testing documentation
There is no current PR testing for building the documentation.
This adds a workflow which will build it and create an artifact, but not deploy it which will require a different workflow.
* Run [clang-format-9](https://clang.llvm.org/docs/ClangFormat.html) on all modified code.
> Added workflow for html documentation

- CONTRIBUTORS.md
Add more names to the contributors list
After reaching out, more people would like to be recognized for their work
> Added some more names to the contributors list

- modules/compiler/source/base/source/spir_fixup_pass.cpp
This precedes the work that we need to do on it to bring it up to date for LLVM 17. This flushes some inevitable cosmetic changes from the queue. It's a fairly cosmetic change - there's a lot of structural and algorithmic work we could do on it too.
> [compiler] Reformat SpirFixupPass in the LLVM code style

- .github/workflows/docs.yml
- .github/workflows/run_pr_tests.yml
Fixed the workflow for documentation changes being run when anything under doc changes
Changes in the doc directory did not trigger the workflow to run
Fixed the workflow triggering to correctly use - before the paths
Also fixed explanation for generic PR testing.
> Fix paths on github workflow for docs

- examples/refsi/refsi_g1_wi/compiler/refsi_g1_wi/source/refsi_mux_builtin_info.cpp
- modules/compiler/source/base/source/program_metadata.cpp
- modules/compiler/source/base/source/target.cpp
- modules/compiler/spirv-ll/source/builder_core.cpp
- modules/compiler/utils/include/compiler/utils/StructTypeRemapper.h
Each of these fixes is pretty self-explanatory.
> [compiler] Various fixes to compile (without warnings) with LLVM 17

- modules/compiler/vecz/source/transform/packetizer.cpp
- modules/compiler/vecz/test/lit/llvm/insert_element_debug_info.ll
- modules/compiler/vecz/test/lit/llvm/packetization_debug_info.ll
- modules/compiler/vecz/test/lit/llvm/phi_node_debug_info.ll
We were trying to update dbg.value intrinsics with the vectorized value and by updating the DIType to a constructed vector type.
Unfortunately we weren't always getting this right, and sometimes generating invalid debug expressions (noticed on LLVM 17).
I have evaluated the state of our debug info (with LLVM and lldb 16) and found while I was able to step through kernels with a source view, the experience is lacking overall and I was unable to inspect any variables at all, regardless of whether we vectorized or not.
Given the fact that LLVM 17 errors about some invalid debug locations and the fact we have no clear pathway towards fixing this properly, the best thing to do is to remove our support for vectorized dbg.value expressions for now.
We can revisit this with a broader view to …
> [vecz] Do not vectorize llvm.debug.value intrinsics

- scripts/testing/city_runner/test_info.py
Rather than `split(",")`, this uses Python's CSV module instead.
In our SYCL CTS CSV file, we would like to be able to represent
```
SYCL_CTS,test_multi_ptr "constructor multi_ptr(local_accessor<T\, dims>). *"
```
This is not currently representable.
The SYCL CTS contains tests whose names contains commas. When we split our CSV file on commas, this breaks down. Using Python's CSV parser instead allows us to easily handle this.
The handling of comments and blank lines is left as is for now to minimize the impact on CI.
Our current SYCL CTS CSV file will still not work with this change, it still needs to be changed too. The line above needs to be changed to
```
SYCL_CTS,"test_multi_ptr ""constructor multi_ptr(local_accessor<T\, dims>). *"""
```
This also allows the CSV file to be opened in …
> Use csv module for city runner

- modules/compiler/targets/host/source/kernel.cpp
This fixes a bug in the mux kernel query for the maximum number of sub-groups.
We were mistakenly returning a number of sub-groups higher than the maximum number of sub-groups reported by the device. The device correctly reports that the theoretical maximum number of sub-groups across all kernels was the maximum local work-group size. However, the kernel query was multiplying the theoretical maximum number of work-items in each of the separate X, Y, and Z dimensions together, which may exceed the maximum work-group size.
We're relying on the fact that the OpenCL and SYCL specifications allow this kind of flexible behaviour with regards to sub-group sizes (i.e., allowing the same kernel to exhibit different sub-group sizes depending on the ND range). Re-addressing this would take a much …
> [host] Fix the maximum number of sub-groups a kernel reports

- modules/compiler/vecz/source/transform/squash_small_vectors_pass.cpp
- modules/compiler/vecz/test/lit/llvm/squash_extract_zext.ll
This commit fixes the optimization when it is faced with vectors/integers (of the same size) whose bit-width is greater than 64 bits in size, or whose vector elements are at least 32 bits in size.
When the elements were at least 32 bits in size, the logic would exhibit UB and shift a 32-bit integer (`1`) left by 32. This was leading to incorrect code generation (the masks would come out as `0` rather than the intended `0xFFFF...`).
Furthermore, when the vectors are greater than 64 bits in size, the masking logic would break down as LLVM can only be given constants who are representable by `uint64_t` and so we wouldn't be able to correctly represent the mask.
At the same time, the the LIT test has been refactored to test only the pass, as the output of the packetizer is largely …
> [vecz] Fix SquashSmallVectorsPass on larger vectors

- modules/compiler/builtins/abacus/include/abacus/internal/is_odd.h
- modules/compiler/builtins/abacus/include/abacus/internal/multiply_exact.h
Fix exact multiplication of doubles, fix undefined behavior in is_odd.
We were seeing maths failures in the SYCL CTS.
Fix exact multiplication of doubles: The `multiply_exact_helper<abacus_half>` method has a comment explaining that the non-specialized version is wrong for floating point types with a mantissa with an odd number of bits. Like `half`, `double` also has an odd number of bits in the mantissa, and we were generating incorrect multiplication results as revealed by the SYCL CTS. So remove the `multiply_exact_helper<abacus_half>` specialization and fix the primary template definition instead.
Fix undefined behavior in is_odd: We would previously evaluate `mantissa << unbiasedExp` and then try to mask out the result based on `validExp` which tells us whether this shift is safe to …
> Fix exact multiplication of doubles, fix undefined behavior in is_odd.

- modules/compiler/targets/host/source/kernel.cpp
Try to recover from fatal JIT errors.
On ARM, the following disabled UnitCL tests result in errors that take down the whole UnitCL process:
Execution/HalfOperatorTest.Precision_03_Half_Add/OpenCLC_2
Execution/HalfOperatorTest.Precision_04_Half_Sub/OpenCLC_2
Execution/HalfOperatorTest.Precision_05_Half_Mul/OpenCLC_2
Execution/HalfOperatorTest.Precision_06_Half_Div/OpenCLC_2
Execution/HalfOperatorTest.Precision_07_Half_Recip/OpenCLC_2
With this change, after those tests fail, UnitCL is able to continue running to cover the remaining tests.
Note that we do fail an assertion at global test environment tear-down. This happens because CrashRecoveryContext is implemented via setjmp/longjmp, which is not required to call destructors for local objects. Likely, this already resulted in memory leaks …
> Try to recover from fatal JIT errors.

- .github/actions/build_vgg_resnet_action/action.yml
- .github/workflows/run_ock_demo.yml
- doc/developer-guide.md
- examples/applications/CMakeLists.txt
- examples/applications/clVectorAddition/main.c
- examples/applications/simple-vector-add.cpp
- examples/applications/vector_addition-load-store.cpp
- examples/applications/vector_addition-masked-store.cpp
- examples/applications/vector_addition-predicated.cpp
- examples/applications/vector_addition-tiled-load-store.cpp
Adding a sample of RISCV examples to OCK to be tested with oneapi.
A few tests from RISCV examples are added to be tested as a part of new OCK demo package.
> Adding riscv testing to OCK repo

- modules/mux/targets/riscv/source/device_info.cpp
[RISC-V] Report denormal support.
RISC-V supports these just fine.
points, etc.*
* Make sure the project builds …
> [RISC-V] Report denormal support.

- source/cl/tools/clc/clc.cpp
- source/cl/tools/oclc/oclc.cpp
Improve error handling.
This addresses a few warnings by clang-tidy-17.
clc's driver::saveBinary and oclc's oclc::Driver::BuildProgram and oclc::Driver::WriteToFile have a result that allows them to indicate failure, but several I/O functions were not checked for errors. Additionally, driver::saveBinary would close stdin when it had not opened it, which is not its responsibility.
* Run …
> Improve error handling.

- doc/CMakeLists.txt
[doc] Add missing dependency.
We link to Abacus documentation, but because that is defined in header files that were not registered as a dependency, we did not generate them during CI and were left with broken references to nonexistent docs.
points, etc.*
understanding and verifying your patch, please include it …
> [doc] Add missing dependency.

- modules/compiler/vecz/source/offset_info.cpp
- modules/compiler/vecz/source/transform/squash_small_vectors_pass.cpp
This should make the code a little more readable at first glance.
> [vecz] Use LLVM helper for testing for powers of 2

- modules/compiler/vecz/source/analysis/stride_analysis.cpp
- modules/compiler/vecz/source/include/analysis/stride_analysis.h
- modules/compiler/vecz/source/passes.def
- modules/compiler/vecz/test/lit/llvm/stride_analysis.ll
This should help better singularly "unit test" the raw results of the StrideAnalysis, in which we know there are some bugs.
Any bugs fixed in the StrideAnalysis can be added to this regression test over time.
> [vecz] Add a pass to print StrideAnalysis results

- modules/compiler/targets/host/source/target.cpp
Fix const error flagged by tidy
> Fix const error flagged by tidy

- hal/source/arg_pack.cpp
Windows does not support std::aligned_alloc, so use _aligned_malloc instead.
Windows does not support std::aligned_alloc, so use _aligned_malloc instead.
> Fix windows failure due to std::aligned_alloc

- modules/compiler/utils/include/compiler/utils/barrier_regions.h
- modules/compiler/utils/source/barrier_regions.cpp
- modules/compiler/utils/source/work_item_loops_pass.cpp
- modules/compiler/vecz/source/transform/scalarizer.cpp
Update for LLVM 19.
Various new debug info things have been renamed.
points, etc.* …
> Update for LLVM 19.

- source/cl/test/UnitCL/source/C11Atomics.cpp
[UnitCL] Fix C11Atomics_76_*, C11Atomics_77_*, C11Atomics_78_*
These tests test atomic_compare_exchange_weak_explicit which is allowed to fail for no clear reason. The test tries to account for this by detecting output differences, using that to fill a weak_exchanges_failed vector, and using that weak_exchanges_failed vector to detect where the result of atomic_compare_exchange_weak_explicit does not match expectations. That is, in output_reference, it does:
if (value == expected_values[success_indices[index]]) {
weak_exchanges_failed[index / kts::localN] = true;
return true;
}
Then, in bool_output_reference, it does:
const size_t work_group = index / kts::localN;
const size_t success_index_of_workgroup = success_indices[work_group];
return (index == success_index_of_workgroup) && …
> [UnitCL] Fix C11Atomics_76_*, C11Atomics_77_*, C11Atomics_78_*

- source/cl/source/command_queue.cpp
Do not skip events.
In clEnqueueBarrierWithWaitList, clEnqueueMarkerWithWaitList, and clEnqueueWaitForEvents we were assuming that all events to wait for would be from the same queue, and therefore implicit dependencies would take care of it already. There is no such requirement, events to wait for may be for different queues, they are merely required to have the same OpenCL context.
This change ensures we always wait on the requested events.
No UnitCL test is added as this is difficult to test for reliably, and was caught by the OpenCL CTS already. …
> Do not skip events.

- modules/mux/targets/host/source/kernel.cpp
[host] Fix hostQueryLocalSizeForSubGroupCount
When we fixed HostKernel::queryLocalSizeForSubGroupCount last year, we missed that the JIT and non-JIT paths go through different code paths, and the same fix is also needed for hostQueryLocalSizeForSubGroupCount.
points, etc.*
understanding and verifying your patch, …
> [host] Fix hostQueryLocalSizeForSubGroupCount

- doc/developer-guide.md
Update developer guide formatting.
Apply markdownlint suggestions where possible.
> Update developer guide formatting.

- modules/compiler/targets/host/source/target.cpp
[host][RISC-V] Do not set ABI.
We were setting ABI to ilp32d/lp64d, which with FP64=ON is the default ABI, and with FP64=OFF results in an error.
Simplify by not setting it at all.
> [host][RISC-V] Do not set ABI.

- scripts/testing/city_runner/profiles/default.py
This allows city runner to prepend a path without an additional profile.
We want to use qemu on different profiles.
Add --prepend-file to default.py to make available to all profiles. This gives it similar ability to --qemu and can be used in that way.
> Support --prepend_path in city city_runner

- .github/actions/setup_ubuntu_build/action.yml
- .github/workflows/create_llvm.yml
Add github workflow cross-compilation of aarch64
Allow aarch64 testing of OCK
Modified workflow to support extra flags, and cache naming to include arch.
> github workflow cross compiling for aarch64

- source/cl/test/UnitCL/source/C11Atomics.cpp
[UnitCL] Fix C11Atomics_67*...C11Atomics_72*
As with the later C11Atomics_* tests, these tests try to account for atomic_compare_exchange_weak sporadically failing, as it is permitted to, by detecting output differences and using that to determine whether atomic_compare_exchange_weak's result must have been true, or must have been false. However, unlike the later C11Atomics_* tests, these tests were not ensuring that the random data was unique. Therefore, it was possible to wrongly detect that an atomic_compare_exchange_weak operation must have succeeded because the data was equal to the data that it tried to set it to, except the operation had actually failed because the old data was, by random chance, already equal to the data that it tried to set it to. Because of how our random …
> [UnitCL] Fix C11Atomics_67*...C11Atomics_72*

- .github/workflows/create_llvm.yml
Add windows to list of builds for llvm
Required for some our OCK testing.
> Add windows build of llvm to testing

- .github/actions/setup_ubuntu_build/action.yml
Add prereqs for ubuntu MR jobs run to date (very likely there are more prereqs to come)
Allow MR jobs to run.
Misc installs. Tested in my fork.
> Add ubuntu MR job install prereqs

- .github/CODEOWNERS
Update CODEOWNERS file for UXL
Moving repo ownership
Changed to uxlfoundation as repo.
> Update CODEOWNERS file for UXL

- modules/compiler/compiler_pipeline/source/align_module_structs_pass.cpp
[AlignModuleStructsPass] Update types in constants
Execution.Regression_35_Constant_Struct_Alignment reveals on LLVM 20 that if a constant expression references a type that needs to be replaced, we were ignoring it unless the constant expression also happened to contain references to globals that need to be replaced.
Do a pass over constant operands and update them to instructions as needed.
* Run …
> [AlignModuleStructsPass] Update types in constants

- README.md
Addressing https://github.com/uxlfoundation/open-source-working-group/issues/153
points, etc.*
* Read and follow the …
> updates for UXL

- .editorconfig
- .github/workflows/jekyll-gh-pages.yml
- rfc-0000.md
- rfc-0001.md
- rfc-0002.md
Add RFCs system based on Python PEPs.
points, etc.* …
> Add RFCs system based on Python PEPs.

- .github/workflows/codeql.yml
Limit to a schedule and resolve at that point.
This is taking up too much time
> [codeql] Reduce running of codeql to schedule

- .github/dockerfiles/Dockerfile_22.04
- .github/dockerfiles/Dockerfile_24.04
- .github/workflows/publish_docker_images.yml
Initial dockerfiles and workflow definition.
We need our own dockers.
Dockerfiles for ubuntu 22 & 24.
Basic workflow to support image building and pushing to registry
> First dockers

- .github/dockerfiles/Dockerfile_22.04
- .github/dockerfiles/Dockerfile_24.04
- .github/workflows/publish_docker_images.yml
Docker updates for the first production versions.
Workflows are being "containerised". A further PR for workflow/action updates to follow when the new dockers are built.
New containers will be built from these dockerfiles and the updated workflows will then be pointed at them in a second related PR.
Plan is to merge the second PR immediately the new containers are available.
> Production docker updates.

- rfc-0000.md
- rfc-0001.md
- rfc-0002.md
- rfc-0002/rfc-NNNN.md
RFC 2: Include more detail on how to write RFCs.
points, etc.*
Also fix the headers of RFC 1.
* Make sure the project builds …
> RFC 2: Include more detail on how to write RFCs.

- _layouts/default.html
Include preamble in rendered HTML.
points, etc.* …
> Include preamble in rendered HTML.

- .github/workflows/pr_tests_cache.yml
Changes workflow/ to workflows/ in the pr tests cache workflow
Was not running as expected.
> Fix typo on changed files causing a rerun.

- .github/actions/run_sycl_cts/action.yml
- scripts/testing/sycl-cts.csv
Update sycl-cts.csv, move to a more general location.
points, etc.* …
> Update sycl-cts.csv, move to a more general location.

- source/cl/source/kernel.cpp
Fix CL_KERNEL_LOCAL_MEM_SIZE.
We were only returning the memory needed by the kernel, but we need to return memory needed by kernel arguments as well.
points, etc.*
This fixes an error reported by OpenCL CTS `test_abi`'s `kernel_local_memory_size` test.
* …
> Fix CL_KERNEL_LOCAL_MEM_SIZE.

- .github/dockerfiles/Dockerfile_22.04-aarch64
- .github/dockerfiles/Dockerfile_22.04-x86-64
- .github/dockerfiles/Dockerfile_24.04-x86-64
Add LLVM 20 to docker file install sources
Getting ready for switch to llvm 19/20
> [CI] Updated docker files so we can install llvm 20

- .github/sycl_cts/override_all.csv
Add test_language to sycl_cts expected fails.
Failure over night
> [CI] Add test_language to sycl_cts expected fails.

- scripts/testing/city_runner/test_info.py
Preserve test order.
We were sorting the list of failed tests, but it is easier to go over the list when they appear in the same order as in the input test list.
points, etc.* …
> Preserve test order.

- scripts/testing/sycl_cts/override_opencl_host_aarch64_linux.csv
Remove test_reduction MayFail.
We have not seen this fail recently. If it fails again we can look into it at that time.
points, etc.*
* Read and follow the project [Code of Conduct](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/ …
> Remove test_reduction MayFail.

- rfc-0003.md
After some comments in
https://github.com/uxlfoundation/oneapi-construction-kit/discussions/670 some minor updates have been made for clarity.
> Added updates to VULKAN-SDK removeal RFC-0003.md after updates.

- scripts/testing/patches/DPCPP-0001-SYCL-NativeCPU-Add-libclc-at-compile-time.patch
- scripts/testing/patches/DPCPP-0002-SYCL-NativeCPU-Move-__spirv_AtomicF-Add-Min-Max-EXT-.patch
- scripts/testing/patches/DPCPP-0003-SYCL-NativeCPU-Update-clang-linker-wrapper.patch
Update DPC++ patches.
A conflicting change has been merged upstream.
points, etc.* …
> Update DPC++ patches.

- rfc-0003.md
Update vulkan rfc state to accepted
rfc-0003.md has been reviewed and accepted
points, etc.*
* Make sure the …
> Update vulkan rfc state to accepted

- modules/compiler/cookie/{{cookiecutter.target_name}}/source/module.cpp
- modules/compiler/riscv/source/module.cpp
- modules/compiler/source/base/source/module.cpp
[LLVM 21] Use llvm::driver::createTLII.
LLVM 21 renames llvm::TargetLibraryInfoImpl::LIBMVEC_X86 to llvm::TargetLibraryInfoImpl::LIBMVEC and changes it to apply across targets.
There is also a utility function llvm::driver::createTLII which has existed for longer, which we were effectively re-implementing, and which avoids our need to know about this rename. Just call that.
* Run …
> [LLVM 21] Use llvm::driver::createTLII.

- scripts/testing/sycl_e2e/override_all.csv
Fix e2e threadsan override entries
'/' should be ','
> Fix e2e threadsan override entries

- scripts/testing/sycl_e2e/override_native_cpu.csv
- scripts/testing/sycl_e2e/override_opencl.csv
Update e2e overrides from latest (L20) xpasses or fails
> Update e2e overrides from latest (L20) xpasses or fails

- scripts/testing/sycl_cts/override_opencl.csv
- scripts/testing/sycl_e2e/override_opencl.csv
Add more overrides for submit_time and test_bit_cast
> Add more overrides for submit_time and test_bit_cast

- .github/workflows/pr_tests_cache.yml
- .github/workflows/publish_docker_images.yml
More permission tweaking.
* pr_test_cache.yml: actions: write should not be necessary outside of clean_cache, which already specifies that. Drop it at the workflow level.
* publish_docker_images.yml: move write permissions from workflow level to job level.
* Run …
> More permission tweaking.

- override_native_cpu.csv
- scripts/testing/sycl_cts/override_all.csv
- scripts/testing/sycl_e2e/override_all.csv
- scripts/testing/sycl_e2e/override_native_cpu.csv
- scripts/testing/sycl_e2e/override_opencl.csv
Added more Graph/FreeFunction overrides and removed some MayFails
> [OVERRIDES] Added more Graph/FreeFunction overrides and removed some MayFails

- override_native_cpu.csv
- scripts/testing/sycl_cts/override_native_cpu.csv
Move override_native_cpu.csv to correct directory.
#867 added this to the top level by mistake.
points, etc.*
* …
> Move override_native_cpu.csv to correct directory.

- scripts/testing/patches/DPCPP-0001-SYCL-NativeCPU-Add-libclc-at-compile-time.patch
- scripts/testing/patches/DPCPP-0002-SYCL-NativeCPU-Move-__spirv_AtomicF-Add-Min-Max-EXT-.patch
- scripts/testing/patches/DPCPP-0003-SYCL-NativeCPU-Update-clang-linker-wrapper.patch
Update DPC++ patches again.
points, etc.* …
> Update DPC++ patches again.

- scripts/testing/patches/DPCPP-0002-SYCL-NativeCPU-Create-NativeCPUABIInfo.patch
- scripts/testing/patches/DPCPP-0003-NFC-Remove-getDefaultCallingConvention-IsBuiltin.patch
- scripts/testing/patches/DPCPP-0004-SYCL-NativeCPU-Limit-generic-ABI-to-builtins.patch
- scripts/testing/patches/DPCPP-0005-SYCL-NativeCPU-Add-libclc-at-compile-time.patch
- scripts/testing/patches/DPCPP-0006-SYCL-NativeCPU-Move-__spirv_AtomicF-Add-Min-Max-EXT-.patch
- scripts/testing/patches/DPCPP-0007-SYCL-NativeCPU-Update-clang-linker-wrapper.patch
- scripts/testing/sycl_e2e/override_all.csv
- scripts/testing/sycl_e2e/override_native_cpu.csv
- scripts/testing/sycl_e2e/override_opencl.csv
Update DPC++ patches to fix calling convention bugs.
points, etc.* …
> Update DPC++ patches to fix calling convention bugs.

- scripts/testing/sycl_e2e/known.csv
- scripts/testing/sycl_e2e/override_all.csv
- scripts/testing/sycl_e2e/override_native_cpu.csv
- scripts/testing/sycl_e2e/override_opencl.csv
> [E2E][CI] Update known and overrides to reflect latest results

- modules/cargo/include/cargo/argument_parser.h
[cargo][NFC] Use std::variant in argument parser.
Through argument's Type field and its anonymous union, we were effectively creating our own custom std::variant, except less featureful and not capable of handling not-trivially-destructible types, which is why CustomHandler was kept out of the union. There is no advantage to this hand-coded version and it results in compiler warnings that then need to be suppressed.
Just use std::variant directly instead. …
> [cargo][NFC] Use std::variant in argument parser.

- .github/workflows/planned_testing_caller_19.yml
- .github/workflows/planned_testing_caller_21.yml
- .github/workflows/planned_testing_caller_main.yml
- .github/workflows/planned_testing_caller_mini_main.yml
Add testing for llvm 21
llvm 21 is branched
> Add testing for llvm 21 and full main

- scripts/testing/sycl_e2e/override_opencl.csv
Added extra e2e reduction range override after recent fails
> [CI][E2E] Added extra e2e reduction range override after recent fails

- CONTRIBUTING.md
- README.md
> Add links to documentation

- .github/workflows/run_ock_external_tests.yml
- scripts/testing/sycl_cts/override_native_cpu.csv
- scripts/testing/sycl_cts/override_opencl.csv
- scripts/testing/sycl_e2e/override_native_cpu.csv
Fix up overrides and race condition
> [CI] Fix up overrides and race condition

- rfc-0000.md
- rfc-0001.md
Update RFCs to account for new location.
The process for including OCK documentation and RFCs in the same place resulted in poorly rendered documentation. The change to address this moves where RFCs are stored.
This commit implements the required changes to account for the new location.
> Update RFCs to account for new location.

- .github/workflows/codeql.yml
- .github/workflows/planned_testing_caller_main.yml
- .github/workflows/scorecard.yml
[NFC] Add and correct cron comments.
points, etc.* …
> [NFC] Add and correct cron comments.

- .github/workflows/run_ock_external_tests.yml
Build DPC++ on Ubuntu 24.04.
This matches what is run in DPC++'s own CI and reduces the number of issues we will encounter.
points, etc.*
* Read and follow the project [Code of Conduct](https://github.com/uxlfoundation/oneapi-construction-kit/blob/main …
> Build DPC++ on Ubuntu 24.04.

- modules/compiler/vecz/source/transform/control_flow_conversion_pass.cpp
[vecz] Avoid more dangling references.
Since we rely on LoopMasks[...] not creating new map entries, since they should have been created in advance, use LoopMasks.at(...) instead. This reveals that with BOSCC, there was one case that the previous fix missed, which this commit also fixes.
* Run relevant testing locally to …
> [vecz] Avoid more dangling references.

- modules/compiler/vecz/test/lit/llvm/subgroup_reductions.ll
[LLVM 22] Adjust test for new optimisation.
LLVM 22 is able to optimise a reduce.add of a splat into a multiplication.
Adjust one test to allow this.
* Run [clang-format-21](https://clang.llvm.org/docs/ClangFormat.html) on all modified code.
> [LLVM 22] Adjust test for new optimisation.
